// This file was automatically generated by the Panda compiler
#ifndef $LPInt64$CInt64$RP_H
#define $LPInt64$CInt64$RP_H
extern panda$core$Class $LPInt64$CInt64$RP_class;
#ifndef CLASS_$LPInt64$CInt64$RP
#define CLASS_$LPInt64$CInt64$RP
struct $LPInt64$CInt64$RP {
    panda$core$Class* cl;
    Int64 $field0;
    Int64 $field1;
};

#define $LPpanda$core$Int64$Cpanda$core$Int64$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$core$Int64$RP$convert_$Rpanda$core$String_TYPE)($LPInt64$CInt64$RP* self);
#define $LPpanda$core$Int64$Cpanda$core$Int64$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$core$Int64$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPInt64$CInt64$RP* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$core$Int64$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$core$Int64$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPInt64$CInt64$RP* self);
#define $LPpanda$core$Int64$Cpanda$core$Int64$RP$$ARR_Int32_$Rpanda$core$Int64_INDEX 4
typedef Int64($LPpanda$core$Int64$Cpanda$core$Int64$RP$$ARR_Int32_$Rpanda$core$Int64_TYPE)($LPInt64$CInt64$RP* self, Int32);
void $LPpanda$core$Int64$Cpanda$core$Int64$RP$init_Int64_Int64($LPInt64$CInt64$RP* self, Int64, Int64);
$LPInt64$CInt64$RP* new_$LPpanda$core$Int64$Cpanda$core$Int64$RP$init_Int64_Int64(Int64, Int64);
panda$core$String* $LPpanda$core$Int64$Cpanda$core$Int64$RP$convert_$Rpanda$core$String($LPInt64$CInt64$RP* self);
Bit $LPpanda$core$Int64$Cpanda$core$Int64$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPInt64$CInt64$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$core$Int64$RP$get_hash_$Rpanda$core$Int64($LPInt64$CInt64$RP* self);
Int64 $LPpanda$core$Int64$Cpanda$core$Int64$RP$$ARR_Int32_$Rpanda$core$Int64($LPInt64$CInt64$RP* self, Int32);
#endif
#endif
