// This file was automatically generated by the Panda compiler
#ifndef $LPInt64$CUInt16$RP_H
#define $LPInt64$CUInt16$RP_H
extern panda$core$Class $LPInt64$CUInt16$RP_class;
#ifndef CLASS_$LPInt64$CUInt16$RP
#define CLASS_$LPInt64$CUInt16$RP
struct $LPInt64$CUInt16$RP {
    panda$core$Class* cl;
    Int64 $field0;
    UInt16 $field1;
};

#define $LPpanda$core$Int64$Cpanda$core$UInt16$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$core$UInt16$RP$convert_$Rpanda$core$String_TYPE)($LPInt64$CUInt16$RP* self);
#define $LPpanda$core$Int64$Cpanda$core$UInt16$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$core$UInt16$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPInt64$CUInt16$RP* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$core$UInt16$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$core$UInt16$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPInt64$CUInt16$RP* self);
#define $LPpanda$core$Int64$Cpanda$core$UInt16$RP$$ARR_Int32_$Rpanda$core$Integer_INDEX 4
typedef panda$core$Integer*($LPpanda$core$Int64$Cpanda$core$UInt16$RP$$ARR_Int32_$Rpanda$core$Integer_TYPE)($LPInt64$CUInt16$RP* self, Int32);
void $LPpanda$core$Int64$Cpanda$core$UInt16$RP$init_Int64_UInt16($LPInt64$CUInt16$RP* self, Int64, UInt16);
$LPInt64$CUInt16$RP* new_$LPpanda$core$Int64$Cpanda$core$UInt16$RP$init_Int64_UInt16(Int64, UInt16);
panda$core$String* $LPpanda$core$Int64$Cpanda$core$UInt16$RP$convert_$Rpanda$core$String($LPInt64$CUInt16$RP* self);
Bit $LPpanda$core$Int64$Cpanda$core$UInt16$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPInt64$CUInt16$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$core$UInt16$RP$get_hash_$Rpanda$core$Int64($LPInt64$CUInt16$RP* self);
panda$core$Integer* $LPpanda$core$Int64$Cpanda$core$UInt16$RP$$ARR_Int32_$Rpanda$core$Integer($LPInt64$CUInt16$RP* self, Int32);
#endif
#endif
