// This file was automatically generated by the Panda compiler
#ifndef $LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP_H
#define $LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP_H
extern panda$core$Class $LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP_class;
#ifndef CLASS_$LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP
#define CLASS_$LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP
struct $LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP {
    panda$core$Class* cl;
    Int64 $field0;
    $LPpanda$core$Immutable$Cpanda$core$Immutable$RP* $field1;
};

#define $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$convert_$Rpanda$core$String_TYPE)($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self);
#define $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self, panda$core$Object*);
#define $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self);
#define $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$$ARR_Int32_$Rpanda$core$Value_INDEX 4
typedef panda$core$Value*($LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$$ARR_Int32_$Rpanda$core$Value_TYPE)($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self, Int32);
void $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$init_Int64_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self, Int64, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
$LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* new_$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$init_Int64_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP(Int64, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
panda$core$String* $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$convert_$Rpanda$core$String($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self);
Bit $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$get_hash_$Rpanda$core$Int64($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self);
panda$core$Value* $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$$ARR_Int32_$Rpanda$core$Value($LPInt64$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP* self, Int32);
#endif
#endif
