// This file was automatically generated by the Panda compiler
#ifndef $LPInt64$CChar$RP_H
#define $LPInt64$CChar$RP_H
extern panda$core$Class $LPInt64$CChar$RP_class;
#ifndef CLASS_$LPInt64$CChar$RP
#define CLASS_$LPInt64$CChar$RP
struct $LPInt64$CChar$RP {
    panda$core$Class* cl;
    Int64 $field0;
    Char $field1;
};

#define $LPpanda$core$Int64$Cpanda$core$Char$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$core$Char$RP$convert_$Rpanda$core$String_TYPE)($LPInt64$CChar$RP* self);
#define $LPpanda$core$Int64$Cpanda$core$Char$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$core$Char$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPInt64$CChar$RP* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$core$Char$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$core$Char$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPInt64$CChar$RP* self);
#define $LPpanda$core$Int64$Cpanda$core$Char$RP$$ARR_Int32_$Rpanda$core$Primitive_INDEX 4
typedef panda$core$Primitive*($LPpanda$core$Int64$Cpanda$core$Char$RP$$ARR_Int32_$Rpanda$core$Primitive_TYPE)($LPInt64$CChar$RP* self, Int32);
void $LPpanda$core$Int64$Cpanda$core$Char$RP$init_Int64_Char($LPInt64$CChar$RP* self, Int64, Char);
$LPInt64$CChar$RP* new_$LPpanda$core$Int64$Cpanda$core$Char$RP$init_Int64_Char(Int64, Char);
panda$core$String* $LPpanda$core$Int64$Cpanda$core$Char$RP$convert_$Rpanda$core$String($LPInt64$CChar$RP* self);
Bit $LPpanda$core$Int64$Cpanda$core$Char$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPInt64$CChar$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$core$Char$RP$get_hash_$Rpanda$core$Int64($LPInt64$CChar$RP* self);
panda$core$Primitive* $LPpanda$core$Int64$Cpanda$core$Char$RP$$ARR_Int32_$Rpanda$core$Primitive($LPInt64$CChar$RP* self, Int32);
#endif
#endif
