// This file was automatically generated by the Panda compiler
#ifndef $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP_H
#define $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP_H
extern panda$core$Class $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP_class;
#ifndef CLASS_$LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP
#define CLASS_$LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP
struct $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP {
    panda$core$Class* cl;
    Int64 $field0;
    panda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT* $field1;
};

#define $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$convert_$Rpanda$core$String_TYPE)($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self);
#define $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self);
#define $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$$ARR_Int32_$Rpanda$core$Immutable_INDEX 4
typedef panda$core$Immutable*($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$$ARR_Int32_$Rpanda$core$Immutable_TYPE)($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self, Int32);
void $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$init_Int64_panda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self, Int64, panda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT*);
$LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* new_$LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$init_Int64_panda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT(Int64, panda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT*);
panda$core$String* $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$convert_$Rpanda$core$String($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self);
Bit $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$get_hash_$Rpanda$core$Int64($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self);
panda$core$Immutable* $LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP$$ARR_Int32_$Rpanda$core$Immutable($LPpanda$core$Int64$Cpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$RP* self, Int32);
#endif
#endif
