// This file was automatically generated by the Panda compiler
#ifndef $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP_H
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP_H
extern panda$core$Class $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP_class;
#ifndef CLASS_$LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP
#define CLASS_$LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP
struct $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP {
    panda$core$Class* cl;
    Int64 $field0;
    panda$parser$GLRParser$ParseError* $field1;
};

#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$convert_$Rpanda$core$String_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$ARR_Int32_$Rpanda$core$Immutable_INDEX 4
typedef panda$core$Immutable*($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$ARR_Int32_$Rpanda$core$Immutable_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self, Int32);
void $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$init_Int64_panda$parser$GLRParser$ParseError($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self, Int64, panda$parser$GLRParser$ParseError*);
$LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* new_$LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$init_Int64_panda$parser$GLRParser$ParseError(Int64, panda$parser$GLRParser$ParseError*);
panda$core$String* $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$convert_$Rpanda$core$String($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self);
Bit $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$get_hash_$Rpanda$core$Int64($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self);
panda$core$Immutable* $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$ARR_Int32_$Rpanda$core$Immutable($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP* self, Int32);
#endif
#endif
