// This file was automatically generated by the Panda compiler
#ifndef $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_H
#define $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_H
extern panda$core$Class $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_class;
#ifndef CLASS_$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP
#define CLASS_$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP
struct $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP {
    panda$core$Class* cl;
    panda$core$Object* $field0;
    panda$core$Object* $field1;
};

#define $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$convert_$Rpanda$core$String_TYPE)($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self);
#define $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self, panda$core$Object*);
#define $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self);
#define $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$$ARR_Int32_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$$ARR_Int32_$Rpanda$core$Object$Z_TYPE)($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self, Int32);
void $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$init_panda$core$Object$Z_panda$core$Object$Z($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self, panda$core$Object*, panda$core$Object*);
$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* new_$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$init_panda$core$Object$Z_panda$core$Object$Z(panda$core$Object*, panda$core$Object*);
panda$core$String* $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$convert_$Rpanda$core$String($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self);
Bit $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$get_hash_$Rpanda$core$Int64($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self);
panda$core$Object* $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$$ARR_Int32_$Rpanda$core$Object$Z($LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP* self, Int32);
#endif
#endif
