// This file was automatically generated by the Panda compiler
#ifndef $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP_H
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP_H
extern panda$core$Class $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP_class;
#ifndef CLASS_$LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP
#define CLASS_$LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP
struct $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP {
    panda$core$Class* cl;
    Int64 $field0;
    panda$parser$GLRParser$Action* $field1;
};

#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$convert_$Rpanda$core$String_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$get_hash_$Rpanda$core$Int64_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$$ARR_Int32_$Rpanda$core$Object_INDEX 4
typedef panda$core$Object*($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$$ARR_Int32_$Rpanda$core$Object_TYPE)($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self, Int32);
void $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$init_Int64_panda$parser$GLRParser$Action($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self, Int64, panda$parser$GLRParser$Action*);
$LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* new_$LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$init_Int64_panda$parser$GLRParser$Action(Int64, panda$parser$GLRParser$Action*);
panda$core$String* $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$convert_$Rpanda$core$String($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self);
Bit $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$$EQ_panda$core$Object_$Rpanda$core$Bit($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$get_hash_$Rpanda$core$Int64($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self);
panda$core$Object* $LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP$$ARR_Int32_$Rpanda$core$Object($LPpanda$core$Int64$Cpanda$parser$GLRParser$Action$RP* self, Int32);
#endif
#endif
