// This file was automatically generated by the Panda compiler
#ifndef (Int64,Real64)_H
#define (Int64,Real64)_H
extern panda$core$Class (Int64,Real64)_class;
#ifndef CLASS_(Int64,Real64)
#define CLASS_(Int64,Real64)
struct (Int64,Real64) {
    panda$core$Class* cl;
    Int64 $field0;
    Real64 $field1;
};

#define $LPpanda$core$Int64$Cpanda$core$Real64$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$core$Real64$RP$convert_$Rpanda$core$String_TYPE)((Int64,Real64)* self);
#define $LPpanda$core$Int64$Cpanda$core$Real64$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$core$Real64$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)((Int64,Real64)* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$core$Real64$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$core$Real64$RP$get_hash_$Rpanda$core$Int64_TYPE)((Int64,Real64)* self);
#define $LPpanda$core$Int64$Cpanda$core$Real64$RP$$ARR_Int32_$Rpanda$core$Number_INDEX 4
typedef panda$core$Number*($LPpanda$core$Int64$Cpanda$core$Real64$RP$$ARR_Int32_$Rpanda$core$Number_TYPE)((Int64,Real64)* self, Int32);
void $LPpanda$core$Int64$Cpanda$core$Real64$RP$init_Int64_Real64((Int64,Real64)* self, Int64, Real64);
(Int64,Real64)* new_$LPpanda$core$Int64$Cpanda$core$Real64$RP$init_Int64_Real64(Int64, Real64);
panda$core$String* $LPpanda$core$Int64$Cpanda$core$Real64$RP$convert_$Rpanda$core$String((Int64,Real64)* self);
Bit $LPpanda$core$Int64$Cpanda$core$Real64$RP$$EQ_panda$core$Object_$Rpanda$core$Bit((Int64,Real64)* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$core$Real64$RP$get_hash_$Rpanda$core$Int64((Int64,Real64)* self);
panda$core$Number* $LPpanda$core$Int64$Cpanda$core$Real64$RP$$ARR_Int32_$Rpanda$core$Number((Int64,Real64)* self, Int32);
#endif
#endif
