// This file was automatically generated by the Panda compiler
#ifndef (Int64,Int8)_H
#define (Int64,Int8)_H
extern panda$core$Class (Int64,Int8)_class;
#ifndef CLASS_(Int64,Int8)
#define CLASS_(Int64,Int8)
struct (Int64,Int8) {
    panda$core$Class* cl;
    Int64 $field0;
    Int8 $field1;
};

#define $LPpanda$core$Int64$Cpanda$core$Int8$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$core$Int8$RP$convert_$Rpanda$core$String_TYPE)((Int64,Int8)* self);
#define $LPpanda$core$Int64$Cpanda$core$Int8$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$core$Int8$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)((Int64,Int8)* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$core$Int8$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$core$Int8$RP$get_hash_$Rpanda$core$Int64_TYPE)((Int64,Int8)* self);
#define $LPpanda$core$Int64$Cpanda$core$Int8$RP$$ARR_Int32_$Rpanda$core$SignedInteger_INDEX 4
typedef panda$core$SignedInteger*($LPpanda$core$Int64$Cpanda$core$Int8$RP$$ARR_Int32_$Rpanda$core$SignedInteger_TYPE)((Int64,Int8)* self, Int32);
void $LPpanda$core$Int64$Cpanda$core$Int8$RP$init_Int64_Int8((Int64,Int8)* self, Int64, Int8);
(Int64,Int8)* new_$LPpanda$core$Int64$Cpanda$core$Int8$RP$init_Int64_Int8(Int64, Int8);
panda$core$String* $LPpanda$core$Int64$Cpanda$core$Int8$RP$convert_$Rpanda$core$String((Int64,Int8)* self);
Bit $LPpanda$core$Int64$Cpanda$core$Int8$RP$$EQ_panda$core$Object_$Rpanda$core$Bit((Int64,Int8)* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$core$Int8$RP$get_hash_$Rpanda$core$Int64((Int64,Int8)* self);
panda$core$SignedInteger* $LPpanda$core$Int64$Cpanda$core$Int8$RP$$ARR_Int32_$Rpanda$core$SignedInteger((Int64,Int8)* self, Int32);
#endif
#endif
