// This file was automatically generated by the Panda compiler
#ifndef (Int64,panda$parser$GLRParser$ParseError)_H
#define (Int64,panda$parser$GLRParser$ParseError)_H
extern panda$core$Class (Int64,panda$parser$GLRParser$ParseError)_class;
#ifndef CLASS_(Int64,panda$parser$GLRParser$ParseError)
#define CLASS_(Int64,panda$parser$GLRParser$ParseError)
struct (Int64,panda$parser$GLRParser$ParseError) {
    panda$core$Class* cl;
    Int64 $field0;
    panda$parser$GLRParser$ParseError* $field1;
};

#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$convert_$Rpanda$core$String_TYPE)((Int64,panda$parser$GLRParser$ParseError)* self);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)((Int64,panda$parser$GLRParser$ParseError)* self, panda$core$Object*);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$get_hash_$Rpanda$core$Int64_TYPE)((Int64,panda$parser$GLRParser$ParseError)* self);
#define $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$ARR_Int32_$Rpanda$core$Immutable_INDEX 4
typedef panda$core$Immutable*($LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$ARR_Int32_$Rpanda$core$Immutable_TYPE)((Int64,panda$parser$GLRParser$ParseError)* self, Int32);
void $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$init_Int64_panda$parser$GLRParser$ParseError((Int64,panda$parser$GLRParser$ParseError)* self, Int64, panda$parser$GLRParser$ParseError*);
(Int64,panda$parser$GLRParser$ParseError)* new_$LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$init_Int64_panda$parser$GLRParser$ParseError(Int64, panda$parser$GLRParser$ParseError*);
panda$core$String* $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$convert_$Rpanda$core$String((Int64,panda$parser$GLRParser$ParseError)* self);
Bit $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$EQ_panda$core$Object_$Rpanda$core$Bit((Int64,panda$parser$GLRParser$ParseError)* self, panda$core$Object*);
Int64 $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$get_hash_$Rpanda$core$Int64((Int64,panda$parser$GLRParser$ParseError)* self);
panda$core$Immutable* $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP$$ARR_Int32_$Rpanda$core$Immutable((Int64,panda$parser$GLRParser$ParseError)* self, Int32);
#endif
#endif
