// This file was automatically generated by the Panda compiler
#ifndef (panda$core$String,panda$core$Object)_H
#define (panda$core$String,panda$core$Object)_H
extern panda$core$Class (panda$core$String,panda$core$Object)_class;
#ifndef CLASS_(panda$core$String,panda$core$Object)
#define CLASS_(panda$core$String,panda$core$Object)
struct (panda$core$String,panda$core$Object) {
    panda$core$Class* cl;
    panda$core$String* $field0;
    panda$core$Object* $field1;
};

#define $LPpanda$core$String$Cpanda$core$Object$Z$RP$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*($LPpanda$core$String$Cpanda$core$Object$Z$RP$convert_$Rpanda$core$String_TYPE)((panda$core$String,panda$core$Object)* self);
#define $LPpanda$core$String$Cpanda$core$Object$Z$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit($LPpanda$core$String$Cpanda$core$Object$Z$RP$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)((panda$core$String,panda$core$Object)* self, panda$core$Object*);
#define $LPpanda$core$String$Cpanda$core$Object$Z$RP$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64($LPpanda$core$String$Cpanda$core$Object$Z$RP$get_hash_$Rpanda$core$Int64_TYPE)((panda$core$String,panda$core$Object)* self);
#define $LPpanda$core$String$Cpanda$core$Object$Z$RP$$ARR_Int32_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*($LPpanda$core$String$Cpanda$core$Object$Z$RP$$ARR_Int32_$Rpanda$core$Object$Z_TYPE)((panda$core$String,panda$core$Object)* self, Int32);
void $LPpanda$core$String$Cpanda$core$Object$Z$RP$init_panda$core$String_panda$core$Object$Z((panda$core$String,panda$core$Object)* self, panda$core$String*, panda$core$Object*);
(panda$core$String,panda$core$Object)* new_$LPpanda$core$String$Cpanda$core$Object$Z$RP$init_panda$core$String_panda$core$Object$Z(panda$core$String*, panda$core$Object*);
panda$core$String* $LPpanda$core$String$Cpanda$core$Object$Z$RP$convert_$Rpanda$core$String((panda$core$String,panda$core$Object)* self);
Bit $LPpanda$core$String$Cpanda$core$Object$Z$RP$$EQ_panda$core$Object_$Rpanda$core$Bit((panda$core$String,panda$core$Object)* self, panda$core$Object*);
Int64 $LPpanda$core$String$Cpanda$core$Object$Z$RP$get_hash_$Rpanda$core$Int64((panda$core$String,panda$core$Object)* self);
panda$core$Object* $LPpanda$core$String$Cpanda$core$Object$Z$RP$$ARR_Int32_$Rpanda$core$Object$Z((panda$core$String,panda$core$Object)* self, Int32);
#endif
#endif
