// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutableArray$LTpanda$core$Int64$GT_H
#define panda$collections$ImmutableArray$LTpanda$core$Int64$GT_H
extern panda$core$Class panda$collections$ImmutableArray$LTpanda$core$Int64$GT_class;
#ifndef CLASS_panda$collections$ImmutableArray$LTpanda$core$Int64$GT
#define CLASS_panda$collections$ImmutableArray$LTpanda$core$Int64$GT
struct panda$collections$ImmutableArray$LTpanda$core$Int64$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LTpanda$core$Int64$GT* contents;
};

#define panda$collections$ImmutableArray$LTpanda$core$Int64$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$ImmutableArray$LTpanda$core$Int64$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self);
#define panda$collections$ImmutableArray$LTpanda$core$Int64$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$ImmutableArray$LTpanda$core$Int64$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self, panda$core$Object*);
#define panda$collections$ImmutableArray$LTpanda$core$Int64$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$ImmutableArray$LTpanda$core$Int64$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self);
#define panda$collections$ImmutableArray$LTpanda$core$Int64$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$ImmutableArray$LTpanda$core$Int64$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self);
#define panda$collections$ImmutableArray$LTpanda$core$Int64$GT$$ARR_Int64_$Rpanda$core$Int64_INDEX 17
typedef Int64(panda$collections$ImmutableArray$LTpanda$core$Int64$GT$$ARR_Int64_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self, Int64);
#define panda$collections$ImmutableArray$LTpanda$core$Int64$GT$convert_$Rpanda$collections$ImmutableArray$LTpanda$core$Int64$GT_INDEX 18
typedef panda$collections$ImmutableArray$LTpanda$core$Int64$GT*(panda$collections$ImmutableArray$LTpanda$core$Int64$GT$convert_$Rpanda$collections$ImmutableArray$LTpanda$core$Int64$GT_TYPE)(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self);
void panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self);
panda$collections$ImmutableArray$LTpanda$core$Int64$GT* new_panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init();
void panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Int64$GT(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self, panda$collections$PrimitiveArray$LTpanda$core$Int64$GT*);
panda$collections$ImmutableArray$LTpanda$core$Int64$GT* new_panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Int64$GT(panda$collections$PrimitiveArray$LTpanda$core$Int64$GT*);
void panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init_panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64$GT(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self, panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64$GT*);
panda$collections$ImmutableArray$LTpanda$core$Int64$GT* new_panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init_panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64$GT(panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64$GT*);
void panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init_panda$collections$CollectionView$LTpanda$core$Int64$GT(panda$collections$ImmutableArray$LTpanda$core$Int64$GT* self, panda$collections$CollectionView$LTpanda$core$Int64$GT*);
panda$collections$ImmutableArray$LTpanda$core$Int64$GT* new_panda$collections$ImmutableArray$LTpanda$core$Int64$GT$init_panda$collections$CollectionView$LTpanda$core$Int64$GT(panda$collections$CollectionView$LTpanda$core$Int64$GT*);
#endif
#endif
