// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_H
#define panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_H
extern panda$core$Class panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_class;
#ifndef CLASS_panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT
#define CLASS_panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT
struct panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT {
    panda$core$Class* cl;
    Int64 _length;
    panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$Z$GT* contents;
};

#define panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self);
#define panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$get_iterator_$Rpanda$collections$Iterator$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_INDEX 4
typedef panda$collections$Iterator$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$get_iterator_$Rpanda$collections$Iterator$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_TYPE)(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self);
#define panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$get_count_$Rpanda$core$Int64_INDEX 6
typedef Int64(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self);
#define panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$$ARR_panda$core$Immutable_$Rpanda$core$Immutable$Z_INDEX 8
typedef panda$core$Immutable*(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$$ARR_panda$core$Immutable_$Rpanda$core$Immutable$Z_TYPE)(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$contains_panda$core$Immutable_$Rpanda$core$Bit_INDEX 9
typedef Bit(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$contains_panda$core$Immutable_$Rpanda$core$Bit_TYPE)(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Object$Z$GT_INDEX 10
typedef panda$collections$Iterator$LTpanda$core$Object$Z$GT*(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Object$Z$GT_TYPE)(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self);
void panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self);
panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* new_panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init();
void panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$MapView$LTpanda$core$Immutable$Cpanda$core$Immutable$GT(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$collections$MapView$LTpanda$core$Immutable$Cpanda$core$Immutable$GT*);
panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* new_panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$MapView$LTpanda$core$Immutable$Cpanda$core$Immutable$GT(panda$collections$MapView$LTpanda$core$Immutable$Cpanda$core$Immutable$GT*);
void panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$ListView$LTpanda$core$Immutable$GT_panda$collections$ListView$LTpanda$core$Immutable$GT(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$collections$ListView$LTpanda$core$Immutable$GT*, panda$collections$ListView$LTpanda$core$Immutable$GT*);
panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* new_panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$ListView$LTpanda$core$Immutable$GT_panda$collections$ListView$LTpanda$core$Immutable$GT(panda$collections$ListView$LTpanda$core$Immutable$GT*, panda$collections$ListView$LTpanda$core$Immutable$GT*);
void panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$ListView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$collections$ListView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* new_panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$ListView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$ListView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
void panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT*, panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT*);
panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* new_panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT(panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT*, panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT*);
panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$copy_panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$Z_$Rpanda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$Z(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT*);
Int64 panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$indexFor_panda$core$Immutable_$Rpanda$core$Int64(panda$collections$ImmutableHashMap$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$core$Immutable*);
#endif
#endif
