// This file was automatically generated by the Panda compiler
#ifndef panda$core$Number_H
#define panda$core$Number_H
extern panda$core$Class panda$core$Number_class;
#ifndef CLASS_panda$core$Number
#define CLASS_panda$core$Number
struct panda$core$Number {
    panda$core$Class* cl;
};

#define panda$core$Number$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$core$Number$get_hash_$Rpanda$core$Int64_TYPE)(panda$core$Number* self);
#define panda$core$Number$format_panda$core$String_$Rpanda$core$String_INDEX 4
typedef panda$core$String*(panda$core$Number$format_panda$core$String_$Rpanda$core$String_TYPE)(panda$core$Number* self, panda$core$String*);
#define panda$core$Number$english_$Rpanda$core$String_INDEX 5
typedef panda$core$String*(panda$core$Number$english_$Rpanda$core$String_TYPE)(panda$core$Number* self);
#define panda$core$Number$convertToString_panda$core$CharWrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$core$String_$Rpanda$core$String_INDEX 6
typedef panda$core$String*(panda$core$Number$convertToString_panda$core$CharWrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$core$String_$Rpanda$core$String_TYPE)(panda$core$Number* self, panda$core$CharWrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$core$String*);
#define panda$core$Number$convert_$Rpanda$core$Int8_INDEX 7
typedef Int8(panda$core$Number$convert_$Rpanda$core$Int8_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$Int16_INDEX 8
typedef Int16(panda$core$Number$convert_$Rpanda$core$Int16_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$Int32_INDEX 9
typedef Int32(panda$core$Number$convert_$Rpanda$core$Int32_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$Int64_INDEX 10
typedef Int64(panda$core$Number$convert_$Rpanda$core$Int64_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$UInt8_INDEX 11
typedef UInt8(panda$core$Number$convert_$Rpanda$core$UInt8_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$UInt16_INDEX 12
typedef UInt16(panda$core$Number$convert_$Rpanda$core$UInt16_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$UInt32_INDEX 13
typedef UInt32(panda$core$Number$convert_$Rpanda$core$UInt32_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$UInt64_INDEX 14
typedef UInt64(panda$core$Number$convert_$Rpanda$core$UInt64_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$Real32_INDEX 15
typedef Real32(panda$core$Number$convert_$Rpanda$core$Real32_TYPE)(panda$core$Number* self);
#define panda$core$Number$convert_$Rpanda$core$Real64_INDEX 16
typedef Real64(panda$core$Number$convert_$Rpanda$core$Real64_TYPE)(panda$core$Number* self);
#define panda$core$Number$roman_$Rpanda$core$String_INDEX 17
typedef panda$core$String*(panda$core$Number$roman_$Rpanda$core$String_TYPE)(panda$core$Number* self);
panda$core$String* panda$core$Number$convertToString_class_Int64_panda$core$CharWrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$core$String_$Rpanda$core$String(Int64, panda$core$CharWrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$core$String*);
panda$core$String* panda$core$Number$convertToString_class_UInt64_panda$core$CharWrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$core$String_$Rpanda$core$String(UInt64, panda$core$CharWrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$core$String*);
panda$core$String* panda$core$Number$convertToString_class_Real64_panda$core$CharWrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$core$String_$Rpanda$core$String(Real64, panda$core$CharWrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$core$String*);
void panda$core$Number$roundUp_class_panda$core$MutableString_Int64(panda$core$MutableString*, Int64);
panda$core$String* panda$core$Number$uppercaseFirst_class_panda$core$String_$Rpanda$core$String(panda$core$String*);
void panda$core$Number$init(panda$core$Number* self);
panda$core$Number* new_panda$core$Number$init();
void panda$core$Number$$classInit_class();
extern panda$core$RegularExpression* class_panda$core$Number$FORMAT_PATTERN;
extern Bit class_panda$core$Number$$classInited;
#endif
#endif
