// This file was automatically generated by the Panda compiler
#ifndef panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$Action$GT_H
#define panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$Action$GT_H
extern panda$core$Class panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$Action$GT_class;
#ifndef CLASS_panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$Action$GT
#define CLASS_panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$Action$GT
struct panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$Action$GT {
    panda$core$Class* cl;
    Int64 length;
    panda$parser$GLRParser$Action** contents;
};

#endif
#endif
