// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Enumerator$LTpanda$core$Immutable$GT_H
#define panda$collections$Enumerator$LTpanda$core$Immutable$GT_H
extern panda$core$Class panda$collections$Enumerator$LTpanda$core$Immutable$GT_class;
#ifndef CLASS_panda$collections$Enumerator$LTpanda$core$Immutable$GT
#define CLASS_panda$collections$Enumerator$LTpanda$core$Immutable$GT
struct panda$collections$Enumerator$LTpanda$core$Immutable$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$core$Immutable$GT* base;
    Int64 index;
};

#define panda$collections$Enumerator$LTpanda$core$Immutable$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Enumerator$LTpanda$core$Immutable$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Enumerator$LTpanda$core$Immutable$GT* self);
#define panda$collections$Enumerator$LTpanda$core$Immutable$GT$next_$R$LPpanda$core$Int64$Cpanda$core$Immutable$RP_INDEX 8
typedef $LPInt64$Cpanda$core$Immutable$RP*(panda$collections$Enumerator$LTpanda$core$Immutable$GT$next_$R$LPpanda$core$Int64$Cpanda$core$Immutable$RP_TYPE)(panda$collections$Enumerator$LTpanda$core$Immutable$GT* self);
void panda$collections$Enumerator$LTpanda$core$Immutable$GT$init_panda$collections$CollectionView$LTpanda$core$Immutable$GT(panda$collections$Enumerator$LTpanda$core$Immutable$GT* self, panda$collections$CollectionView$LTpanda$core$Immutable$GT*);
panda$collections$Enumerator$LTpanda$core$Immutable$GT* new_panda$collections$Enumerator$LTpanda$core$Immutable$GT$init_panda$collections$CollectionView$LTpanda$core$Immutable$GT(panda$collections$CollectionView$LTpanda$core$Immutable$GT*);
#endif
#endif
