// This file was automatically generated by the Panda compiler
#ifndef panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_H
#define panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_H
extern panda$core$Class panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_class;
#ifndef CLASS_panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT
#define CLASS_panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT
struct panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT {
    panda$core$Class* cl;
    Int64 $length;
    $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP** contents;
};

#define panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$length_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$length_$Rpanda$core$Int64_TYPE)(panda$collections$PrimitiveArray$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self);
#endif
#endif
