// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure10_H
#define panda$util$JSONParser$closure10_H
extern panda$core$Class panda$util$JSONParser$closure10_class;
#ifndef CLASS_panda$util$JSONParser$closure10
#define CLASS_panda$util$JSONParser$closure10
struct panda$util$JSONParser$closure10 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure10$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure10$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure10* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure10$init(panda$util$JSONParser$closure10* self);
panda$util$JSONParser$closure10* new_panda$util$JSONParser$closure10$init();
#endif
#endif
