// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT_H
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT_H
extern panda$core$Class panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT_class;
#ifndef CLASS_panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT
#define CLASS_panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT
struct panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT* self);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$C$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_INDEX 5
typedef $LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$C$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT* self, void**);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$C$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP_$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_INDEX 6
typedef $LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$C$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP_$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT* self, void**, $LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP*);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$filter_$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT_INDEX 7
typedef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$filter_$LP$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT* self, void**);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$next_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_INDEX 8
typedef $LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT$next_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP$GT* self);
#endif
#endif
