// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT_H
#define panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT_H
extern panda$core$Class panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT_class;
#ifndef CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT
#define CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT
struct panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT {
    panda$core$Class* cl;
    Int64 $length;
    panda$parser$GLRParser$ParseError** contents;
};

#define panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT$length_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT$length_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutablePrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT* self);
#endif
#endif
