// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionView$LTpanda$core$Object$GT_H
#define panda$collections$CollectionView$LTpanda$core$Object$GT_H
extern panda$core$Class panda$collections$CollectionView$LTpanda$core$Object$GT_class;
#ifndef CLASS_panda$collections$CollectionView$LTpanda$core$Object$GT
#define CLASS_panda$collections$CollectionView$LTpanda$core$Object$GT
struct panda$collections$CollectionView$LTpanda$core$Object$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionView$LTpanda$core$Object$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$CollectionView$LTpanda$core$Object$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self);
#define panda$collections$CollectionView$LTpanda$core$Object$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$Object$RP$GT_INDEX 6
typedef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$Object$RP$GT*(panda$collections$CollectionView$LTpanda$core$Object$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$Object$RP$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self);
#define panda$collections$CollectionView$LTpanda$core$Object$GT$apply_$LPpanda$core$Object$RP$EQ$AM$GT$LP$RP_INDEX 7
typedef void(panda$collections$CollectionView$LTpanda$core$Object$GT$apply_$LPpanda$core$Object$RP$EQ$AM$GT$LP$RP_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$Object$GT$fold_$LPpanda$core$Object$Cpanda$core$Object$RP$EQ$GT$LPpanda$core$Object$RP_$Rpanda$core$Object_INDEX 8
typedef panda$core$Object*(panda$collections$CollectionView$LTpanda$core$Object$GT$fold_$LPpanda$core$Object$Cpanda$core$Object$RP$EQ$GT$LPpanda$core$Object$RP_$Rpanda$core$Object_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$Object$GT$fold_$LPpanda$core$Object$Cpanda$core$Object$RP$EQ$GT$LPpanda$core$Object$RP_panda$core$Object_$Rpanda$core$Object_INDEX 9
typedef panda$core$Object*(panda$collections$CollectionView$LTpanda$core$Object$GT$fold_$LPpanda$core$Object$Cpanda$core$Object$RP$EQ$GT$LPpanda$core$Object$RP_panda$core$Object_$Rpanda$core$Object_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self, void**, panda$core$Object*);
#define panda$collections$CollectionView$LTpanda$core$Object$GT$filter_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$Object$GT_INDEX 10
typedef panda$collections$CollectionView$LTpanda$core$Object$GT*(panda$collections$CollectionView$LTpanda$core$Object$GT$filter_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$Object$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$Object$GT$contains_panda$core$Object_$Rpanda$core$Bit_INDEX 11
typedef Bit(panda$collections$CollectionView$LTpanda$core$Object$GT$contains_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self, panda$core$Object*);
#define panda$collections$CollectionView$LTpanda$core$Object$GT$convert_$Rpanda$collections$Array$LTpanda$core$Object$GT_INDEX 12
typedef panda$collections$Array$LTpanda$core$Object$GT*(panda$collections$CollectionView$LTpanda$core$Object$GT$convert_$Rpanda$collections$Array$LTpanda$core$Object$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$Object$GT* self);
#endif
#endif
