// This file was automatically generated by the Panda compiler
#ifndef panda$core$Primitive_H
#define panda$core$Primitive_H
extern panda$core$Class panda$core$Primitive_class;
#ifndef CLASS_panda$core$Primitive
#define CLASS_panda$core$Primitive
struct panda$core$Primitive {
    panda$core$Class* cl;
};

void panda$core$Primitive$init(panda$core$Primitive* self);
panda$core$Primitive* new_panda$core$Primitive$init();
#endif
#endif
