// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT_H
#define panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT_H
extern panda$core$Class panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT_class;
#ifndef CLASS_panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT
#define CLASS_panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT
struct panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT {
    panda$core$Class* cl;
    panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT* list;
    Int64 index;
};

#define panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT* self);
#define panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT$next_$Rpanda$parser$GLRParser$Action_INDEX 8
typedef panda$parser$GLRParser$Action*(panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT$next_$Rpanda$parser$GLRParser$Action_TYPE)(panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT* self);
void panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT$init_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT(panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT* self, panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT*);
panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT* new_panda$collections$ListIterator$LTpanda$parser$GLRParser$Action$GT$init_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT(panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT*);
#endif
#endif
