// This file was automatically generated by the Panda compiler
#ifndef panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT_H
#define panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT_H
extern panda$core$Class panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT_class;
#ifndef CLASS_panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT
#define CLASS_panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT
struct panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$parser$GLRParser$State$GT* base;
    void** filter;
    panda$parser$GLRParser$State* nextValue;
};

#define panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT* self);
#define panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$next_$Rpanda$parser$GLRParser$State_INDEX 8
typedef panda$parser$GLRParser$State*(panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$next_$Rpanda$parser$GLRParser$State_TYPE)(panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT* self);
#define panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$getNext_INDEX 9
typedef void(panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$getNext_TYPE)(panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT* self);
void panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$init_panda$collections$Iterator$LTpanda$parser$GLRParser$State$GT_$LPpanda$parser$GLRParser$State$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT* self, panda$collections$Iterator$LTpanda$parser$GLRParser$State$GT*, void**);
panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT* new_panda$collections$FilterIterator$LTpanda$parser$GLRParser$State$GT$init_panda$collections$Iterator$LTpanda$parser$GLRParser$State$GT_$LPpanda$parser$GLRParser$State$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$parser$GLRParser$State$GT*, void**);
#endif
#endif
