// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionWriter$LTpanda$core$UInt16$GT_H
#define panda$collections$CollectionWriter$LTpanda$core$UInt16$GT_H
extern panda$core$Class panda$collections$CollectionWriter$LTpanda$core$UInt16$GT_class;
#ifndef CLASS_panda$collections$CollectionWriter$LTpanda$core$UInt16$GT
#define CLASS_panda$collections$CollectionWriter$LTpanda$core$UInt16$GT
struct panda$collections$CollectionWriter$LTpanda$core$UInt16$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT* self);
#define panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$addAll_panda$collections$CollectionView$LTpanda$core$UInt16$GT_INDEX 5
typedef void(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$addAll_panda$collections$CollectionView$LTpanda$core$UInt16$GT_TYPE)(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT* self, panda$collections$CollectionView$LTpanda$core$UInt16$GT*);
#define panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$add_UInt16_INDEX 6
typedef void(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$add_UInt16_TYPE)(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT* self, UInt16);
#define panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$add_panda$collections$ListView$LTpanda$core$UInt16$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$add_panda$collections$ListView$LTpanda$core$UInt16$GT_Int64_Int64_TYPE)(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT* self, panda$collections$ListView$LTpanda$core$UInt16$GT*, Int64, Int64);
#define panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$remove_UInt16_INDEX 8
typedef void(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$remove_UInt16_TYPE)(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT* self, UInt16);
#define panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$clear_INDEX 9
typedef void(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT$clear_TYPE)(panda$collections$CollectionWriter$LTpanda$core$UInt16$GT* self);
#endif
#endif
