// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64Wrapper$Z$GT_H
#define panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64Wrapper$Z$GT_H
extern panda$core$Class panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64Wrapper$Z$GT_class;
#ifndef CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64Wrapper$Z$GT
#define CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64Wrapper$Z$GT
struct panda$collections$ImmutablePrimitiveArray$LTpanda$core$Int64Wrapper$Z$GT {
    panda$core$Class* cl;
    Int64 length;
    panda$core$Int64Wrapper** contents;
};

#endif
#endif
