// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure103_H
#define panda$util$JSONParser$closure103_H
extern panda$core$Class panda$util$JSONParser$closure103_class;
#ifndef CLASS_panda$util$JSONParser$closure103
#define CLASS_panda$util$JSONParser$closure103
struct panda$util$JSONParser$closure103 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure103$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure103$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure103* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure103$init(panda$util$JSONParser$closure103* self);
panda$util$JSONParser$closure103* new_panda$util$JSONParser$closure103$init();
#endif
#endif
