// This file was automatically generated by the Panda compiler
#ifndef panda$collections$FilterIterator$LTpanda$core$String$Z$GT_H
#define panda$collections$FilterIterator$LTpanda$core$String$Z$GT_H
extern panda$core$Class panda$collections$FilterIterator$LTpanda$core$String$Z$GT_class;
#ifndef CLASS_panda$collections$FilterIterator$LTpanda$core$String$Z$GT
#define CLASS_panda$collections$FilterIterator$LTpanda$core$String$Z$GT
struct panda$collections$FilterIterator$LTpanda$core$String$Z$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$core$String$Z$GT* base;
    void** filter;
    panda$core$String* nextValue;
};

#define panda$collections$FilterIterator$LTpanda$core$String$Z$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$FilterIterator$LTpanda$core$String$Z$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$FilterIterator$LTpanda$core$String$Z$GT* self);
#define panda$collections$FilterIterator$LTpanda$core$String$Z$GT$next_$Rpanda$core$String$Z_INDEX 8
typedef panda$core$String*(panda$collections$FilterIterator$LTpanda$core$String$Z$GT$next_$Rpanda$core$String$Z_TYPE)(panda$collections$FilterIterator$LTpanda$core$String$Z$GT* self);
#define panda$collections$FilterIterator$LTpanda$core$String$Z$GT$getNext_INDEX 9
typedef void(panda$collections$FilterIterator$LTpanda$core$String$Z$GT$getNext_TYPE)(panda$collections$FilterIterator$LTpanda$core$String$Z$GT* self);
void panda$collections$FilterIterator$LTpanda$core$String$Z$GT$init_panda$collections$Iterator$LTpanda$core$String$Z$GT_$LPpanda$core$String$Z$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$FilterIterator$LTpanda$core$String$Z$GT* self, panda$collections$Iterator$LTpanda$core$String$Z$GT*, void**);
panda$collections$FilterIterator$LTpanda$core$String$Z$GT* new_panda$collections$FilterIterator$LTpanda$core$String$Z$GT$init_panda$collections$Iterator$LTpanda$core$String$Z$GT_$LPpanda$core$String$Z$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$core$String$Z$GT*, void**);
#endif
#endif
