// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure86_H
#define panda$util$JSONParser$closure86_H
extern panda$core$Class panda$util$JSONParser$closure86_class;
#ifndef CLASS_panda$util$JSONParser$closure86
#define CLASS_panda$util$JSONParser$closure86
struct panda$util$JSONParser$closure86 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure86$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure86$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure86* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure86$init(panda$util$JSONParser$closure86* self);
panda$util$JSONParser$closure86* new_panda$util$JSONParser$closure86$init();
#endif
#endif
