// This file was automatically generated by the Panda compiler
#ifndef panda$collections$FilterIterator_H
#define panda$collections$FilterIterator_H
extern panda$core$Class panda$collections$FilterIterator_class;
#ifndef CLASS_panda$collections$FilterIterator
#define CLASS_panda$collections$FilterIterator
struct panda$collections$FilterIterator {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$core$Object$Z$GT* base;
    void** filter;
    panda$core$Object* nextValue;
};

#define panda$collections$FilterIterator$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$FilterIterator$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$FilterIterator* self);
#define panda$collections$FilterIterator$next_$Rpanda$core$Object$Z_INDEX 8
typedef panda$core$Object*(panda$collections$FilterIterator$next_$Rpanda$core$Object$Z_TYPE)(panda$collections$FilterIterator* self);
#define panda$collections$FilterIterator$getNext_INDEX 9
typedef void(panda$collections$FilterIterator$getNext_TYPE)(panda$collections$FilterIterator* self);
void panda$collections$FilterIterator$init_panda$collections$Iterator$LTpanda$core$Object$Z$GT_$LPpanda$core$Object$Z$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$FilterIterator* self, panda$collections$Iterator$LTpanda$core$Object$Z$GT*, void**);
panda$collections$FilterIterator* new_panda$collections$FilterIterator$init_panda$collections$Iterator$LTpanda$core$Object$Z$GT_$LPpanda$core$Object$Z$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$core$Object$Z$GT*, void**);
#endif
#endif
