// This file was automatically generated by the Panda compiler
#ifndef panda$core$UnsignedInteger_H
#define panda$core$UnsignedInteger_H
extern panda$core$Class panda$core$UnsignedInteger_class;
#ifndef CLASS_panda$core$UnsignedInteger
#define CLASS_panda$core$UnsignedInteger
struct panda$core$UnsignedInteger {
    panda$core$Class* cl;
};

#define panda$core$UnsignedInteger$english_$Rpanda$core$String_INDEX 5
typedef panda$core$String*(panda$core$UnsignedInteger$english_$Rpanda$core$String_TYPE)(panda$core$UnsignedInteger* self);
#define panda$core$UnsignedInteger$roman_$Rpanda$core$String_INDEX 17
typedef panda$core$String*(panda$core$UnsignedInteger$roman_$Rpanda$core$String_TYPE)(panda$core$UnsignedInteger* self);
void panda$core$UnsignedInteger$init(panda$core$UnsignedInteger* self);
panda$core$UnsignedInteger* new_panda$core$UnsignedInteger$init();
#endif
#endif
