// This file was automatically generated by the Panda compiler
#ifndef panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT_H
#define panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT_H
extern panda$core$Class panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT_class;
#ifndef CLASS_panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT
#define CLASS_panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT
struct panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT* base;
    void** filter;
    $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP* nextValue;
};

#define panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT* self);
#define panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$next_$R$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP_INDEX 8
typedef $LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP*(panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$next_$R$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP_TYPE)(panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT* self);
#define panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$getNext_INDEX 9
typedef void(panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$getNext_TYPE)(panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT* self);
void panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$init_panda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT_$LP$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT* self, panda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT*, void**);
panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT* new_panda$collections$FilterIterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT$init_panda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT_$LP$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$RP$GT*, void**);
#endif
#endif
