// This file was automatically generated by the Panda compiler
#ifndef panda$io$FileInputStream_H
#define panda$io$FileInputStream_H
extern panda$core$Class panda$io$FileInputStream_class;
#ifndef CLASS_panda$io$FileInputStream
#define CLASS_panda$io$FileInputStream
struct panda$io$FileInputStream {
    panda$core$Class* cl;
    Bit closed;
    void* nativeFile;
};

#define panda$io$FileInputStream$finalize_INDEX 0
typedef void(panda$io$FileInputStream$finalize_TYPE)(panda$io$FileInputStream* self);
#define panda$io$FileInputStream$close_INDEX 4
typedef void(panda$io$FileInputStream$close_TYPE)(panda$io$FileInputStream* self);
#define panda$io$FileInputStream$read_$Rpanda$core$UInt8Wrapper$Z_INDEX 9
typedef panda$core$UInt8Wrapper*(panda$io$FileInputStream$read_$Rpanda$core$UInt8Wrapper$Z_TYPE)(panda$io$FileInputStream* self);
#define panda$io$FileInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 10
typedef panda$core$Int64Wrapper*(panda$io$FileInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$io$FileInputStream* self, panda$collections$ListWriter$LTpanda$core$UInt8$GT*, Int64);
void panda$io$FileInputStream$init_panda$core$$NativePointer(panda$io$FileInputStream* self, void*);
panda$io$FileInputStream* new_panda$io$FileInputStream$init_panda$core$$NativePointer(void*);
void panda$io$FileInputStream$init_panda$io$File(panda$io$FileInputStream* self, panda$io$File*);
panda$io$FileInputStream* new_panda$io$FileInputStream$init_panda$io$File(panda$io$File*);
panda$core$Int64Wrapper* panda$io$FileInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z(panda$io$FileInputStream* self, panda$collections$ListWriter$LTpanda$core$UInt8$GT*, Int64);
Int16 panda$io$FileInputStream$read_class_panda$core$$NativePointer_$Rpanda$core$Int16(void*);
Int64 panda$io$FileInputStream$close_class_panda$core$$NativePointer_$Rpanda$core$Int64(void*);
void* panda$io$FileInputStream$open_class_panda$core$String_Bit_Bit_$Rpanda$core$$NativePointer(panda$core$String*, Bit, Bit);
#endif
#endif
