// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Array$LTpanda$core$Immutable$GT_H
#define panda$collections$Array$LTpanda$core$Immutable$GT_H
extern panda$core$Class panda$collections$Array$LTpanda$core$Immutable$GT_class;
#ifndef CLASS_panda$collections$Array$LTpanda$core$Immutable$GT
#define CLASS_panda$collections$Array$LTpanda$core$Immutable$GT
struct panda$collections$Array$LTpanda$core$Immutable$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT* contents;
    Int64 _count;
};

#define panda$collections$Array$LTpanda$core$Immutable$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$Array$LTpanda$core$Immutable$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self);
#define panda$collections$Array$LTpanda$core$Immutable$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$Array$LTpanda$core$Immutable$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$core$Object*);
#define panda$collections$Array$LTpanda$core$Immutable$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$Array$LTpanda$core$Immutable$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self);
#define panda$collections$Array$LTpanda$core$Immutable$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$Array$LTpanda$core$Immutable$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self);
#define panda$collections$Array$LTpanda$core$Immutable$GT$addAll_panda$collections$CollectionView$LTpanda$core$Immutable$GT_INDEX 5
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$addAll_panda$collections$CollectionView$LTpanda$core$Immutable$GT_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$collections$CollectionView$LTpanda$core$Immutable$GT*);
#define panda$collections$Array$LTpanda$core$Immutable$GT$add_panda$core$Immutable_INDEX 6
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$add_panda$core$Immutable_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$Array$LTpanda$core$Immutable$GT$add_panda$collections$ListView$LTpanda$core$Immutable$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$add_panda$collections$ListView$LTpanda$core$Immutable$GT_Int64_Int64_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$collections$ListView$LTpanda$core$Immutable$GT*, Int64, Int64);
#define panda$collections$Array$LTpanda$core$Immutable$GT$remove_panda$core$Immutable_INDEX 8
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$remove_panda$core$Immutable_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$Array$LTpanda$core$Immutable$GT$clear_INDEX 9
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$clear_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self);
#define panda$collections$Array$LTpanda$core$Immutable$GT$$ARREQ_Int64_panda$core$Immutable_INDEX 10
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$$ARREQ_Int64_panda$core$Immutable_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64, panda$core$Immutable*);
#define panda$collections$Array$LTpanda$core$Immutable$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$removeIndex_Int64_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64);
#define panda$collections$Array$LTpanda$core$Immutable$GT$contains_panda$core$Immutable_$Rpanda$core$Bit_INDEX 19
typedef Bit(panda$collections$Array$LTpanda$core$Immutable$GT$contains_panda$core$Immutable_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$Array$LTpanda$core$Immutable$GT$$ARR_Int64_$Rpanda$core$Immutable_INDEX 25
typedef panda$core$Immutable*(panda$collections$Array$LTpanda$core$Immutable$GT$$ARR_Int64_$Rpanda$core$Immutable_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64);
#define panda$collections$Array$LTpanda$core$Immutable$GT$addAll_panda$collections$Array$LTpanda$core$Immutable$GT_INDEX 39
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$addAll_panda$collections$Array$LTpanda$core$Immutable$GT_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$collections$Array$LTpanda$core$Immutable$GT*);
#define panda$collections$Array$LTpanda$core$Immutable$GT$sorted_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$core$Immutable$GT_INDEX 40
typedef panda$collections$Array$LTpanda$core$Immutable$GT*(panda$collections$Array$LTpanda$core$Immutable$GT$sorted_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$core$Immutable$GT_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, void**);
#define panda$collections$Array$LTpanda$core$Immutable$GT$add_panda$collections$Array$LTpanda$core$Immutable$GT_Int64_Int64_INDEX 41
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$add_panda$collections$Array$LTpanda$core$Immutable$GT_Int64_Int64_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$collections$Array$LTpanda$core$Immutable$GT*, Int64, Int64);
#define panda$collections$Array$LTpanda$core$Immutable$GT$sort_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 42
typedef void(panda$collections$Array$LTpanda$core$Immutable$GT$sort_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$Array$LTpanda$core$Immutable$GT* self, void**);
void panda$collections$Array$LTpanda$core$Immutable$GT$init(panda$collections$Array$LTpanda$core$Immutable$GT* self);
panda$collections$Array$LTpanda$core$Immutable$GT* new_panda$collections$Array$LTpanda$core$Immutable$GT$init();
void panda$collections$Array$LTpanda$core$Immutable$GT$init_Int64(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64);
panda$collections$Array$LTpanda$core$Immutable$GT* new_panda$collections$Array$LTpanda$core$Immutable$GT$init_Int64(Int64);
void panda$collections$Array$LTpanda$core$Immutable$GT$init_Int64_panda$core$Immutable(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64, panda$core$Immutable*);
panda$collections$Array$LTpanda$core$Immutable$GT* new_panda$collections$Array$LTpanda$core$Immutable$GT$init_Int64_panda$core$Immutable(Int64, panda$core$Immutable*);
void panda$collections$Array$LTpanda$core$Immutable$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT*);
panda$collections$Array$LTpanda$core$Immutable$GT* new_panda$collections$Array$LTpanda$core$Immutable$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT(panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT*);
void panda$collections$Array$LTpanda$core$Immutable$GT$init_panda$collections$CollectionView$LTpanda$core$Immutable$GT(panda$collections$Array$LTpanda$core$Immutable$GT* self, panda$collections$CollectionView$LTpanda$core$Immutable$GT*);
panda$collections$Array$LTpanda$core$Immutable$GT* new_panda$collections$Array$LTpanda$core$Immutable$GT$init_panda$collections$CollectionView$LTpanda$core$Immutable$GT(panda$collections$CollectionView$LTpanda$core$Immutable$GT*);
void panda$collections$Array$LTpanda$core$Immutable$GT$swap_Int64_Int64(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64, Int64);
void panda$collections$Array$LTpanda$core$Immutable$GT$sort_Int64_Int64_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64, Int64, void**);
void panda$collections$Array$LTpanda$core$Immutable$GT$ensureCapacity_Int64(panda$collections$Array$LTpanda$core$Immutable$GT* self, Int64);
extern Int64 class_panda$collections$Array$DEFAULT_COUNT;
extern Bit class_panda$collections$Array$$classInited;
#endif
#endif
