// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT_H
#define panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT_H
extern panda$core$Class panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT_class;
#ifndef CLASS_panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT
#define CLASS_panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT
struct panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$parser$GLRParser$State$GT* base;
    Int64 index;
};

#define panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT* self);
#define panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT$next_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_INDEX 8
typedef $LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP*(panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT$next_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$State$RP_TYPE)(panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT* self);
void panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT$init_panda$collections$CollectionView$LTpanda$parser$GLRParser$State$GT(panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT* self, panda$collections$CollectionView$LTpanda$parser$GLRParser$State$GT*);
panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT* new_panda$collections$Enumerator$LTpanda$parser$GLRParser$State$GT$init_panda$collections$CollectionView$LTpanda$parser$GLRParser$State$GT(panda$collections$CollectionView$LTpanda$parser$GLRParser$State$GT*);
#endif
#endif
