// This file was automatically generated by the Panda compiler
#ifndef panda$core$Panda$closure221_H
#define panda$core$Panda$closure221_H
extern panda$core$Class panda$core$Panda$closure221_class;
#ifndef CLASS_panda$core$Panda$closure221
#define CLASS_panda$core$Panda$closure221
struct panda$core$Panda$closure221 {
    panda$core$Class* cl;
    Int64 count;
    void** f;
};

#define panda$core$Panda$closure221$closure_Int64_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$core$Panda$closure221$closure_Int64_$Rpanda$core$Int64_TYPE)(panda$core$Panda$closure221* self, Int64);
void panda$core$Panda$closure221$init_Int64_$LPpanda$core$Int64$RP$EQ$GT$LPpanda$core$Int64$RP(panda$core$Panda$closure221* self, Int64, void**);
panda$core$Panda$closure221* new_panda$core$Panda$closure221$init_Int64_$LPpanda$core$Int64$RP$EQ$GT$LPpanda$core$Int64$RP(Int64, void**);
#endif
#endif
