// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListWriter$LTpanda$core$Object$GT_H
#define panda$collections$ListWriter$LTpanda$core$Object$GT_H
extern panda$core$Class panda$collections$ListWriter$LTpanda$core$Object$GT_class;
#ifndef CLASS_panda$collections$ListWriter$LTpanda$core$Object$GT
#define CLASS_panda$collections$ListWriter$LTpanda$core$Object$GT
struct panda$collections$ListWriter$LTpanda$core$Object$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListWriter$LTpanda$core$Object$GT$$ARREQ_Int64_panda$core$Object_INDEX 10
typedef void(panda$collections$ListWriter$LTpanda$core$Object$GT$$ARREQ_Int64_panda$core$Object_TYPE)(panda$collections$ListWriter$LTpanda$core$Object$GT* self, Int64, panda$core$Object*);
#define panda$collections$ListWriter$LTpanda$core$Object$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$ListWriter$LTpanda$core$Object$GT$removeIndex_Int64_TYPE)(panda$collections$ListWriter$LTpanda$core$Object$GT* self, Int64);
#define panda$collections$ListWriter$LTpanda$core$Object$GT$insert_Int64_panda$core$Object_INDEX 12
typedef void(panda$collections$ListWriter$LTpanda$core$Object$GT$insert_Int64_panda$core$Object_TYPE)(panda$collections$ListWriter$LTpanda$core$Object$GT* self, Int64, panda$core$Object*);
#endif
#endif
