// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT_H
#define panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT_H
extern panda$core$Class panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT_class;
#ifndef CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT
#define CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT
struct panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT {
    panda$core$Class* cl;
    Int64 length;
    panda$core$String** contents;
};

#endif
#endif
