// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT_H
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT_H
extern panda$core$Class panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT_class;
#ifndef CLASS_panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT
#define CLASS_panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT
struct panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self);
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$GT_INDEX 6
typedef panda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$GT*(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$C$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$GT_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self);
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$apply_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$AM$GT$LP$RP_INDEX 7
typedef void(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$apply_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$AM$GT$LP$RP_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self, void**);
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$C$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP_$R$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_INDEX 8
typedef $LPpanda$core$Int64$Cpanda$core$Object$Z$RP*(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$C$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP_$R$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self, void**);
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$C$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP_$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_$R$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_INDEX 9
typedef $LPpanda$core$Int64$Cpanda$core$Object$Z$RP*(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$C$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP_$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_$R$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self, void**, $LPpanda$core$Int64$Cpanda$core$Object$Z$RP*);
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$filter_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT_INDEX 10
typedef panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT*(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$filter_$LP$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self, void**);
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$contains_$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_$Rpanda$core$Bit_INDEX 11
typedef Bit(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$contains_$LPpanda$core$Int64$Cpanda$core$Object$Z$RP_$Rpanda$core$Bit_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self, $LPpanda$core$Int64$Cpanda$core$Object$Z$RP*);
#define panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$convert_$Rpanda$collections$Array$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT_INDEX 12
typedef panda$collections$Array$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT*(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT$convert_$Rpanda$collections$Array$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT_TYPE)(panda$collections$CollectionView$LT$LPpanda$core$Int64$Cpanda$core$Object$Z$RP$GT* self);
#endif
#endif
