// This file was automatically generated by the Panda compiler
#ifndef panda$io$FileOutputStream_H
#define panda$io$FileOutputStream_H
extern panda$core$Class panda$io$FileOutputStream_class;
#ifndef CLASS_panda$io$FileOutputStream
#define CLASS_panda$io$FileOutputStream
struct panda$io$FileOutputStream {
    panda$core$Class* cl;
    Bit closed;
    void* nativeFile;
};

#define panda$io$FileOutputStream$finalize_INDEX 0
typedef void(panda$io$FileOutputStream$finalize_TYPE)(panda$io$FileOutputStream* self);
#define panda$io$FileOutputStream$flush_INDEX 4
typedef void(panda$io$FileOutputStream$flush_TYPE)(panda$io$FileOutputStream* self);
#define panda$io$FileOutputStream$close_INDEX 5
typedef void(panda$io$FileOutputStream$close_TYPE)(panda$io$FileOutputStream* self);
#define panda$io$FileOutputStream$write_UInt8_INDEX 6
typedef void(panda$io$FileOutputStream$write_UInt8_TYPE)(panda$io$FileOutputStream* self, UInt8);
#define panda$io$FileOutputStream$write_panda$collections$ListView$LTpanda$core$UInt8$GT_Int64_Int64_INDEX 8
typedef void(panda$io$FileOutputStream$write_panda$collections$ListView$LTpanda$core$UInt8$GT_Int64_Int64_TYPE)(panda$io$FileOutputStream* self, panda$collections$ListView$LTpanda$core$UInt8$GT*, Int64, Int64);
void panda$io$FileOutputStream$init_panda$core$$NativePointer(panda$io$FileOutputStream* self, void*);
panda$io$FileOutputStream* new_panda$io$FileOutputStream$init_panda$core$$NativePointer(void*);
void panda$io$FileOutputStream$init_panda$io$File(panda$io$FileOutputStream* self, panda$io$File*);
panda$io$FileOutputStream* new_panda$io$FileOutputStream$init_panda$io$File(panda$io$File*);
void panda$io$FileOutputStream$flush(panda$io$FileOutputStream* self);
Int64 panda$io$FileOutputStream$close_class_panda$core$$NativePointer_$Rpanda$core$Int64(void*);
void* panda$io$FileOutputStream$open_class_panda$core$String_Bit_Bit_$Rpanda$core$$NativePointer(panda$core$String*, Bit, Bit);
void panda$io$FileOutputStream$writeUInt8_class_panda$core$$NativePointer_UInt8(void*, UInt8);
void panda$io$FileOutputStream$writeUInt8Array_class_panda$core$$NativePointer_panda$collections$ListView$LTpanda$core$UInt8$GT_Int64_Int64(void*, panda$collections$ListView$LTpanda$core$UInt8$GT*, Int64, Int64);
#endif
#endif
