// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure121_H
#define panda$util$JSONParser$closure121_H
extern panda$core$Class panda$util$JSONParser$closure121_class;
#ifndef CLASS_panda$util$JSONParser$closure121
#define CLASS_panda$util$JSONParser$closure121
struct panda$util$JSONParser$closure121 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure121$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure121$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure121* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure121$init(panda$util$JSONParser$closure121* self);
panda$util$JSONParser$closure121* new_panda$util$JSONParser$closure121$init();
#endif
#endif
