// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Array$LTpanda$io$File$GT_H
#define panda$collections$Array$LTpanda$io$File$GT_H
extern panda$core$Class panda$collections$Array$LTpanda$io$File$GT_class;
#ifndef CLASS_panda$collections$Array$LTpanda$io$File$GT
#define CLASS_panda$collections$Array$LTpanda$io$File$GT
struct panda$collections$Array$LTpanda$io$File$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LTpanda$io$File$GT* contents;
    Int64 _count;
};

#define panda$collections$Array$LTpanda$io$File$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$Array$LTpanda$io$File$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self);
#define panda$collections$Array$LTpanda$io$File$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$Array$LTpanda$io$File$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, panda$core$Object*);
#define panda$collections$Array$LTpanda$io$File$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$Array$LTpanda$io$File$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self);
#define panda$collections$Array$LTpanda$io$File$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$Array$LTpanda$io$File$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self);
#define panda$collections$Array$LTpanda$io$File$GT$addAll_panda$collections$CollectionView$LTpanda$io$File$GT_INDEX 5
typedef void(panda$collections$Array$LTpanda$io$File$GT$addAll_panda$collections$CollectionView$LTpanda$io$File$GT_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, panda$collections$CollectionView$LTpanda$io$File$GT*);
#define panda$collections$Array$LTpanda$io$File$GT$add_panda$io$File_INDEX 6
typedef void(panda$collections$Array$LTpanda$io$File$GT$add_panda$io$File_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, panda$io$File*);
#define panda$collections$Array$LTpanda$io$File$GT$add_panda$collections$ListView$LTpanda$io$File$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$Array$LTpanda$io$File$GT$add_panda$collections$ListView$LTpanda$io$File$GT_Int64_Int64_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, panda$collections$ListView$LTpanda$io$File$GT*, Int64, Int64);
#define panda$collections$Array$LTpanda$io$File$GT$remove_panda$io$File_INDEX 8
typedef void(panda$collections$Array$LTpanda$io$File$GT$remove_panda$io$File_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, panda$io$File*);
#define panda$collections$Array$LTpanda$io$File$GT$clear_INDEX 9
typedef void(panda$collections$Array$LTpanda$io$File$GT$clear_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self);
#define panda$collections$Array$LTpanda$io$File$GT$$ARREQ_Int64_panda$io$File_INDEX 10
typedef void(panda$collections$Array$LTpanda$io$File$GT$$ARREQ_Int64_panda$io$File_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, Int64, panda$io$File*);
#define panda$collections$Array$LTpanda$io$File$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$Array$LTpanda$io$File$GT$removeIndex_Int64_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, Int64);
#define panda$collections$Array$LTpanda$io$File$GT$contains_panda$io$File_$Rpanda$core$Bit_INDEX 19
typedef Bit(panda$collections$Array$LTpanda$io$File$GT$contains_panda$io$File_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, panda$io$File*);
#define panda$collections$Array$LTpanda$io$File$GT$$ARR_Int64_$Rpanda$io$File_INDEX 25
typedef panda$io$File*(panda$collections$Array$LTpanda$io$File$GT$$ARR_Int64_$Rpanda$io$File_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, Int64);
#define panda$collections$Array$LTpanda$io$File$GT$sorted_$LPpanda$io$File$Cpanda$io$File$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$io$File$GT_INDEX 39
typedef panda$collections$Array$LTpanda$io$File$GT*(panda$collections$Array$LTpanda$io$File$GT$sorted_$LPpanda$io$File$Cpanda$io$File$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$io$File$GT_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, void**);
#define panda$collections$Array$LTpanda$io$File$GT$sort_$LPpanda$io$File$Cpanda$io$File$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 40
typedef void(panda$collections$Array$LTpanda$io$File$GT$sort_$LPpanda$io$File$Cpanda$io$File$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$Array$LTpanda$io$File$GT* self, void**);
void panda$collections$Array$LTpanda$io$File$GT$init(panda$collections$Array$LTpanda$io$File$GT* self);
panda$collections$Array$LTpanda$io$File$GT* new_panda$collections$Array$LTpanda$io$File$GT$init();
void panda$collections$Array$LTpanda$io$File$GT$init_Int64(panda$collections$Array$LTpanda$io$File$GT* self, Int64);
panda$collections$Array$LTpanda$io$File$GT* new_panda$collections$Array$LTpanda$io$File$GT$init_Int64(Int64);
void panda$collections$Array$LTpanda$io$File$GT$init_Int64_panda$io$File(panda$collections$Array$LTpanda$io$File$GT* self, Int64, panda$io$File*);
panda$collections$Array$LTpanda$io$File$GT* new_panda$collections$Array$LTpanda$io$File$GT$init_Int64_panda$io$File(Int64, panda$io$File*);
void panda$collections$Array$LTpanda$io$File$GT$init_panda$collections$PrimitiveArray$LTpanda$io$File$GT(panda$collections$Array$LTpanda$io$File$GT* self, panda$collections$PrimitiveArray$LTpanda$io$File$GT*);
panda$collections$Array$LTpanda$io$File$GT* new_panda$collections$Array$LTpanda$io$File$GT$init_panda$collections$PrimitiveArray$LTpanda$io$File$GT(panda$collections$PrimitiveArray$LTpanda$io$File$GT*);
void panda$collections$Array$LTpanda$io$File$GT$init_panda$collections$CollectionView$LTpanda$io$File$GT(panda$collections$Array$LTpanda$io$File$GT* self, panda$collections$CollectionView$LTpanda$io$File$GT*);
panda$collections$Array$LTpanda$io$File$GT* new_panda$collections$Array$LTpanda$io$File$GT$init_panda$collections$CollectionView$LTpanda$io$File$GT(panda$collections$CollectionView$LTpanda$io$File$GT*);
void panda$collections$Array$LTpanda$io$File$GT$swap_Int64_Int64(panda$collections$Array$LTpanda$io$File$GT* self, Int64, Int64);
void panda$collections$Array$LTpanda$io$File$GT$sort_Int64_Int64_$LPpanda$io$File$Cpanda$io$File$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Array$LTpanda$io$File$GT* self, Int64, Int64, void**);
void panda$collections$Array$LTpanda$io$File$GT$ensureCapacity_Int64(panda$collections$Array$LTpanda$io$File$GT* self, Int64);
extern Int64 class_panda$collections$Array$DEFAULT_COUNT;
extern Bit class_panda$collections$Array$$classInited;
#endif
#endif
