// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT_H
#define panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT_H
extern panda$core$Class panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT_class;
#ifndef CLASS_panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT
#define CLASS_panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT
struct panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT* self);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$fold_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$parser$GLRParser$ParseError$RP_$Rpanda$parser$GLRParser$ParseError_INDEX 5
typedef panda$parser$GLRParser$ParseError*(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$fold_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$parser$GLRParser$ParseError$RP_$Rpanda$parser$GLRParser$ParseError_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT* self, void**);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$fold_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$parser$GLRParser$ParseError$RP_panda$parser$GLRParser$ParseError_$Rpanda$parser$GLRParser$ParseError_INDEX 6
typedef panda$parser$GLRParser$ParseError*(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$fold_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$parser$GLRParser$ParseError$RP_panda$parser$GLRParser$ParseError_$Rpanda$parser$GLRParser$ParseError_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT* self, void**, panda$parser$GLRParser$ParseError*);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$filter_$LPpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT_INDEX 7
typedef panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT*(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$filter_$LPpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT* self, void**);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$next_$Rpanda$parser$GLRParser$ParseError_INDEX 8
typedef panda$parser$GLRParser$ParseError*(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT$next_$Rpanda$parser$GLRParser$ParseError_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT* self);
#endif
#endif
