// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListWriter$LTpanda$io$File$GT_H
#define panda$collections$ListWriter$LTpanda$io$File$GT_H
extern panda$core$Class panda$collections$ListWriter$LTpanda$io$File$GT_class;
#ifndef CLASS_panda$collections$ListWriter$LTpanda$io$File$GT
#define CLASS_panda$collections$ListWriter$LTpanda$io$File$GT
struct panda$collections$ListWriter$LTpanda$io$File$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListWriter$LTpanda$io$File$GT$$ARREQ_Int64_panda$io$File_INDEX 10
typedef void(panda$collections$ListWriter$LTpanda$io$File$GT$$ARREQ_Int64_panda$io$File_TYPE)(panda$collections$ListWriter$LTpanda$io$File$GT* self, Int64, panda$io$File*);
#define panda$collections$ListWriter$LTpanda$io$File$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$ListWriter$LTpanda$io$File$GT$removeIndex_Int64_TYPE)(panda$collections$ListWriter$LTpanda$io$File$GT* self, Int64);
#define panda$collections$ListWriter$LTpanda$io$File$GT$insert_Int64_panda$io$File_INDEX 12
typedef void(panda$collections$ListWriter$LTpanda$io$File$GT$insert_Int64_panda$io$File_TYPE)(panda$collections$ListWriter$LTpanda$io$File$GT* self, Int64, panda$io$File*);
#endif
#endif
