// This file was automatically generated by the Panda compiler
#ifndef panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT_H
#define panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT_H
extern panda$core$Class panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT_class;
#ifndef CLASS_panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT
#define CLASS_panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT
struct panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT {
    panda$core$Class* cl;
    panda$core$Immutable* key;
    panda$core$Object* value;
    panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT* next;
};

void panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT$init_panda$core$Immutable_panda$core$Object(panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT* self, panda$core$Immutable*, panda$core$Object*);
panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT* new_panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT$init_panda$core$Immutable_panda$core$Object(panda$core$Immutable*, panda$core$Object*);
#endif
#endif
