// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionView$LTpanda$core$UInt8$GT_H
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT_H
extern panda$core$Class panda$collections$CollectionView$LTpanda$core$UInt8$GT_class;
#ifndef CLASS_panda$collections$CollectionView$LTpanda$core$UInt8$GT
#define CLASS_panda$collections$CollectionView$LTpanda$core$UInt8$GT
struct panda$collections$CollectionView$LTpanda$core$UInt8$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$CollectionView$LTpanda$core$UInt8$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self);
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$UInt8$RP$GT_INDEX 6
typedef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$UInt8$RP$GT*(panda$collections$CollectionView$LTpanda$core$UInt8$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$UInt8$RP$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self);
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$apply_$LPpanda$core$UInt8$RP$EQ$AM$GT$LP$RP_INDEX 7
typedef void(panda$collections$CollectionView$LTpanda$core$UInt8$GT$apply_$LPpanda$core$UInt8$RP$EQ$AM$GT$LP$RP_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$fold_$LPpanda$core$UInt8$Cpanda$core$UInt8$RP$EQ$GT$LPpanda$core$UInt8$RP_$Rpanda$core$UInt8_INDEX 8
typedef UInt8(panda$collections$CollectionView$LTpanda$core$UInt8$GT$fold_$LPpanda$core$UInt8$Cpanda$core$UInt8$RP$EQ$GT$LPpanda$core$UInt8$RP_$Rpanda$core$UInt8_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$fold_$LPpanda$core$UInt8$Cpanda$core$UInt8$RP$EQ$GT$LPpanda$core$UInt8$RP_UInt8_$Rpanda$core$UInt8_INDEX 9
typedef UInt8(panda$collections$CollectionView$LTpanda$core$UInt8$GT$fold_$LPpanda$core$UInt8$Cpanda$core$UInt8$RP$EQ$GT$LPpanda$core$UInt8$RP_UInt8_$Rpanda$core$UInt8_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self, void**, UInt8);
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$filter_$LPpanda$core$UInt8$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$UInt8$GT_INDEX 10
typedef panda$collections$CollectionView$LTpanda$core$UInt8$GT*(panda$collections$CollectionView$LTpanda$core$UInt8$GT$filter_$LPpanda$core$UInt8$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$UInt8$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$contains_UInt8_$Rpanda$core$Bit_INDEX 11
typedef Bit(panda$collections$CollectionView$LTpanda$core$UInt8$GT$contains_UInt8_$Rpanda$core$Bit_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self, UInt8);
#define panda$collections$CollectionView$LTpanda$core$UInt8$GT$convert_$Rpanda$collections$Array$LTpanda$core$UInt8$GT_INDEX 12
typedef panda$collections$Array$LTpanda$core$UInt8$GT*(panda$collections$CollectionView$LTpanda$core$UInt8$GT$convert_$Rpanda$collections$Array$LTpanda$core$UInt8$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$UInt8$GT* self);
#endif
#endif
