// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_H
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_H
extern panda$core$Class panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_class;
#ifndef CLASS_panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT
#define CLASS_panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT
struct panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* contents;
    Int64 _count;
};

#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$core$Object*);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$addAll_panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_INDEX 5
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$addAll_panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$add_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_INDEX 6
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$add_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$add_panda$collections$ListView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$add_panda$collections$ListView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_Int64_Int64_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$collections$ListView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*, Int64, Int64);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$remove_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_INDEX 8
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$remove_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$clear_INDEX 9
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$clear_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$ARREQ_Int64_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_INDEX 10
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$ARREQ_Int64_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$removeIndex_Int64_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$contains_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_$Rpanda$core$Bit_INDEX 19
typedef Bit(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$contains_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$ARR_Int64_$R$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_INDEX 25
typedef $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$ARR_Int64_$R$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$sorted_$LP$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_INDEX 39
typedef panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$sorted_$LP$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, void**);
#define panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$sort_$LP$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 40
typedef void(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$sort_$LP$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, void**);
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init();
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_Int64(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64);
panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_Int64(Int64);
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_Int64_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_Int64_$LPpanda$core$Immutable$Cpanda$core$Immutable$RP(Int64, $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*);
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$swap_Int64_Int64(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64, Int64);
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$sort_Int64_Int64_$LP$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$C$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64, Int64, void**);
void panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$ensureCapacity_Int64(panda$collections$Array$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64);
extern Int64 class_panda$collections$Array$DEFAULT_COUNT;
extern Bit class_panda$collections$Array$$classInited;
#endif
#endif
