// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure146_H
#define panda$util$JSONParser$closure146_H
extern panda$core$Class panda$util$JSONParser$closure146_class;
#ifndef CLASS_panda$util$JSONParser$closure146
#define CLASS_panda$util$JSONParser$closure146
struct panda$util$JSONParser$closure146 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure146$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure146$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure146* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure146$init(panda$util$JSONParser$closure146* self);
panda$util$JSONParser$closure146* new_panda$util$JSONParser$closure146$init();
#endif
#endif
