// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT_H
#define panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT_H
extern panda$core$Class panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT_class;
#ifndef CLASS_panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT
#define CLASS_panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT
struct panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT$$ARREQ_Int64_panda$parser$GLRParser$ParseError_INDEX 10
typedef void(panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT$$ARREQ_Int64_panda$parser$GLRParser$ParseError_TYPE)(panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT* self, Int64, panda$parser$GLRParser$ParseError*);
#define panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT$removeIndex_Int64_TYPE)(panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT* self, Int64);
#define panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT$insert_Int64_panda$parser$GLRParser$ParseError_INDEX 12
typedef void(panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT$insert_Int64_panda$parser$GLRParser$ParseError_TYPE)(panda$collections$ListWriter$LTpanda$parser$GLRParser$ParseError$GT* self, Int64, panda$parser$GLRParser$ParseError*);
#endif
#endif
