// This file was automatically generated by the Panda compiler
#ifndef panda$core$Panda$closure76_H
#define panda$core$Panda$closure76_H
extern panda$core$Class panda$core$Panda$closure76_class;
#ifndef CLASS_panda$core$Panda$closure76
#define CLASS_panda$core$Panda$closure76
struct panda$core$Panda$closure76 {
    panda$core$Class* cl;
    Int64 count;
    void** f;
};

#define panda$core$Panda$closure76$closure_panda$core$String_$Rpanda$core$String_INDEX 4
typedef panda$core$String*(panda$core$Panda$closure76$closure_panda$core$String_$Rpanda$core$String_TYPE)(panda$core$Panda$closure76* self, panda$core$String*);
void panda$core$Panda$closure76$init_Int64_$LPpanda$core$String$RP$EQ$GT$LPpanda$core$String$RP(panda$core$Panda$closure76* self, Int64, void**);
panda$core$Panda$closure76* new_panda$core$Panda$closure76$init_Int64_$LPpanda$core$String$RP$EQ$GT$LPpanda$core$String$RP(Int64, void**);
#endif
#endif
