// This file was automatically generated by the Panda compiler
#ifndef panda$io$File_H
#define panda$io$File_H
extern panda$core$Class panda$io$File_class;
#ifndef CLASS_panda$io$File
#define CLASS_panda$io$File
struct panda$io$File {
    panda$core$Class* cl;
    panda$core$String* path;
};

#define panda$io$File$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$io$File$convert_$Rpanda$core$String_TYPE)(panda$io$File* self);
#define panda$io$File$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$io$File$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$io$File* self, panda$core$Object*);
#define panda$io$File$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$io$File$get_hash_$Rpanda$core$Int64_TYPE)(panda$io$File* self);
#define panda$io$File$createDirectory_INDEX 4
typedef void(panda$io$File$createDirectory_TYPE)(panda$io$File* self);
#define panda$io$File$exists_$Rpanda$core$Bit_INDEX 5
typedef Bit(panda$io$File$exists_$Rpanda$core$Bit_TYPE)(panda$io$File* self);
#define panda$io$File$isDirectory_$Rpanda$core$Bit_INDEX 6
typedef Bit(panda$io$File$isDirectory_$Rpanda$core$Bit_TYPE)(panda$io$File* self);
#define panda$io$File$list_$Rpanda$collections$ListView$LTpanda$io$File$GT_INDEX 7
typedef panda$collections$ListView$LTpanda$io$File$GT*(panda$io$File$list_$Rpanda$collections$ListView$LTpanda$io$File$GT_TYPE)(panda$io$File* self);
#define panda$io$File$list_panda$core$String_$Rpanda$collections$ListView$LTpanda$io$File$GT_INDEX 8
typedef panda$collections$ListView$LTpanda$io$File$GT*(panda$io$File$list_panda$core$String_$Rpanda$collections$ListView$LTpanda$io$File$GT_TYPE)(panda$io$File* self, panda$core$String*);
#define panda$io$File$list_panda$core$RegularExpression_$Rpanda$collections$ListView$LTpanda$io$File$GT_INDEX 9
typedef panda$collections$ListView$LTpanda$io$File$GT*(panda$io$File$list_panda$core$RegularExpression_$Rpanda$collections$ListView$LTpanda$io$File$GT_TYPE)(panda$io$File* self, panda$core$RegularExpression*);
#define panda$io$File$readAsUInt8Array_$Rpanda$collections$Array$LTpanda$core$UInt8$GT_INDEX 10
typedef panda$collections$Array$LTpanda$core$UInt8$GT*(panda$io$File$readAsUInt8Array_$Rpanda$collections$Array$LTpanda$core$UInt8$GT_TYPE)(panda$io$File* self);
#define panda$io$File$parent_$Rpanda$io$File$Z_INDEX 11
typedef panda$io$File*(panda$io$File$parent_$Rpanda$io$File$Z_TYPE)(panda$io$File* self);
#define panda$io$File$delete_INDEX 12
typedef void(panda$io$File$delete_TYPE)(panda$io$File* self);
#define panda$io$File$openOutputStream_$Rpanda$io$OutputStream_INDEX 13
typedef panda$io$OutputStream*(panda$io$File$openOutputStream_$Rpanda$io$OutputStream_TYPE)(panda$io$File* self);
#define panda$io$File$lines_$Rpanda$collections$Iterator$LTpanda$core$String$GT_INDEX 14
typedef panda$collections$Iterator$LTpanda$core$String$GT*(panda$io$File$lines_$Rpanda$collections$Iterator$LTpanda$core$String$GT_TYPE)(panda$io$File* self);
#define panda$io$File$resolve_panda$core$String_$Rpanda$io$File_INDEX 15
typedef panda$io$File*(panda$io$File$resolve_panda$core$String_$Rpanda$io$File_TYPE)(panda$io$File* self, panda$core$String*);
#define panda$io$File$createDirectories_INDEX 16
typedef void(panda$io$File$createDirectories_TYPE)(panda$io$File* self);
#define panda$io$File$absolute_$Rpanda$io$File_INDEX 17
typedef panda$io$File*(panda$io$File$absolute_$Rpanda$io$File_TYPE)(panda$io$File* self);
#define panda$io$File$openInputStream_$Rpanda$io$InputStream_INDEX 18
typedef panda$io$InputStream*(panda$io$File$openInputStream_$Rpanda$io$InputStream_TYPE)(panda$io$File* self);
#define panda$io$File$readAsString_$Rpanda$core$String_INDEX 19
typedef panda$core$String*(panda$io$File$readAsString_$Rpanda$core$String_TYPE)(panda$io$File* self);
#define panda$io$File$write_panda$core$String_INDEX 20
typedef void(panda$io$File$write_panda$core$String_TYPE)(panda$io$File* self, panda$core$String*);
#define panda$io$File$write_panda$collections$ListView$LTpanda$core$Int8$GT_INDEX 21
typedef void(panda$io$File$write_panda$collections$ListView$LTpanda$core$Int8$GT_TYPE)(panda$io$File* self, panda$collections$ListView$LTpanda$core$Int8$GT*);
void panda$io$File$init_panda$core$String(panda$io$File* self, panda$core$String*);
panda$io$File* new_panda$io$File$init_panda$core$String(panda$core$String*);
panda$io$File* panda$io$File$currentDirectory_class_$Rpanda$io$File();
panda$core$String* panda$io$File$get_name_$Rpanda$core$String(panda$io$File* self);
panda$core$String* panda$io$File$get_simpleName_$Rpanda$core$String(panda$io$File* self);
panda$core$String* panda$io$File$get_extension_$Rpanda$core$String(panda$io$File* self);
panda$io$File* panda$io$File$absolute_$Rpanda$io$File(panda$io$File* self);
panda$io$File* panda$io$File$parent_$Rpanda$io$File$Z(panda$io$File* self);
panda$io$File* panda$io$File$resolve_panda$core$String_$Rpanda$io$File(panda$io$File* self, panda$core$String*);
Bit panda$io$File$exists_$Rpanda$core$Bit(panda$io$File* self);
Bit panda$io$File$isDirectory_$Rpanda$core$Bit(panda$io$File* self);
void panda$io$File$createDirectory(panda$io$File* self);
void panda$io$File$createDirectories(panda$io$File* self);
panda$collections$ListView$LTpanda$io$File$GT* panda$io$File$list_$Rpanda$collections$ListView$LTpanda$io$File$GT(panda$io$File* self);
panda$collections$ListView$LTpanda$io$File$GT* panda$io$File$list_panda$core$String_$Rpanda$collections$ListView$LTpanda$io$File$GT(panda$io$File* self, panda$core$String*);
panda$collections$ListView$LTpanda$io$File$GT* panda$io$File$list_panda$core$RegularExpression_$Rpanda$collections$ListView$LTpanda$io$File$GT(panda$io$File* self, panda$core$RegularExpression*);
panda$core$String* panda$io$File$convert_$Rpanda$core$String(panda$io$File* self);
void panda$io$File$delete(panda$io$File* self);
panda$io$InputStream* panda$io$File$openInputStream_$Rpanda$io$InputStream(panda$io$File* self);
panda$io$OutputStream* panda$io$File$openOutputStream_$Rpanda$io$OutputStream(panda$io$File* self);
void panda$io$File$write_panda$core$String(panda$io$File* self, panda$core$String*);
void panda$io$File$write_panda$collections$ListView$LTpanda$core$Int8$GT(panda$io$File* self, panda$collections$ListView$LTpanda$core$Int8$GT*);
panda$core$String* panda$io$File$readAsString_$Rpanda$core$String(panda$io$File* self);
panda$collections$Array$LTpanda$core$UInt8$GT* panda$io$File$readAsUInt8Array_$Rpanda$collections$Array$LTpanda$core$UInt8$GT(panda$io$File* self);
panda$collections$Iterator$LTpanda$core$String$GT* panda$io$File$lines_$Rpanda$collections$Iterator$LTpanda$core$String$GT(panda$io$File* self);
Bit panda$io$File$$EQ_panda$core$Object_$Rpanda$core$Bit(panda$io$File* self, panda$core$Object*);
Int64 panda$io$File$get_hash_$Rpanda$core$Int64(panda$io$File* self);
panda$core$String* panda$io$File$absolutePath_$Rpanda$core$String(panda$io$File* self);
void panda$io$File$$classInit_class();
extern Char class_panda$io$File$SEPARATOR;
extern panda$io$File* class_panda$io$File$TEMP;
extern Bit class_panda$io$File$$classInited;
#endif
#endif
