// This file was automatically generated by the Panda compiler
#ifndef panda$core$Choice_H
#define panda$core$Choice_H
extern panda$core$Class panda$core$Choice_class;
#ifndef CLASS_panda$core$Choice
#define CLASS_panda$core$Choice
struct panda$core$Choice {
    panda$core$Class* cl;
};

void panda$core$Choice$init(panda$core$Choice* self);
panda$core$Choice* new_panda$core$Choice$init();
#endif
#endif
