// This file was automatically generated by the Panda compiler
#ifndef panda$io$FilterOutputStream_H
#define panda$io$FilterOutputStream_H
extern panda$core$Class panda$io$FilterOutputStream_class;
#ifndef CLASS_panda$io$FilterOutputStream
#define CLASS_panda$io$FilterOutputStream
struct panda$io$FilterOutputStream {
    panda$core$Class* cl;
    Bit closed;
    panda$io$OutputStream* out;
    Bit closeUnderlyingStream;
};

#define panda$io$FilterOutputStream$flush_INDEX 4
typedef void(panda$io$FilterOutputStream$flush_TYPE)(panda$io$FilterOutputStream* self);
#define panda$io$FilterOutputStream$close_INDEX 5
typedef void(panda$io$FilterOutputStream$close_TYPE)(panda$io$FilterOutputStream* self);
#define panda$io$FilterOutputStream$write_UInt8_INDEX 6
typedef void(panda$io$FilterOutputStream$write_UInt8_TYPE)(panda$io$FilterOutputStream* self, UInt8);
#define panda$io$FilterOutputStream$write_panda$collections$ListView$LTpanda$core$UInt8$GT_Int64_Int64_INDEX 8
typedef void(panda$io$FilterOutputStream$write_panda$collections$ListView$LTpanda$core$UInt8$GT_Int64_Int64_TYPE)(panda$io$FilterOutputStream* self, panda$collections$ListView$LTpanda$core$UInt8$GT*, Int64, Int64);
#define panda$io$FilterOutputStream$write_Char_INDEX 9
typedef void(panda$io$FilterOutputStream$write_Char_TYPE)(panda$io$FilterOutputStream* self, Char);
#define panda$io$FilterOutputStream$write_panda$collections$ListView$LTpanda$core$Char$GT_Int64_Int64_INDEX 11
typedef void(panda$io$FilterOutputStream$write_panda$collections$ListView$LTpanda$core$Char$GT_Int64_Int64_TYPE)(panda$io$FilterOutputStream* self, panda$collections$ListView$LTpanda$core$Char$GT*, Int64, Int64);
void panda$io$FilterOutputStream$init_panda$io$OutputStream(panda$io$FilterOutputStream* self, panda$io$OutputStream*);
panda$io$FilterOutputStream* new_panda$io$FilterOutputStream$init_panda$io$OutputStream(panda$io$OutputStream*);
#endif
#endif
