// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterable_H
#define panda$collections$Iterable_H
extern panda$core$Class panda$collections$Iterable_class;
#ifndef CLASS_panda$collections$Iterable
#define CLASS_panda$collections$Iterable
struct panda$collections$Iterable {
    panda$core$Class* cl;
};

#define panda$collections$Iterable$get_iterator_$Rpanda$collections$Iterator$LTpanda$collections$Iterable$T$GT_INDEX 4
typedef panda$collections$Iterator$LTpanda$core$Object$Z$GT*(panda$collections$Iterable$get_iterator_$Rpanda$collections$Iterator$LTpanda$collections$Iterable$T$GT_TYPE)(panda$collections$Iterable* self);
#endif
#endif
