// This file was automatically generated by the Panda compiler
#ifndef panda$core$Matcher_H
#define panda$core$Matcher_H
extern panda$core$Class panda$core$Matcher_class;
#ifndef CLASS_panda$core$Matcher
#define CLASS_panda$core$Matcher
struct panda$core$Matcher {
    panda$core$Class* cl;
    panda$core$String* _searchText;
    panda$core$RegularExpression* regex;
    Bit matched;
    Int64 replacementIndex;
};

#define panda$core$Matcher$group_Int64_$Rpanda$core$String_INDEX 4
typedef panda$core$String*(panda$core$Matcher$group_Int64_$Rpanda$core$String_TYPE)(panda$core$Matcher* self, Int64);
#define panda$core$Matcher$close_INDEX 5
typedef void(panda$core$Matcher$close_TYPE)(panda$core$Matcher* self);
#define panda$core$Matcher$appendTail_panda$core$MutableString_INDEX 6
typedef void(panda$core$Matcher$appendTail_panda$core$MutableString_TYPE)(panda$core$Matcher* self, panda$core$MutableString*);
#define panda$core$Matcher$matches_$Rpanda$core$Bit_INDEX 7
typedef Bit(panda$core$Matcher$matches_$Rpanda$core$Bit_TYPE)(panda$core$Matcher* self);
#define panda$core$Matcher$get_searchText_$Rpanda$core$String_INDEX 8
typedef panda$core$String*(panda$core$Matcher$get_searchText_$Rpanda$core$String_TYPE)(panda$core$Matcher* self);
#define panda$core$Matcher$set_searchText_panda$core$String_INDEX 9
typedef void(panda$core$Matcher$set_searchText_panda$core$String_TYPE)(panda$core$Matcher* self, panda$core$String*);
#define panda$core$Matcher$appendReplacement_panda$core$MutableString_panda$core$String_INDEX 10
typedef void(panda$core$Matcher$appendReplacement_panda$core$MutableString_panda$core$String_TYPE)(panda$core$Matcher* self, panda$core$MutableString*, panda$core$String*);
#define panda$core$Matcher$appendReplacement_panda$core$MutableString_panda$core$String_Bit_INDEX 11
typedef void(panda$core$Matcher$appendReplacement_panda$core$MutableString_panda$core$String_Bit_TYPE)(panda$core$Matcher* self, panda$core$MutableString*, panda$core$String*, Bit);
#define panda$core$Matcher$find_$Rpanda$core$Bit_INDEX 12
typedef Bit(panda$core$Matcher$find_$Rpanda$core$Bit_TYPE)(panda$core$Matcher* self);
#define panda$core$Matcher$find_Int64_$Rpanda$core$Bit_INDEX 13
typedef Bit(panda$core$Matcher$find_Int64_$Rpanda$core$Bit_TYPE)(panda$core$Matcher* self, Int64);
void panda$core$Matcher$init_panda$core$RegularExpression_panda$core$String(panda$core$Matcher* self, panda$core$RegularExpression*, panda$core$String*);
panda$core$Matcher* new_panda$core$Matcher$init_panda$core$RegularExpression_panda$core$String(panda$core$RegularExpression*, panda$core$String*);
panda$core$String* panda$core$Matcher$get_searchText_$Rpanda$core$String(panda$core$Matcher* self);
void panda$core$Matcher$set_searchText_panda$core$String(panda$core$Matcher* self, panda$core$String*);
Bit panda$core$Matcher$matches_$Rpanda$core$Bit(panda$core$Matcher* self);
Bit panda$core$Matcher$matches_class_panda$core$$NativePointer_$Rpanda$core$Bit(void*);
Bit panda$core$Matcher$find_$Rpanda$core$Bit(panda$core$Matcher* self);
Bit panda$core$Matcher$find_Int64_$Rpanda$core$Bit(panda$core$Matcher* self, Int64);
Bit panda$core$Matcher$find_class_panda$core$$NativePointer_Int64_$Rpanda$core$Bit(void*, Int64);
panda$core$String* panda$core$Matcher$group_Int64_$Rpanda$core$String(panda$core$Matcher* self, Int64);
panda$core$String* panda$core$Matcher$group_class_panda$core$$NativePointer_Int64_$Rpanda$core$String(void*, Int64);
Int64 panda$core$Matcher$get_groupCount_$Rpanda$core$Int64(panda$core$Matcher* self);
Int64 panda$core$Matcher$get_start_$Rpanda$core$Int64(panda$core$Matcher* self);
Int64 panda$core$Matcher$get_end_$Rpanda$core$Int64(panda$core$Matcher* self);
void panda$core$Matcher$appendReplacement_panda$core$MutableString_panda$core$String(panda$core$Matcher* self, panda$core$MutableString*, panda$core$String*);
void panda$core$Matcher$appendReplacement_panda$core$MutableString_panda$core$String_Bit(panda$core$Matcher* self, panda$core$MutableString*, panda$core$String*, Bit);
void panda$core$Matcher$appendTail_panda$core$MutableString(panda$core$Matcher* self, panda$core$MutableString*);
void panda$core$Matcher$close(panda$core$Matcher* self);
void panda$core$Matcher$setText_class_panda$core$$NativePointer_panda$core$String(void*, panda$core$String*);
Int64 panda$core$Matcher$_groupCount_class_panda$core$$NativePointer_$Rpanda$core$Int64(void*);
Int64 panda$core$Matcher$_start_class_panda$core$$NativePointer_$Rpanda$core$Int64(void*);
Int64 panda$core$Matcher$_end_class_panda$core$$NativePointer_$Rpanda$core$Int64(void*);
void panda$core$Matcher$$classInit_class();
extern panda$core$RegularExpression* class_panda$core$Matcher$REPLACEMENT_GROUPS;
extern Bit class_panda$core$Matcher$$classInited;
#endif
#endif
