// This file was automatically generated by the Panda compiler
#ifndef panda$io$File$closure76_H
#define panda$io$File$closure76_H
extern panda$core$Class panda$io$File$closure76_class;
#ifndef CLASS_panda$io$File$closure76
#define CLASS_panda$io$File$closure76
struct panda$io$File$closure76 {
    panda$core$Class* cl;
    panda$core$RegularExpression* pattern;
};

#define panda$io$File$closure76$closure_panda$io$File_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$io$File$closure76$closure_panda$io$File_$Rpanda$core$Bit_TYPE)(panda$io$File$closure76* self, panda$io$File*);
void panda$io$File$closure76$init_panda$core$RegularExpression(panda$io$File$closure76* self, panda$core$RegularExpression*);
panda$io$File$closure76* new_panda$io$File$closure76$init_panda$core$RegularExpression(panda$core$RegularExpression*);
#endif
#endif
