// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure142_H
#define panda$util$JSONParser$closure142_H
extern panda$core$Class panda$util$JSONParser$closure142_class;
#ifndef CLASS_panda$util$JSONParser$closure142
#define CLASS_panda$util$JSONParser$closure142
struct panda$util$JSONParser$closure142 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure142$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure142$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure142* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure142$init(panda$util$JSONParser$closure142* self);
panda$util$JSONParser$closure142* new_panda$util$JSONParser$closure142$init();
#endif
#endif
