// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListWriter$LTpanda$core$Real32$GT_H
#define panda$collections$ListWriter$LTpanda$core$Real32$GT_H
extern panda$core$Class panda$collections$ListWriter$LTpanda$core$Real32$GT_class;
#ifndef CLASS_panda$collections$ListWriter$LTpanda$core$Real32$GT
#define CLASS_panda$collections$ListWriter$LTpanda$core$Real32$GT
struct panda$collections$ListWriter$LTpanda$core$Real32$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListWriter$LTpanda$core$Real32$GT$$ARREQ_Int64_Real32_INDEX 10
typedef void(panda$collections$ListWriter$LTpanda$core$Real32$GT$$ARREQ_Int64_Real32_TYPE)(panda$collections$ListWriter$LTpanda$core$Real32$GT* self, Int64, Real32);
#define panda$collections$ListWriter$LTpanda$core$Real32$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$ListWriter$LTpanda$core$Real32$GT$removeIndex_Int64_TYPE)(panda$collections$ListWriter$LTpanda$core$Real32$GT* self, Int64);
#define panda$collections$ListWriter$LTpanda$core$Real32$GT$insert_Int64_Real32_INDEX 12
typedef void(panda$collections$ListWriter$LTpanda$core$Real32$GT$insert_Int64_Real32_TYPE)(panda$collections$ListWriter$LTpanda$core$Real32$GT* self, Int64, Real32);
#endif
#endif
