// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListWriter$LTpanda$core$Char$GT_H
#define panda$collections$ListWriter$LTpanda$core$Char$GT_H
extern panda$core$Class panda$collections$ListWriter$LTpanda$core$Char$GT_class;
#ifndef CLASS_panda$collections$ListWriter$LTpanda$core$Char$GT
#define CLASS_panda$collections$ListWriter$LTpanda$core$Char$GT
struct panda$collections$ListWriter$LTpanda$core$Char$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListWriter$LTpanda$core$Char$GT$$ARREQ_Int64_Char_INDEX 10
typedef void(panda$collections$ListWriter$LTpanda$core$Char$GT$$ARREQ_Int64_Char_TYPE)(panda$collections$ListWriter$LTpanda$core$Char$GT* self, Int64, Char);
#define panda$collections$ListWriter$LTpanda$core$Char$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$ListWriter$LTpanda$core$Char$GT$removeIndex_Int64_TYPE)(panda$collections$ListWriter$LTpanda$core$Char$GT* self, Int64);
#define panda$collections$ListWriter$LTpanda$core$Char$GT$insert_Int64_Char_INDEX 12
typedef void(panda$collections$ListWriter$LTpanda$core$Char$GT$insert_Int64_Char_TYPE)(panda$collections$ListWriter$LTpanda$core$Char$GT* self, Int64, Char);
#endif
#endif
