// This file was automatically generated by the Panda compiler
#ifndef panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT_H
#define panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT_H
extern panda$core$Class panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT_class;
#ifndef CLASS_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT
#define CLASS_panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT
struct panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT {
    panda$core$Class* cl;
    Int64 $length;
    panda$core$Immutable** contents;
};

#define panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT$length_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT$length_$Rpanda$core$Int64_TYPE)(panda$collections$PrimitiveArray$LTpanda$core$Immutable$GT* self);
#endif
#endif
