// This file was automatically generated by the Panda compiler
#ifndef panda$io$LineNumberInputStream_H
#define panda$io$LineNumberInputStream_H
extern panda$core$Class panda$io$LineNumberInputStream_class;
#ifndef CLASS_panda$io$LineNumberInputStream
#define CLASS_panda$io$LineNumberInputStream
struct panda$io$LineNumberInputStream {
    panda$core$Class* cl;
    Bit closed;
    panda$io$InputStream* raw;
    Bit closeUnderlyingStream;
    Int64 line;
    Int64 column;
};

#define panda$io$LineNumberInputStream$read_$Rpanda$core$UInt8Wrapper$Z_INDEX 9
typedef panda$core$UInt8Wrapper*(panda$io$LineNumberInputStream$read_$Rpanda$core$UInt8Wrapper$Z_TYPE)(panda$io$LineNumberInputStream* self);
#define panda$io$LineNumberInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 10
typedef panda$core$Int64Wrapper*(panda$io$LineNumberInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$io$LineNumberInputStream* self, panda$collections$ListWriter$LTpanda$core$UInt8$GT*, Int64);
void panda$io$LineNumberInputStream$init_panda$io$InputStream(panda$io$LineNumberInputStream* self, panda$io$InputStream*);
panda$io$LineNumberInputStream* new_panda$io$LineNumberInputStream$init_panda$io$InputStream(panda$io$InputStream*);
#endif
#endif
