// This file was automatically generated by the Panda compiler
#ifndef panda$collections$List$LTpanda$parser$GLRParser$Action$GT_H
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT_H
extern panda$core$Class panda$collections$List$LTpanda$parser$GLRParser$Action$GT_class;
#ifndef CLASS_panda$collections$List$LTpanda$parser$GLRParser$Action$GT
#define CLASS_panda$collections$List$LTpanda$parser$GLRParser$Action$GT
struct panda$collections$List$LTpanda$parser$GLRParser$Action$GT {
    panda$core$Class* cl;
};

#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$ARREQ_Int64_panda$parser$GLRParser$Action_INDEX 10
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$ARREQ_Int64_panda$parser$GLRParser$Action_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, Int64, panda$parser$GLRParser$Action*);
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$insert_Int64_panda$parser$GLRParser$Action_INDEX 12
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$insert_Int64_panda$parser$GLRParser$Action_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, Int64, panda$parser$GLRParser$Action*);
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$filterInPlace_$LPpanda$parser$GLRParser$Action$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 33
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$filterInPlace_$LPpanda$parser$GLRParser$Action$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, void**);
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$mapInPlace_$LPpanda$parser$GLRParser$Action$RP$EQ$GT$LPpanda$parser$GLRParser$Action$RP_INDEX 34
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$mapInPlace_$LPpanda$parser$GLRParser$Action$RP$EQ$GT$LPpanda$parser$GLRParser$Action$RP_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, void**);
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLIEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_INDEX 35
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLIEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT*);
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLIEQ_Int64_Int64_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_INDEX 36
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLIEQ_Int64_Int64_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, Int64, Int64, Int64, panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT*);
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLEEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_INDEX 37
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLEEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT*);
#define panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLEEQ_Int64_Int64_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_INDEX 38
typedef void(panda$collections$List$LTpanda$parser$GLRParser$Action$GT$$SLEEQ_Int64_Int64_Int64_panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT_TYPE)(panda$collections$List$LTpanda$parser$GLRParser$Action$GT* self, Int64, Int64, Int64, panda$collections$ListView$LTpanda$parser$GLRParser$Action$GT*);
#endif
#endif
