// This file was automatically generated by the Panda compiler
#ifndef panda$collections$IndexOutOfBoundsError_H
#define panda$collections$IndexOutOfBoundsError_H
extern panda$core$Class panda$collections$IndexOutOfBoundsError_class;
#ifndef CLASS_panda$collections$IndexOutOfBoundsError
#define CLASS_panda$collections$IndexOutOfBoundsError
struct panda$collections$IndexOutOfBoundsError {
    panda$core$Class* cl;
    panda$core$String* message;
    panda$collections$ImmutablePrimitiveArray$LTpanda$core$StackTraceEntry$GT* stack;
};

void panda$collections$IndexOutOfBoundsError$init_panda$core$String(panda$collections$IndexOutOfBoundsError* self, panda$core$String*);
panda$collections$IndexOutOfBoundsError* new_panda$collections$IndexOutOfBoundsError$init_panda$core$String(panda$core$String*);
#endif
#endif
