// This file was automatically generated by the Panda compiler
#ifndef panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_H
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_H
extern panda$core$Class panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_class;
#ifndef CLASS_panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT
#define CLASS_panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT
struct panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT {
    panda$core$Class* cl;
};

#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$ARREQ_Int64_$LPpanda$core$String$Cpanda$core$Object$Z$RP_INDEX 10
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$ARREQ_Int64_$LPpanda$core$String$Cpanda$core$Object$Z$RP_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, Int64, $LPpanda$core$String$Cpanda$core$Object$Z$RP*);
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$insert_Int64_$LPpanda$core$String$Cpanda$core$Object$Z$RP_INDEX 12
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$insert_Int64_$LPpanda$core$String$Cpanda$core$Object$Z$RP_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, Int64, $LPpanda$core$String$Cpanda$core$Object$Z$RP*);
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$filterInPlace_$LP$LPpanda$core$String$Cpanda$core$Object$Z$RP$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 33
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$filterInPlace_$LP$LPpanda$core$String$Cpanda$core$Object$Z$RP$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, void**);
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$mapInPlace_$LP$LPpanda$core$String$Cpanda$core$Object$Z$RP$RP$EQ$GT$LP$LPpanda$core$String$Cpanda$core$Object$Z$RP$RP_INDEX 34
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$mapInPlace_$LP$LPpanda$core$String$Cpanda$core$Object$Z$RP$RP$EQ$GT$LP$LPpanda$core$String$Cpanda$core$Object$Z$RP$RP_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, void**);
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLIEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_INDEX 35
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLIEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT*);
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLIEQ_Int64_Int64_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_INDEX 36
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLIEQ_Int64_Int64_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, Int64, Int64, Int64, panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT*);
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLEEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_INDEX 37
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLEEQ_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64, panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT*);
#define panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLEEQ_Int64_Int64_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_INDEX 38
typedef void(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT$$SLEEQ_Int64_Int64_Int64_panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT_TYPE)(panda$collections$List$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT* self, Int64, Int64, Int64, panda$collections$ListView$LT$LPpanda$core$String$Cpanda$core$Object$Z$RP$GT*);
#endif
#endif
