// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_H
#define panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_H
extern panda$core$Class panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_class;
#ifndef CLASS_panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT
#define CLASS_panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT
struct panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_iterator_$Rpanda$collections$Iterator$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_INDEX 4
typedef panda$collections$Iterator$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*(panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_iterator_$Rpanda$collections$Iterator$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_TYPE)(panda$collections$Iterable$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#endif
#endif
