// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LTpanda$core$Object$GT$closure74_H
#define panda$collections$Iterator$LTpanda$core$Object$GT$closure74_H
extern panda$core$Class panda$collections$Iterator$LTpanda$core$Object$GT$closure74_class;
#ifndef CLASS_panda$collections$Iterator$LTpanda$core$Object$GT$closure74
#define CLASS_panda$collections$Iterator$LTpanda$core$Object$GT$closure74
struct panda$collections$Iterator$LTpanda$core$Object$GT$closure74 {
    panda$core$Class* cl;
    void** $capture73;
};

#define panda$collections$Iterator$LTpanda$core$Object$GT$closure74$closure_panda$core$Object$Z_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LTpanda$core$Object$GT$closure74$closure_panda$core$Object$Z_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LTpanda$core$Object$GT$closure74* self, panda$core$Object*);
void panda$collections$Iterator$LTpanda$core$Object$GT$closure74$init_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$core$Object$GT$closure74* self, void**);
panda$collections$Iterator$LTpanda$core$Object$GT$closure74* new_panda$collections$Iterator$LTpanda$core$Object$GT$closure74$init_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP(void**);
#endif
#endif
