// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionView$LTpanda$core$String$Z$GT_H
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT_H
extern panda$core$Class panda$collections$CollectionView$LTpanda$core$String$Z$GT_class;
#ifndef CLASS_panda$collections$CollectionView$LTpanda$core$String$Z$GT
#define CLASS_panda$collections$CollectionView$LTpanda$core$String$Z$GT
struct panda$collections$CollectionView$LTpanda$core$String$Z$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$CollectionView$LTpanda$core$String$Z$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self);
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$String$Z$RP$GT_INDEX 6
typedef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$String$Z$RP$GT*(panda$collections$CollectionView$LTpanda$core$String$Z$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$String$Z$RP$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self);
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$apply_$LPpanda$core$String$Z$RP$EQ$AM$GT$LP$RP_INDEX 7
typedef void(panda$collections$CollectionView$LTpanda$core$String$Z$GT$apply_$LPpanda$core$String$Z$RP$EQ$AM$GT$LP$RP_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$fold_$LPpanda$core$String$Z$Cpanda$core$String$Z$RP$EQ$GT$LPpanda$core$String$Z$RP_$Rpanda$core$String$Z_INDEX 8
typedef panda$core$String*(panda$collections$CollectionView$LTpanda$core$String$Z$GT$fold_$LPpanda$core$String$Z$Cpanda$core$String$Z$RP$EQ$GT$LPpanda$core$String$Z$RP_$Rpanda$core$String$Z_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$fold_$LPpanda$core$String$Z$Cpanda$core$String$Z$RP$EQ$GT$LPpanda$core$String$Z$RP_panda$core$String$Z_$Rpanda$core$String$Z_INDEX 9
typedef panda$core$String*(panda$collections$CollectionView$LTpanda$core$String$Z$GT$fold_$LPpanda$core$String$Z$Cpanda$core$String$Z$RP$EQ$GT$LPpanda$core$String$Z$RP_panda$core$String$Z_$Rpanda$core$String$Z_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self, void**, panda$core$String*);
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$filter_$LPpanda$core$String$Z$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$String$Z$GT_INDEX 10
typedef panda$collections$CollectionView$LTpanda$core$String$Z$GT*(panda$collections$CollectionView$LTpanda$core$String$Z$GT$filter_$LPpanda$core$String$Z$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$String$Z$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$contains_panda$core$String$Z_$Rpanda$core$Bit_INDEX 11
typedef Bit(panda$collections$CollectionView$LTpanda$core$String$Z$GT$contains_panda$core$String$Z_$Rpanda$core$Bit_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self, panda$core$String*);
#define panda$collections$CollectionView$LTpanda$core$String$Z$GT$convert_$Rpanda$collections$Array$LTpanda$core$String$Z$GT_INDEX 12
typedef panda$collections$Array$LTpanda$core$String$Z$GT*(panda$collections$CollectionView$LTpanda$core$String$Z$GT$convert_$Rpanda$collections$Array$LTpanda$core$String$Z$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$String$Z$GT* self);
#endif
#endif
