// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT_H
#define panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT_H
extern panda$core$Class panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT_class;
#ifndef CLASS_panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT
#define CLASS_panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT
struct panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT* self);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$fold_$LPpanda$parser$GLRParser$Action$Z$Cpanda$parser$GLRParser$Action$Z$RP$EQ$GT$LPpanda$parser$GLRParser$Action$Z$RP_$Rpanda$parser$GLRParser$Action$Z_INDEX 5
typedef panda$parser$GLRParser$Action*(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$fold_$LPpanda$parser$GLRParser$Action$Z$Cpanda$parser$GLRParser$Action$Z$RP$EQ$GT$LPpanda$parser$GLRParser$Action$Z$RP_$Rpanda$parser$GLRParser$Action$Z_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT* self, void**);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$fold_$LPpanda$parser$GLRParser$Action$Z$Cpanda$parser$GLRParser$Action$Z$RP$EQ$GT$LPpanda$parser$GLRParser$Action$Z$RP_panda$parser$GLRParser$Action$Z_$Rpanda$parser$GLRParser$Action$Z_INDEX 6
typedef panda$parser$GLRParser$Action*(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$fold_$LPpanda$parser$GLRParser$Action$Z$Cpanda$parser$GLRParser$Action$Z$RP$EQ$GT$LPpanda$parser$GLRParser$Action$Z$RP_panda$parser$GLRParser$Action$Z_$Rpanda$parser$GLRParser$Action$Z_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT* self, void**, panda$parser$GLRParser$Action*);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$filter_$LPpanda$parser$GLRParser$Action$Z$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT_INDEX 7
typedef panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT*(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$filter_$LPpanda$parser$GLRParser$Action$Z$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT* self, void**);
#define panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$next_$Rpanda$parser$GLRParser$Action$Z_INDEX 8
typedef panda$parser$GLRParser$Action*(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT$next_$Rpanda$parser$GLRParser$Action$Z_TYPE)(panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT* self);
#endif
#endif
