// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LTpanda$core$Object$GT$closure75_H
#define panda$collections$Iterator$LTpanda$core$Object$GT$closure75_H
extern panda$core$Class panda$collections$Iterator$LTpanda$core$Object$GT$closure75_class;
#ifndef CLASS_panda$collections$Iterator$LTpanda$core$Object$GT$closure75
#define CLASS_panda$collections$Iterator$LTpanda$core$Object$GT$closure75
struct panda$collections$Iterator$LTpanda$core$Object$GT$closure75 {
    panda$core$Class* cl;
    void** $capture74;
};

#define panda$collections$Iterator$LTpanda$core$Object$GT$closure75$closure_panda$core$Object$Z_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LTpanda$core$Object$GT$closure75$closure_panda$core$Object$Z_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LTpanda$core$Object$GT$closure75* self, panda$core$Object*);
void panda$collections$Iterator$LTpanda$core$Object$GT$closure75$init_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$core$Object$GT$closure75* self, void**);
panda$collections$Iterator$LTpanda$core$Object$GT$closure75* new_panda$collections$Iterator$LTpanda$core$Object$GT$closure75$init_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP(void**);
#endif
#endif
