// This file was automatically generated by the Panda compiler
#ifndef panda$core$SignedInteger_H
#define panda$core$SignedInteger_H
extern panda$core$Class panda$core$SignedInteger_class;
#ifndef CLASS_panda$core$SignedInteger
#define CLASS_panda$core$SignedInteger
struct panda$core$SignedInteger {
    panda$core$Class* cl;
};

#define panda$core$SignedInteger$english_$Rpanda$core$String_INDEX 5
typedef panda$core$String*(panda$core$SignedInteger$english_$Rpanda$core$String_TYPE)(panda$core$SignedInteger* self);
#define panda$core$SignedInteger$roman_$Rpanda$core$String_INDEX 17
typedef panda$core$String*(panda$core$SignedInteger$roman_$Rpanda$core$String_TYPE)(panda$core$SignedInteger* self);
void panda$core$SignedInteger$init(panda$core$SignedInteger* self);
panda$core$SignedInteger* new_panda$core$SignedInteger$init();
#endif
#endif
