// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT_H
#define panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT_H
extern panda$core$Class panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT_class;
#ifndef CLASS_panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT
#define CLASS_panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT
struct panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT* self);
#define panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$addAll_panda$collections$CollectionView$LTpanda$core$Int64Wrapper$Z$GT_INDEX 5
typedef void(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$addAll_panda$collections$CollectionView$LTpanda$core$Int64Wrapper$Z$GT_TYPE)(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT* self, panda$collections$CollectionView$LTpanda$core$Int64Wrapper$Z$GT*);
#define panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$add_panda$core$Int64Wrapper$Z_INDEX 6
typedef void(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$add_panda$core$Int64Wrapper$Z_TYPE)(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT* self, panda$core$Int64Wrapper*);
#define panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$add_panda$collections$ListView$LTpanda$core$Int64Wrapper$Z$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$add_panda$collections$ListView$LTpanda$core$Int64Wrapper$Z$GT_Int64_Int64_TYPE)(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT* self, panda$collections$ListView$LTpanda$core$Int64Wrapper$Z$GT*, Int64, Int64);
#define panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$remove_panda$core$Int64Wrapper$Z_INDEX 8
typedef void(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$remove_panda$core$Int64Wrapper$Z_TYPE)(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT* self, panda$core$Int64Wrapper*);
#define panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$clear_INDEX 9
typedef void(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT$clear_TYPE)(panda$collections$CollectionWriter$LTpanda$core$Int64Wrapper$Z$GT* self);
#endif
#endif
