// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT_H
#define panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT_H
extern panda$core$Class panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT_class;
#ifndef CLASS_panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT
#define CLASS_panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT
struct panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT {
    panda$core$Class* cl;
    panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT* list;
    Int64 index;
};

#define panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT* self);
#define panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT$next_$Rpanda$parser$GLRParser$ParseError_INDEX 8
typedef panda$parser$GLRParser$ParseError*(panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT$next_$Rpanda$parser$GLRParser$ParseError_TYPE)(panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT* self);
void panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT* self, panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT*);
panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT* new_panda$collections$ListIterator$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT*);
#endif
#endif
