// This file was automatically generated by the Panda compiler
#ifndef panda$collections$PrimitiveArray$LTpanda$io$File$GT_H
#define panda$collections$PrimitiveArray$LTpanda$io$File$GT_H
extern panda$core$Class panda$collections$PrimitiveArray$LTpanda$io$File$GT_class;
#ifndef CLASS_panda$collections$PrimitiveArray$LTpanda$io$File$GT
#define CLASS_panda$collections$PrimitiveArray$LTpanda$io$File$GT
struct panda$collections$PrimitiveArray$LTpanda$io$File$GT {
    panda$core$Class* cl;
    Int64 length;
    panda$io$File** contents;
};

#endif
#endif
