// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutableTuple_H
#define panda$collections$ImmutableTuple_H
extern panda$core$Class panda$collections$ImmutableTuple_class;
#ifndef CLASS_panda$collections$ImmutableTuple
#define CLASS_panda$collections$ImmutableTuple
struct panda$collections$ImmutableTuple {
    panda$core$Class* cl;
};

Int64 panda$collections$ImmutableTuple$hashField_class_panda$core$Object$Z_$Rpanda$core$Int64(panda$core$Object*);
void panda$collections$ImmutableTuple$init(panda$collections$ImmutableTuple* self);
panda$collections$ImmutableTuple* new_panda$collections$ImmutableTuple$init();
#endif
#endif
