// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT_H
#define panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT_H
extern panda$core$Class panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT_class;
#ifndef CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT
#define CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT
struct panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT {
    panda$core$Class* cl;
    Int64 $length;
    panda$core$Object** contents;
};

#define panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT$length_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT$length_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutablePrimitiveArray$LTpanda$core$Object$Z$GT* self);
#endif
#endif
