// This file was automatically generated by the Panda compiler
#ifndef panda$io$FilterInputStream_H
#define panda$io$FilterInputStream_H
extern panda$core$Class panda$io$FilterInputStream_class;
#ifndef CLASS_panda$io$FilterInputStream
#define CLASS_panda$io$FilterInputStream
struct panda$io$FilterInputStream {
    panda$core$Class* cl;
    Bit closed;
    panda$io$InputStream* raw;
    Bit closeUnderlyingStream;
};

#define panda$io$FilterInputStream$close_INDEX 4
typedef void(panda$io$FilterInputStream$close_TYPE)(panda$io$FilterInputStream* self);
#define panda$io$FilterInputStream$read_$Rpanda$core$UInt8Wrapper$Z_INDEX 9
typedef panda$core$UInt8Wrapper*(panda$io$FilterInputStream$read_$Rpanda$core$UInt8Wrapper$Z_TYPE)(panda$io$FilterInputStream* self);
#define panda$io$FilterInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 10
typedef panda$core$Int64Wrapper*(panda$io$FilterInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$io$FilterInputStream* self, panda$collections$ListWriter$LTpanda$core$UInt8$GT*, Int64);
void panda$io$FilterInputStream$init_panda$io$InputStream(panda$io$FilterInputStream* self, panda$io$InputStream*);
panda$io$FilterInputStream* new_panda$io$FilterInputStream$init_panda$io$InputStream(panda$io$InputStream*);
#endif
#endif
