// This file was automatically generated by the Panda compiler
#ifndef panda$threads$InternalMessageQueue_H
#define panda$threads$InternalMessageQueue_H
extern panda$core$Class panda$threads$InternalMessageQueue_class;
#ifndef CLASS_panda$threads$InternalMessageQueue
#define CLASS_panda$threads$InternalMessageQueue
struct panda$threads$InternalMessageQueue {
    panda$core$Class* cl;
    void* nativeQueue;
};

#define panda$threads$InternalMessageQueue$finalize_INDEX 0
typedef void(panda$threads$InternalMessageQueue$finalize_TYPE)(panda$threads$InternalMessageQueue* self);
#define panda$threads$InternalMessageQueue$getMessage_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$threads$InternalMessageQueue$getMessage_$Rpanda$core$Object$Z_TYPE)(panda$threads$InternalMessageQueue* self);
#define panda$threads$InternalMessageQueue$getMessage_Int64_$Rpanda$core$Object$Z_INDEX 5
typedef panda$core$Object*(panda$threads$InternalMessageQueue$getMessage_Int64_$Rpanda$core$Object$Z_TYPE)(panda$threads$InternalMessageQueue* self, Int64);
#define panda$threads$InternalMessageQueue$pendingMessages_$Rpanda$core$Int64_INDEX 6
typedef Int64(panda$threads$InternalMessageQueue$pendingMessages_$Rpanda$core$Int64_TYPE)(panda$threads$InternalMessageQueue* self);
#define panda$threads$InternalMessageQueue$post_panda$core$Object$Z_INDEX 7
typedef void(panda$threads$InternalMessageQueue$post_panda$core$Object$Z_TYPE)(panda$threads$InternalMessageQueue* self, panda$core$Object*);
void panda$threads$InternalMessageQueue$init(panda$threads$InternalMessageQueue* self);
panda$threads$InternalMessageQueue* new_panda$threads$InternalMessageQueue$init();
Int64 panda$threads$InternalMessageQueue$pendingMessages_$Rpanda$core$Int64(panda$threads$InternalMessageQueue* self);
panda$core$Object* panda$threads$InternalMessageQueue$getMessage_$Rpanda$core$Object$Z(panda$threads$InternalMessageQueue* self);
panda$core$Object* panda$threads$InternalMessageQueue$getMessage_Int64_$Rpanda$core$Object$Z(panda$threads$InternalMessageQueue* self, Int64);
void panda$threads$InternalMessageQueue$finalize(panda$threads$InternalMessageQueue* self);
void panda$threads$InternalMessageQueue$initMessageQueue(panda$threads$InternalMessageQueue* self);
void panda$threads$InternalMessageQueue$sendMessage_panda$threads$Message(panda$threads$InternalMessageQueue* self, panda$threads$Message*);
void panda$threads$InternalMessageQueue$threadExit_class();
#endif
#endif
