// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterable$LTpanda$core$Real32$GT_H
#define panda$collections$Iterable$LTpanda$core$Real32$GT_H
extern panda$core$Class panda$collections$Iterable$LTpanda$core$Real32$GT_class;
#ifndef CLASS_panda$collections$Iterable$LTpanda$core$Real32$GT
#define CLASS_panda$collections$Iterable$LTpanda$core$Real32$GT
struct panda$collections$Iterable$LTpanda$core$Real32$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterable$LTpanda$core$Real32$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Real32$GT_INDEX 4
typedef panda$collections$Iterator$LTpanda$core$Real32$GT*(panda$collections$Iterable$LTpanda$core$Real32$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Real32$GT_TYPE)(panda$collections$Iterable$LTpanda$core$Real32$GT* self);
#endif
#endif
