// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure7_H
#define panda$util$JSONParser$closure7_H
extern panda$core$Class panda$util$JSONParser$closure7_class;
#ifndef CLASS_panda$util$JSONParser$closure7
#define CLASS_panda$util$JSONParser$closure7
struct panda$util$JSONParser$closure7 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure7$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure7$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure7* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure7$init(panda$util$JSONParser$closure7* self);
panda$util$JSONParser$closure7* new_panda$util$JSONParser$closure7$init();
#endif
#endif
