// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionView$LTpanda$core$Real32$GT_H
#define panda$collections$CollectionView$LTpanda$core$Real32$GT_H
extern panda$core$Class panda$collections$CollectionView$LTpanda$core$Real32$GT_class;
#ifndef CLASS_panda$collections$CollectionView$LTpanda$core$Real32$GT
#define CLASS_panda$collections$CollectionView$LTpanda$core$Real32$GT
struct panda$collections$CollectionView$LTpanda$core$Real32$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionView$LTpanda$core$Real32$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$CollectionView$LTpanda$core$Real32$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self);
#define panda$collections$CollectionView$LTpanda$core$Real32$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$Real32$RP$GT_INDEX 6
typedef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$Real32$RP$GT*(panda$collections$CollectionView$LTpanda$core$Real32$GT$get_enumeration_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$core$Real32$RP$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self);
#define panda$collections$CollectionView$LTpanda$core$Real32$GT$apply_$LPpanda$core$Real32$RP$EQ$AM$GT$LP$RP_INDEX 7
typedef void(panda$collections$CollectionView$LTpanda$core$Real32$GT$apply_$LPpanda$core$Real32$RP$EQ$AM$GT$LP$RP_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$Real32$GT$fold_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Real32$RP_$Rpanda$core$Real32_INDEX 8
typedef Real32(panda$collections$CollectionView$LTpanda$core$Real32$GT$fold_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Real32$RP_$Rpanda$core$Real32_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$Real32$GT$fold_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Real32$RP_Real32_$Rpanda$core$Real32_INDEX 9
typedef Real32(panda$collections$CollectionView$LTpanda$core$Real32$GT$fold_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Real32$RP_Real32_$Rpanda$core$Real32_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self, void**, Real32);
#define panda$collections$CollectionView$LTpanda$core$Real32$GT$filter_$LPpanda$core$Real32$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$Real32$GT_INDEX 10
typedef panda$collections$CollectionView$LTpanda$core$Real32$GT*(panda$collections$CollectionView$LTpanda$core$Real32$GT$filter_$LPpanda$core$Real32$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$CollectionView$LTpanda$core$Real32$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self, void**);
#define panda$collections$CollectionView$LTpanda$core$Real32$GT$contains_Real32_$Rpanda$core$Bit_INDEX 11
typedef Bit(panda$collections$CollectionView$LTpanda$core$Real32$GT$contains_Real32_$Rpanda$core$Bit_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self, Real32);
#define panda$collections$CollectionView$LTpanda$core$Real32$GT$convert_$Rpanda$collections$Array$LTpanda$core$Real32$GT_INDEX 12
typedef panda$collections$Array$LTpanda$core$Real32$GT*(panda$collections$CollectionView$LTpanda$core$Real32$GT$convert_$Rpanda$collections$Array$LTpanda$core$Real32$GT_TYPE)(panda$collections$CollectionView$LTpanda$core$Real32$GT* self);
#endif
#endif
