// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutableArray$LTpanda$core$String$GT_H
#define panda$collections$ImmutableArray$LTpanda$core$String$GT_H
extern panda$core$Class panda$collections$ImmutableArray$LTpanda$core$String$GT_class;
#ifndef CLASS_panda$collections$ImmutableArray$LTpanda$core$String$GT
#define CLASS_panda$collections$ImmutableArray$LTpanda$core$String$GT
struct panda$collections$ImmutableArray$LTpanda$core$String$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LTpanda$core$String$GT* contents;
};

#define panda$collections$ImmutableArray$LTpanda$core$String$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$ImmutableArray$LTpanda$core$String$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$ImmutableArray$LTpanda$core$String$GT* self);
#define panda$collections$ImmutableArray$LTpanda$core$String$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$ImmutableArray$LTpanda$core$String$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$ImmutableArray$LTpanda$core$String$GT* self, panda$core$Object*);
#define panda$collections$ImmutableArray$LTpanda$core$String$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$ImmutableArray$LTpanda$core$String$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableArray$LTpanda$core$String$GT* self);
#define panda$collections$ImmutableArray$LTpanda$core$String$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$ImmutableArray$LTpanda$core$String$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableArray$LTpanda$core$String$GT* self);
#define panda$collections$ImmutableArray$LTpanda$core$String$GT$$ARR_Int64_$Rpanda$core$String_INDEX 17
typedef panda$core$String*(panda$collections$ImmutableArray$LTpanda$core$String$GT$$ARR_Int64_$Rpanda$core$String_TYPE)(panda$collections$ImmutableArray$LTpanda$core$String$GT* self, Int64);
#define panda$collections$ImmutableArray$LTpanda$core$String$GT$convert_$Rpanda$collections$ImmutableArray$LTpanda$core$String$GT_INDEX 25
typedef panda$collections$ImmutableArray$LTpanda$core$String$GT*(panda$collections$ImmutableArray$LTpanda$core$String$GT$convert_$Rpanda$collections$ImmutableArray$LTpanda$core$String$GT_TYPE)(panda$collections$ImmutableArray$LTpanda$core$String$GT* self);
void panda$collections$ImmutableArray$LTpanda$core$String$GT$init(panda$collections$ImmutableArray$LTpanda$core$String$GT* self);
panda$collections$ImmutableArray$LTpanda$core$String$GT* new_panda$collections$ImmutableArray$LTpanda$core$String$GT$init();
void panda$collections$ImmutableArray$LTpanda$core$String$GT$init_panda$collections$PrimitiveArray$LTpanda$core$String$GT(panda$collections$ImmutableArray$LTpanda$core$String$GT* self, panda$collections$PrimitiveArray$LTpanda$core$String$GT*);
panda$collections$ImmutableArray$LTpanda$core$String$GT* new_panda$collections$ImmutableArray$LTpanda$core$String$GT$init_panda$collections$PrimitiveArray$LTpanda$core$String$GT(panda$collections$PrimitiveArray$LTpanda$core$String$GT*);
void panda$collections$ImmutableArray$LTpanda$core$String$GT$init_panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT(panda$collections$ImmutableArray$LTpanda$core$String$GT* self, panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT*);
panda$collections$ImmutableArray$LTpanda$core$String$GT* new_panda$collections$ImmutableArray$LTpanda$core$String$GT$init_panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT(panda$collections$ImmutablePrimitiveArray$LTpanda$core$String$GT*);
void panda$collections$ImmutableArray$LTpanda$core$String$GT$init_panda$collections$CollectionView$LTpanda$core$String$GT(panda$collections$ImmutableArray$LTpanda$core$String$GT* self, panda$collections$CollectionView$LTpanda$core$String$GT*);
panda$collections$ImmutableArray$LTpanda$core$String$GT* new_panda$collections$ImmutableArray$LTpanda$core$String$GT$init_panda$collections$CollectionView$LTpanda$core$String$GT(panda$collections$CollectionView$LTpanda$core$String$GT*);
#endif
#endif
