// This file was automatically generated by the Panda compiler
#ifndef panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_H
#define panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_H
extern panda$core$Class panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_class;
#ifndef CLASS_panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT
#define CLASS_panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT
struct panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT {
    panda$core$Class* cl;
};

#define panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$addAll_panda$collections$MapView$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_INDEX 4
typedef void(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$addAll_panda$collections$MapView$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_TYPE)(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$collections$MapView$LTpanda$core$Immutable$Cpanda$core$Immutable$GT*);
#define panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$remove_panda$core$Immutable_INDEX 5
typedef void(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$remove_panda$core$Immutable_TYPE)(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$$ARREQ_panda$core$Immutable_panda$core$Immutable_INDEX 6
typedef void(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$$ARREQ_panda$core$Immutable_panda$core$Immutable_TYPE)(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$core$Immutable*, panda$core$Immutable*);
#define panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$clear_INDEX 7
typedef void(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$clear_TYPE)(panda$collections$MapWriter$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self);
#endif
#endif
