// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Array$LTpanda$core$Real32$GT_H
#define panda$collections$Array$LTpanda$core$Real32$GT_H
extern panda$core$Class panda$collections$Array$LTpanda$core$Real32$GT_class;
#ifndef CLASS_panda$collections$Array$LTpanda$core$Real32$GT
#define CLASS_panda$collections$Array$LTpanda$core$Real32$GT
struct panda$collections$Array$LTpanda$core$Real32$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LTpanda$core$Real32$GT* contents;
    Int64 _count;
};

#define panda$collections$Array$LTpanda$core$Real32$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$Array$LTpanda$core$Real32$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self);
#define panda$collections$Array$LTpanda$core$Real32$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$Array$LTpanda$core$Real32$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, panda$core$Object*);
#define panda$collections$Array$LTpanda$core$Real32$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$Array$LTpanda$core$Real32$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self);
#define panda$collections$Array$LTpanda$core$Real32$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$Array$LTpanda$core$Real32$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self);
#define panda$collections$Array$LTpanda$core$Real32$GT$addAll_panda$collections$CollectionView$LTpanda$core$Real32$GT_INDEX 5
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$addAll_panda$collections$CollectionView$LTpanda$core$Real32$GT_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, panda$collections$CollectionView$LTpanda$core$Real32$GT*);
#define panda$collections$Array$LTpanda$core$Real32$GT$add_Real32_INDEX 6
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$add_Real32_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, Real32);
#define panda$collections$Array$LTpanda$core$Real32$GT$add_panda$collections$ListView$LTpanda$core$Real32$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$add_panda$collections$ListView$LTpanda$core$Real32$GT_Int64_Int64_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, panda$collections$ListView$LTpanda$core$Real32$GT*, Int64, Int64);
#define panda$collections$Array$LTpanda$core$Real32$GT$remove_Real32_INDEX 8
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$remove_Real32_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, Real32);
#define panda$collections$Array$LTpanda$core$Real32$GT$clear_INDEX 9
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$clear_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self);
#define panda$collections$Array$LTpanda$core$Real32$GT$$ARREQ_Int64_Real32_INDEX 10
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$$ARREQ_Int64_Real32_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64, Real32);
#define panda$collections$Array$LTpanda$core$Real32$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$removeIndex_Int64_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64);
#define panda$collections$Array$LTpanda$core$Real32$GT$contains_Real32_$Rpanda$core$Bit_INDEX 19
typedef Bit(panda$collections$Array$LTpanda$core$Real32$GT$contains_Real32_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, Real32);
#define panda$collections$Array$LTpanda$core$Real32$GT$$ARR_Int64_$Rpanda$core$Real32_INDEX 25
typedef Real32(panda$collections$Array$LTpanda$core$Real32$GT$$ARR_Int64_$Rpanda$core$Real32_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64);
#define panda$collections$Array$LTpanda$core$Real32$GT$sorted_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$core$Real32$GT_INDEX 39
typedef panda$collections$Array$LTpanda$core$Real32$GT*(panda$collections$Array$LTpanda$core$Real32$GT$sorted_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$core$Real32$GT_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, void**);
#define panda$collections$Array$LTpanda$core$Real32$GT$sort_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 40
typedef void(panda$collections$Array$LTpanda$core$Real32$GT$sort_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$Array$LTpanda$core$Real32$GT* self, void**);
void panda$collections$Array$LTpanda$core$Real32$GT$init(panda$collections$Array$LTpanda$core$Real32$GT* self);
panda$collections$Array$LTpanda$core$Real32$GT* new_panda$collections$Array$LTpanda$core$Real32$GT$init();
void panda$collections$Array$LTpanda$core$Real32$GT$init_Int64(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64);
panda$collections$Array$LTpanda$core$Real32$GT* new_panda$collections$Array$LTpanda$core$Real32$GT$init_Int64(Int64);
void panda$collections$Array$LTpanda$core$Real32$GT$init_Int64_Real32(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64, Real32);
panda$collections$Array$LTpanda$core$Real32$GT* new_panda$collections$Array$LTpanda$core$Real32$GT$init_Int64_Real32(Int64, Real32);
void panda$collections$Array$LTpanda$core$Real32$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Real32$GT(panda$collections$Array$LTpanda$core$Real32$GT* self, panda$collections$PrimitiveArray$LTpanda$core$Real32$GT*);
panda$collections$Array$LTpanda$core$Real32$GT* new_panda$collections$Array$LTpanda$core$Real32$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Real32$GT(panda$collections$PrimitiveArray$LTpanda$core$Real32$GT*);
void panda$collections$Array$LTpanda$core$Real32$GT$init_panda$collections$CollectionView$LTpanda$core$Real32$GT(panda$collections$Array$LTpanda$core$Real32$GT* self, panda$collections$CollectionView$LTpanda$core$Real32$GT*);
panda$collections$Array$LTpanda$core$Real32$GT* new_panda$collections$Array$LTpanda$core$Real32$GT$init_panda$collections$CollectionView$LTpanda$core$Real32$GT(panda$collections$CollectionView$LTpanda$core$Real32$GT*);
void panda$collections$Array$LTpanda$core$Real32$GT$swap_Int64_Int64(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64, Int64);
void panda$collections$Array$LTpanda$core$Real32$GT$sort_Int64_Int64_$LPpanda$core$Real32$Cpanda$core$Real32$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64, Int64, void**);
void panda$collections$Array$LTpanda$core$Real32$GT$ensureCapacity_Int64(panda$collections$Array$LTpanda$core$Real32$GT* self, Int64);
extern Int64 class_panda$collections$Array$DEFAULT_COUNT;
extern Bit class_panda$collections$Array$$classInited;
#endif
#endif
