// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Stack$LTpanda$parser$GLRParser$State$GT_H
#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT_H
extern panda$core$Class panda$collections$Stack$LTpanda$parser$GLRParser$State$GT_class;
#ifndef CLASS_panda$collections$Stack$LTpanda$parser$GLRParser$State$GT
#define CLASS_panda$collections$Stack$LTpanda$parser$GLRParser$State$GT
struct panda$collections$Stack$LTpanda$parser$GLRParser$State$GT {
    panda$core$Class* cl;
    panda$collections$List$LTpanda$parser$GLRParser$State$GT* contents;
};

#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self);
#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$push_panda$parser$GLRParser$State_INDEX 4
typedef void(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$push_panda$parser$GLRParser$State_TYPE)(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self, panda$parser$GLRParser$State*);
#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$peek_$Rpanda$parser$GLRParser$State_INDEX 5
typedef panda$parser$GLRParser$State*(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$peek_$Rpanda$parser$GLRParser$State_TYPE)(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self);
#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$peek_Int64_$Rpanda$parser$GLRParser$State_INDEX 6
typedef panda$parser$GLRParser$State*(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$peek_Int64_$Rpanda$parser$GLRParser$State_TYPE)(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self, Int64);
#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$pop_$Rpanda$parser$GLRParser$State_INDEX 7
typedef panda$parser$GLRParser$State*(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$pop_$Rpanda$parser$GLRParser$State_TYPE)(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self);
#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$clear_INDEX 8
typedef void(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$clear_TYPE)(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self);
#define panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$convert_$Rpanda$collections$ListView$LTpanda$parser$GLRParser$State$GT_INDEX 9
typedef panda$collections$ListView$LTpanda$parser$GLRParser$State$GT*(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$convert_$Rpanda$collections$ListView$LTpanda$parser$GLRParser$State$GT_TYPE)(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self);
void panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$init(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self);
panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* new_panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$init();
Int64 panda$collections$Stack$LTpanda$parser$GLRParser$State$GT$get_count_$Rpanda$core$Int64(panda$collections$Stack$LTpanda$parser$GLRParser$State$GT* self);
#endif
#endif
