// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListIterator$LTpanda$core$Int64$GT_H
#define panda$collections$ListIterator$LTpanda$core$Int64$GT_H
extern panda$core$Class panda$collections$ListIterator$LTpanda$core$Int64$GT_class;
#ifndef CLASS_panda$collections$ListIterator$LTpanda$core$Int64$GT
#define CLASS_panda$collections$ListIterator$LTpanda$core$Int64$GT
struct panda$collections$ListIterator$LTpanda$core$Int64$GT {
    panda$core$Class* cl;
    panda$collections$ListView$LTpanda$core$Int64$GT* list;
    Int64 index;
};

#define panda$collections$ListIterator$LTpanda$core$Int64$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$ListIterator$LTpanda$core$Int64$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$ListIterator$LTpanda$core$Int64$GT* self);
#define panda$collections$ListIterator$LTpanda$core$Int64$GT$next_$Rpanda$core$Int64_INDEX 8
typedef Int64(panda$collections$ListIterator$LTpanda$core$Int64$GT$next_$Rpanda$core$Int64_TYPE)(panda$collections$ListIterator$LTpanda$core$Int64$GT* self);
void panda$collections$ListIterator$LTpanda$core$Int64$GT$init_panda$collections$ListView$LTpanda$core$Int64$GT(panda$collections$ListIterator$LTpanda$core$Int64$GT* self, panda$collections$ListView$LTpanda$core$Int64$GT*);
panda$collections$ListIterator$LTpanda$core$Int64$GT* new_panda$collections$ListIterator$LTpanda$core$Int64$GT$init_panda$collections$ListView$LTpanda$core$Int64$GT(panda$collections$ListView$LTpanda$core$Int64$GT*);
#endif
#endif
