// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT_H
#define panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT_H
extern panda$core$Class panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT_class;
#ifndef CLASS_panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT
#define CLASS_panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT
struct panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT_INDEX 4
typedef panda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT*(panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$parser$GLRParser$Action$Z$GT_TYPE)(panda$collections$Iterable$LTpanda$parser$GLRParser$Action$Z$GT* self);
#endif
#endif
