// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListView$LTpanda$core$Immutable$GT_H
#define panda$collections$ListView$LTpanda$core$Immutable$GT_H
extern panda$core$Class panda$collections$ListView$LTpanda$core$Immutable$GT_class;
#ifndef CLASS_panda$collections$ListView$LTpanda$core$Immutable$GT
#define CLASS_panda$collections$ListView$LTpanda$core$Immutable$GT
struct panda$collections$ListView$LTpanda$core$Immutable$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListView$LTpanda$core$Immutable$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Immutable$GT_INDEX 4
typedef panda$collections$Iterator$LTpanda$core$Immutable$GT*(panda$collections$ListView$LTpanda$core$Immutable$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Immutable$GT_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$contains_panda$core$Immutable_$Rpanda$core$Bit_INDEX 11
typedef Bit(panda$collections$ListView$LTpanda$core$Immutable$GT$contains_panda$core$Immutable_$Rpanda$core$Bit_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$convert_$Rpanda$collections$Array$LTpanda$core$Immutable$GT_INDEX 12
typedef panda$collections$Array$LTpanda$core$Immutable$GT*(panda$collections$ListView$LTpanda$core$Immutable$GT$convert_$Rpanda$collections$Array$LTpanda$core$Immutable$GT_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$lastIndexOf_panda$core$Immutable_$Rpanda$core$Int64Wrapper$Z_INDEX 13
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$Immutable$GT$lastIndexOf_panda$core$Immutable_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$lastIndexOf_panda$core$Immutable_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 14
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$Immutable$GT$lastIndexOf_panda$core$Immutable_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$Immutable*, Int64);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$$SLE_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_INDEX 15
typedef panda$collections$ListView$LTpanda$core$Immutable$GT*(panda$collections$ListView$LTpanda$core$Immutable$GT$$SLE_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$$SLE_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_INDEX 16
typedef panda$collections$ListView$LTpanda$core$Immutable$GT*(panda$collections$ListView$LTpanda$core$Immutable$GT$$SLE_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, Int64, Int64, Int64);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$$ARR_Int64_$Rpanda$core$Immutable_INDEX 17
typedef panda$core$Immutable*(panda$collections$ListView$LTpanda$core$Immutable$GT$$ARR_Int64_$Rpanda$core$Immutable_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, Int64);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$convert_$Rpanda$collections$ImmutableArray$LTpanda$core$Immutable$GT_INDEX 18
typedef panda$collections$ImmutableArray$LTpanda$core$Immutable$GT*(panda$collections$ListView$LTpanda$core$Immutable$GT$convert_$Rpanda$collections$ImmutableArray$LTpanda$core$Immutable$GT_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$join_$Rpanda$core$String_INDEX 19
typedef panda$core$String*(panda$collections$ListView$LTpanda$core$Immutable$GT$join_$Rpanda$core$String_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$join_panda$core$String_$Rpanda$core$String_INDEX 20
typedef panda$core$String*(panda$collections$ListView$LTpanda$core$Immutable$GT$join_panda$core$String_$Rpanda$core$String_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$String*);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$indexOf_panda$core$Immutable_$Rpanda$core$Int64Wrapper$Z_INDEX 21
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$Immutable$GT$indexOf_panda$core$Immutable_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$Immutable*);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$indexOf_panda$core$Immutable_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 22
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$Immutable$GT$indexOf_panda$core$Immutable_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$Immutable*, Int64);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$$SLI_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_INDEX 23
typedef panda$collections$ListView$LTpanda$core$Immutable$GT*(panda$collections$ListView$LTpanda$core$Immutable$GT$$SLI_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64);
#define panda$collections$ListView$LTpanda$core$Immutable$GT$$SLI_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_INDEX 24
typedef panda$collections$ListView$LTpanda$core$Immutable$GT*(panda$collections$ListView$LTpanda$core$Immutable$GT$$SLI_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$Immutable$GT_TYPE)(panda$collections$ListView$LTpanda$core$Immutable$GT* self, Int64, Int64, Int64);
#endif
#endif
