// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Map$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_H
#define panda$collections$Map$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_H
extern panda$core$Class panda$collections$Map$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_class;
#ifndef CLASS_panda$collections$Map$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT
#define CLASS_panda$collections$Map$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT
struct panda$collections$Map$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT {
    panda$core$Class* cl;
};

#endif
#endif
