// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_H
#define panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_H
extern panda$core$Class panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_class;
#ifndef CLASS_panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT
#define CLASS_panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT
struct panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT {
    panda$core$Class* cl;
    panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* list;
    Int64 index;
};

#define panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self);
#define panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$next_$R$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_INDEX 8
typedef $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP*(panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$next_$R$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_TYPE)(panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self);
void panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$init_panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT(panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self, panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT*);
panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* new_panda$collections$ListIterator$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$init_panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT(panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT*);
#endif
#endif
