// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure53_H
#define panda$util$JSONParser$closure53_H
extern panda$core$Class panda$util$JSONParser$closure53_class;
#ifndef CLASS_panda$util$JSONParser$closure53
#define CLASS_panda$util$JSONParser$closure53
struct panda$util$JSONParser$closure53 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure53$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure53$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure53* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure53$init(panda$util$JSONParser$closure53* self);
panda$util$JSONParser$closure53* new_panda$util$JSONParser$closure53$init();
#endif
#endif
