// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutablePrimitiveArray_H
#define panda$collections$ImmutablePrimitiveArray_H
extern panda$core$Class panda$collections$ImmutablePrimitiveArray_class;
#ifndef CLASS_panda$collections$ImmutablePrimitiveArray
#define CLASS_panda$collections$ImmutablePrimitiveArray
struct panda$collections$ImmutablePrimitiveArray {
    panda$core$Class* cl;
};

void panda$collections$ImmutablePrimitiveArray$init(panda$collections$ImmutablePrimitiveArray* self);
panda$collections$ImmutablePrimitiveArray* new_panda$collections$ImmutablePrimitiveArray$init();
#endif
#endif
