// This file was automatically generated by the Panda compiler
#ifndef panda$io$InputStream_H
#define panda$io$InputStream_H
extern panda$core$Class panda$io$InputStream_class;
#ifndef CLASS_panda$io$InputStream
#define CLASS_panda$io$InputStream
struct panda$io$InputStream {
    panda$core$Class* cl;
    Bit closed;
};

#define panda$io$InputStream$close_INDEX 4
typedef void(panda$io$InputStream$close_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$lines_$Rpanda$collections$Iterator$LTpanda$core$String$GT_INDEX 5
typedef panda$collections$Iterator$LTpanda$core$String$GT*(panda$io$InputStream$lines_$Rpanda$collections$Iterator$LTpanda$core$String$GT_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$readLine_$Rpanda$core$String$Z_INDEX 6
typedef panda$core$String*(panda$io$InputStream$readLine_$Rpanda$core$String$Z_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$readAsUInt8Array_$Rpanda$collections$Array$LTpanda$core$UInt8$GT_INDEX 7
typedef panda$collections$Array$LTpanda$core$UInt8$GT*(panda$io$InputStream$readAsUInt8Array_$Rpanda$collections$Array$LTpanda$core$UInt8$GT_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$readAsString_$Rpanda$core$String_INDEX 8
typedef panda$core$String*(panda$io$InputStream$readAsString_$Rpanda$core$String_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$read_$Rpanda$core$UInt8Wrapper$Z_INDEX 9
typedef panda$core$UInt8Wrapper*(panda$io$InputStream$read_$Rpanda$core$UInt8Wrapper$Z_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 10
typedef panda$core$Int64Wrapper*(panda$io$InputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$io$InputStream* self, panda$collections$ListWriter$LTpanda$core$UInt8$GT*, Int64);
#define panda$io$InputStream$read_panda$collections$ListWriter$LTpanda$core$Char$GT_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 11
typedef panda$core$Int64Wrapper*(panda$io$InputStream$read_panda$collections$ListWriter$LTpanda$core$Char$GT_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$io$InputStream* self, panda$collections$ListWriter$LTpanda$core$Char$GT*, Int64);
#define panda$io$InputStream$readInt32_$Rpanda$core$Int32Wrapper$Z_INDEX 12
typedef panda$core$Int32Wrapper*(panda$io$InputStream$readInt32_$Rpanda$core$Int32Wrapper$Z_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$readInt64_$Rpanda$core$Int64Wrapper$Z_INDEX 13
typedef panda$core$Int64Wrapper*(panda$io$InputStream$readInt64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$io$InputStream* self);
#define panda$io$InputStream$readInt16_$Rpanda$core$Int16Wrapper$Z_INDEX 14
typedef panda$core$Int16Wrapper*(panda$io$InputStream$readInt16_$Rpanda$core$Int16Wrapper$Z_TYPE)(panda$io$InputStream* self);
panda$core$CharWrapper* panda$io$InputStream$readChar_$Rpanda$core$CharWrapper$Z(panda$io$InputStream* self);
void panda$io$InputStream$sendTo_panda$io$OutputStream(panda$io$InputStream* self, panda$io$OutputStream*);
void panda$io$InputStream$init(panda$io$InputStream* self);
panda$io$InputStream* new_panda$io$InputStream$init();
void panda$io$InputStream$$classInit_class();
extern Int64 class_panda$io$InputStream$BUFFER_SIZE;
extern Bit class_panda$io$InputStream$$classInited;
#endif
#endif
