// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT_H
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT_H
extern panda$core$Class panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT_class;
#ifndef CLASS_panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT
#define CLASS_panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT
struct panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT* self);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$io$File$RP$C$LPpanda$core$Int64$Cpanda$io$File$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$io$File$RP$RP_$R$LPpanda$core$Int64$Cpanda$io$File$RP_INDEX 5
typedef $LPInt64$Cpanda$io$File$RP*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$io$File$RP$C$LPpanda$core$Int64$Cpanda$io$File$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$io$File$RP$RP_$R$LPpanda$core$Int64$Cpanda$io$File$RP_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT* self, void**);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$io$File$RP$C$LPpanda$core$Int64$Cpanda$io$File$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$io$File$RP$RP_$LPpanda$core$Int64$Cpanda$io$File$RP_$R$LPpanda$core$Int64$Cpanda$io$File$RP_INDEX 6
typedef $LPInt64$Cpanda$io$File$RP*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$fold_$LP$LPpanda$core$Int64$Cpanda$io$File$RP$C$LPpanda$core$Int64$Cpanda$io$File$RP$RP$EQ$GT$LP$LPpanda$core$Int64$Cpanda$io$File$RP$RP_$LPpanda$core$Int64$Cpanda$io$File$RP_$R$LPpanda$core$Int64$Cpanda$io$File$RP_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT* self, void**, $LPInt64$Cpanda$io$File$RP*);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$filter_$LP$LPpanda$core$Int64$Cpanda$io$File$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT_INDEX 7
typedef panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$filter_$LP$LPpanda$core$Int64$Cpanda$io$File$RP$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT* self, void**);
#define panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$next_$R$LPpanda$core$Int64$Cpanda$io$File$RP_INDEX 8
typedef $LPInt64$Cpanda$io$File$RP*(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT$next_$R$LPpanda$core$Int64$Cpanda$io$File$RP_TYPE)(panda$collections$Iterator$LT$LPpanda$core$Int64$Cpanda$io$File$RP$GT* self);
#endif
#endif
