// This file was automatically generated by the Panda compiler
#ifndef panda$io$BufferedOutputStream_H
#define panda$io$BufferedOutputStream_H
extern panda$core$Class panda$io$BufferedOutputStream_class;
#ifndef CLASS_panda$io$BufferedOutputStream
#define CLASS_panda$io$BufferedOutputStream
struct panda$io$BufferedOutputStream {
    panda$core$Class* cl;
    Bit closed;
    panda$io$OutputStream* out;
    Bit closeUnderlyingStream;
    Int64 bufferOffset;
    panda$collections$Array$LTpanda$core$UInt8$GT* buffer;
    Int64 bufferSize;
};

#define panda$io$BufferedOutputStream$flush_INDEX 4
typedef void(panda$io$BufferedOutputStream$flush_TYPE)(panda$io$BufferedOutputStream* self);
#define panda$io$BufferedOutputStream$close_INDEX 5
typedef void(panda$io$BufferedOutputStream$close_TYPE)(panda$io$BufferedOutputStream* self);
#define panda$io$BufferedOutputStream$write_UInt8_INDEX 6
typedef void(panda$io$BufferedOutputStream$write_UInt8_TYPE)(panda$io$BufferedOutputStream* self, UInt8);
#define panda$io$BufferedOutputStream$write_panda$collections$ListView$LTpanda$core$UInt8$GT_Int64_Int64_INDEX 8
typedef void(panda$io$BufferedOutputStream$write_panda$collections$ListView$LTpanda$core$UInt8$GT_Int64_Int64_TYPE)(panda$io$BufferedOutputStream* self, panda$collections$ListView$LTpanda$core$UInt8$GT*, Int64, Int64);
void panda$io$BufferedOutputStream$init_panda$io$OutputStream(panda$io$BufferedOutputStream* self, panda$io$OutputStream*);
panda$io$BufferedOutputStream* new_panda$io$BufferedOutputStream$init_panda$io$OutputStream(panda$io$OutputStream*);
void panda$io$BufferedOutputStream$init_panda$io$OutputStream_Int64(panda$io$BufferedOutputStream* self, panda$io$OutputStream*, Int64);
panda$io$BufferedOutputStream* new_panda$io$BufferedOutputStream$init_panda$io$OutputStream_Int64(panda$io$OutputStream*, Int64);
void panda$io$BufferedOutputStream$$classInit_class();
extern Int64 class_panda$io$BufferedOutputStream$DEFAULT_BUFFER_SIZE;
extern Bit class_panda$io$BufferedOutputStream$$classInited;
#endif
#endif
