// This file was automatically generated by the Panda compiler
#ifndef panda$collections$FilterIterator$LTpanda$core$Int8$GT_H
#define panda$collections$FilterIterator$LTpanda$core$Int8$GT_H
extern panda$core$Class panda$collections$FilterIterator$LTpanda$core$Int8$GT_class;
#ifndef CLASS_panda$collections$FilterIterator$LTpanda$core$Int8$GT
#define CLASS_panda$collections$FilterIterator$LTpanda$core$Int8$GT
struct panda$collections$FilterIterator$LTpanda$core$Int8$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$core$Int8$GT* base;
    void** filter;
    panda$core$Int8Wrapper* nextValue;
};

#define panda$collections$FilterIterator$LTpanda$core$Int8$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$FilterIterator$LTpanda$core$Int8$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$FilterIterator$LTpanda$core$Int8$GT* self);
#define panda$collections$FilterIterator$LTpanda$core$Int8$GT$next_$Rpanda$core$Int8_INDEX 8
typedef Int8(panda$collections$FilterIterator$LTpanda$core$Int8$GT$next_$Rpanda$core$Int8_TYPE)(panda$collections$FilterIterator$LTpanda$core$Int8$GT* self);
#define panda$collections$FilterIterator$LTpanda$core$Int8$GT$getNext_INDEX 9
typedef void(panda$collections$FilterIterator$LTpanda$core$Int8$GT$getNext_TYPE)(panda$collections$FilterIterator$LTpanda$core$Int8$GT* self);
void panda$collections$FilterIterator$LTpanda$core$Int8$GT$init_panda$collections$Iterator$LTpanda$core$Int8$GT_$LPpanda$core$Int8$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$FilterIterator$LTpanda$core$Int8$GT* self, panda$collections$Iterator$LTpanda$core$Int8$GT*, void**);
panda$collections$FilterIterator$LTpanda$core$Int8$GT* new_panda$collections$FilterIterator$LTpanda$core$Int8$GT$init_panda$collections$Iterator$LTpanda$core$Int8$GT_$LPpanda$core$Int8$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$core$Int8$GT*, void**);
#endif
#endif
