// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure216_H
#define panda$util$JSONParser$closure216_H
extern panda$core$Class panda$util$JSONParser$closure216_class;
#ifndef CLASS_panda$util$JSONParser$closure216
#define CLASS_panda$util$JSONParser$closure216
struct panda$util$JSONParser$closure216 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure216$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure216$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure216* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure216$init(panda$util$JSONParser$closure216* self);
panda$util$JSONParser$closure216* new_panda$util$JSONParser$closure216$init();
#endif
#endif
