// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Array$LTpanda$core$Int8$GT_H
#define panda$collections$Array$LTpanda$core$Int8$GT_H
extern panda$core$Class panda$collections$Array$LTpanda$core$Int8$GT_class;
#ifndef CLASS_panda$collections$Array$LTpanda$core$Int8$GT
#define CLASS_panda$collections$Array$LTpanda$core$Int8$GT
struct panda$collections$Array$LTpanda$core$Int8$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LTpanda$core$Int8$GT* contents;
    Int64 _count;
};

#define panda$collections$Array$LTpanda$core$Int8$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$Array$LTpanda$core$Int8$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self);
#define panda$collections$Array$LTpanda$core$Int8$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$Array$LTpanda$core$Int8$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, panda$core$Object*);
#define panda$collections$Array$LTpanda$core$Int8$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$Array$LTpanda$core$Int8$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self);
#define panda$collections$Array$LTpanda$core$Int8$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$Array$LTpanda$core$Int8$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self);
#define panda$collections$Array$LTpanda$core$Int8$GT$addAll_panda$collections$CollectionView$LTpanda$core$Int8$GT_INDEX 5
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$addAll_panda$collections$CollectionView$LTpanda$core$Int8$GT_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, panda$collections$CollectionView$LTpanda$core$Int8$GT*);
#define panda$collections$Array$LTpanda$core$Int8$GT$add_Int8_INDEX 6
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$add_Int8_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, Int8);
#define panda$collections$Array$LTpanda$core$Int8$GT$add_panda$collections$ListView$LTpanda$core$Int8$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$add_panda$collections$ListView$LTpanda$core$Int8$GT_Int64_Int64_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, panda$collections$ListView$LTpanda$core$Int8$GT*, Int64, Int64);
#define panda$collections$Array$LTpanda$core$Int8$GT$remove_Int8_INDEX 8
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$remove_Int8_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, Int8);
#define panda$collections$Array$LTpanda$core$Int8$GT$clear_INDEX 9
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$clear_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self);
#define panda$collections$Array$LTpanda$core$Int8$GT$$ARREQ_Int64_Int8_INDEX 10
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$$ARREQ_Int64_Int8_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64, Int8);
#define panda$collections$Array$LTpanda$core$Int8$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$removeIndex_Int64_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64);
#define panda$collections$Array$LTpanda$core$Int8$GT$contains_Int8_$Rpanda$core$Bit_INDEX 19
typedef Bit(panda$collections$Array$LTpanda$core$Int8$GT$contains_Int8_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, Int8);
#define panda$collections$Array$LTpanda$core$Int8$GT$$ARR_Int64_$Rpanda$core$Int8_INDEX 25
typedef Int8(panda$collections$Array$LTpanda$core$Int8$GT$$ARR_Int64_$Rpanda$core$Int8_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64);
#define panda$collections$Array$LTpanda$core$Int8$GT$addAll_panda$collections$Array$LTpanda$core$Int8$GT_INDEX 39
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$addAll_panda$collections$Array$LTpanda$core$Int8$GT_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, panda$collections$Array$LTpanda$core$Int8$GT*);
#define panda$collections$Array$LTpanda$core$Int8$GT$sorted_$LPpanda$core$Int8$Cpanda$core$Int8$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$core$Int8$GT_INDEX 40
typedef panda$collections$Array$LTpanda$core$Int8$GT*(panda$collections$Array$LTpanda$core$Int8$GT$sorted_$LPpanda$core$Int8$Cpanda$core$Int8$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$core$Int8$GT_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, void**);
#define panda$collections$Array$LTpanda$core$Int8$GT$add_panda$collections$Array$LTpanda$core$Int8$GT_Int64_Int64_INDEX 41
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$add_panda$collections$Array$LTpanda$core$Int8$GT_Int64_Int64_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, panda$collections$Array$LTpanda$core$Int8$GT*, Int64, Int64);
#define panda$collections$Array$LTpanda$core$Int8$GT$sort_$LPpanda$core$Int8$Cpanda$core$Int8$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 42
typedef void(panda$collections$Array$LTpanda$core$Int8$GT$sort_$LPpanda$core$Int8$Cpanda$core$Int8$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$Array$LTpanda$core$Int8$GT* self, void**);
void panda$collections$Array$LTpanda$core$Int8$GT$init(panda$collections$Array$LTpanda$core$Int8$GT* self);
panda$collections$Array$LTpanda$core$Int8$GT* new_panda$collections$Array$LTpanda$core$Int8$GT$init();
void panda$collections$Array$LTpanda$core$Int8$GT$init_Int64(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64);
panda$collections$Array$LTpanda$core$Int8$GT* new_panda$collections$Array$LTpanda$core$Int8$GT$init_Int64(Int64);
void panda$collections$Array$LTpanda$core$Int8$GT$init_Int64_Int8(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64, Int8);
panda$collections$Array$LTpanda$core$Int8$GT* new_panda$collections$Array$LTpanda$core$Int8$GT$init_Int64_Int8(Int64, Int8);
void panda$collections$Array$LTpanda$core$Int8$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Int8$GT(panda$collections$Array$LTpanda$core$Int8$GT* self, panda$collections$PrimitiveArray$LTpanda$core$Int8$GT*);
panda$collections$Array$LTpanda$core$Int8$GT* new_panda$collections$Array$LTpanda$core$Int8$GT$init_panda$collections$PrimitiveArray$LTpanda$core$Int8$GT(panda$collections$PrimitiveArray$LTpanda$core$Int8$GT*);
void panda$collections$Array$LTpanda$core$Int8$GT$init_panda$collections$CollectionView$LTpanda$core$Int8$GT(panda$collections$Array$LTpanda$core$Int8$GT* self, panda$collections$CollectionView$LTpanda$core$Int8$GT*);
panda$collections$Array$LTpanda$core$Int8$GT* new_panda$collections$Array$LTpanda$core$Int8$GT$init_panda$collections$CollectionView$LTpanda$core$Int8$GT(panda$collections$CollectionView$LTpanda$core$Int8$GT*);
void panda$collections$Array$LTpanda$core$Int8$GT$swap_Int64_Int64(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64, Int64);
void panda$collections$Array$LTpanda$core$Int8$GT$sort_Int64_Int64_$LPpanda$core$Int8$Cpanda$core$Int8$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64, Int64, void**);
void panda$collections$Array$LTpanda$core$Int8$GT$ensureCapacity_Int64(panda$collections$Array$LTpanda$core$Int8$GT* self, Int64);
extern Int64 class_panda$collections$Array$DEFAULT_COUNT;
extern Bit class_panda$collections$Array$$classInited;
#endif
#endif
