// This file was automatically generated by the Panda compiler
#ifndef panda$parser$GLRParser$Action$Type_H
#define panda$parser$GLRParser$Action$Type_H
extern panda$core$Class panda$parser$GLRParser$Action$Type_class;
#ifndef CLASS_panda$parser$GLRParser$Action$Type
#define CLASS_panda$parser$GLRParser$Action$Type
struct panda$parser$GLRParser$Action$Type {
    panda$core$Class* cl;
};

#define panda$parser$GLRParser$Action$Type$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$parser$GLRParser$Action$Type$convert_$Rpanda$core$String_TYPE)(panda$parser$GLRParser$Action$Type* self);
#define panda$parser$GLRParser$Action$Type$convert_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$parser$GLRParser$Action$Type$convert_$Rpanda$core$Int64_TYPE)(panda$parser$GLRParser$Action$Type* self);
void panda$parser$GLRParser$Action$Type$$classInit_class();
void panda$parser$GLRParser$Action$Type$init(panda$parser$GLRParser$Action$Type* self);
panda$parser$GLRParser$Action$Type* new_panda$parser$GLRParser$Action$Type$init();
panda$parser$GLRParser$Action$Type* panda$parser$GLRParser$Action$Type$fromInt_class_Int64_$Rpanda$parser$GLRParser$Action$Type(Int64);
panda$parser$GLRParser$Action$Type* panda$parser$GLRParser$Action$Type$fromString_class_panda$core$String_$Rpanda$parser$GLRParser$Action$Type(panda$core$String*);
extern panda$parser$GLRParser$Action$Type* class_panda$parser$GLRParser$Action$Type$SHIFT;
extern panda$parser$GLRParser$Action$Type* class_panda$parser$GLRParser$Action$Type$REDUCE;
extern panda$parser$GLRParser$Action$Type* class_panda$parser$GLRParser$Action$Type$CUT;
extern panda$parser$GLRParser$Action$Type* class_panda$parser$GLRParser$Action$Type$MULTIPLE;
extern panda$parser$GLRParser$Action$Type* class_panda$parser$GLRParser$Action$Type$ACCEPT;
extern Bit class_panda$parser$GLRParser$Action$Type$$classInited;
#endif
#endif
