// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Collection_H
#define panda$collections$Collection_H
extern panda$core$Class panda$collections$Collection_class;
#ifndef CLASS_panda$collections$Collection
#define CLASS_panda$collections$Collection
struct panda$collections$Collection {
    panda$core$Class* cl;
};

#endif
#endif
