// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure9_H
#define panda$util$JSONParser$closure9_H
extern panda$core$Class panda$util$JSONParser$closure9_class;
#ifndef CLASS_panda$util$JSONParser$closure9
#define CLASS_panda$util$JSONParser$closure9
struct panda$util$JSONParser$closure9 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure9$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure9$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure9* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure9$init(panda$util$JSONParser$closure9* self);
panda$util$JSONParser$closure9* new_panda$util$JSONParser$closure9$init();
#endif
#endif
