// This file was automatically generated by the Panda compiler
#ifndef panda$math$SharedRandom_H
#define panda$math$SharedRandom_H
extern panda$core$Class panda$math$SharedRandom_class;
#ifndef CLASS_panda$math$SharedRandom
#define CLASS_panda$math$SharedRandom
struct panda$math$SharedRandom {
    panda$core$Class* cl;
};

void panda$math$SharedRandom$init(panda$math$SharedRandom* self);
panda$math$SharedRandom* new_panda$math$SharedRandom$init();
void panda$math$SharedRandom$$classInit_class();
Int64 panda$math$SharedRandom$$initcount_class_$Rpanda$core$Int64();
panda$math$Random* panda$math$SharedRandom$$initinstance_class_$Rpanda$math$Random();
extern Int64 class_panda$math$SharedRandom$count;
extern Int64 class_panda$math$SharedRandom$count$index;
extern panda$math$Random* class_panda$math$SharedRandom$instance;
extern Int64 class_panda$math$SharedRandom$instance$index;
extern Bit class_panda$math$SharedRandom$$classInited;
#endif
#endif
