// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_H
#define panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_H
extern panda$core$Class panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_class;
#ifndef CLASS_panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT
#define CLASS_panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT
struct panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* contents;
};

#define panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#define panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$core$Object*);
#define panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#define panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_count_$Rpanda$core$Int64_INDEX 5
typedef Int64(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
#define panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$ARR_Int64_$R$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_INDEX 17
typedef $LPpanda$core$Immutable$Cpanda$core$Immutable$RP*(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$$ARR_Int64_$R$LPpanda$core$Immutable$Cpanda$core$Immutable$RP_TYPE)(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, Int64);
#define panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$convert_$Rpanda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_INDEX 19
typedef panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$convert_$Rpanda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT_TYPE)(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
void panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self);
panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init();
void panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$PrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
void panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$ImmutablePrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$collections$ImmutablePrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$ImmutablePrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$ImmutablePrimitiveArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
void panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* self, panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT* new_panda$collections$ImmutableArray$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT$init_panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT(panda$collections$CollectionView$LT$LPpanda$core$Immutable$Cpanda$core$Immutable$RP$GT*);
#endif
#endif
