// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT_H
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT_H
extern panda$core$Class panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT_class;
#ifndef CLASS_panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT
#define CLASS_panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT
struct panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT {
    panda$core$Class* cl;
    panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT* contents;
    Int64 _count;
};

#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$convert_$Rpanda$core$String_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_INDEX 2
typedef Bit(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$$EQ_panda$core$Object_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$core$Object*);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$get_hash_$Rpanda$core$Int64_INDEX 3
typedef Int64(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$get_hash_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$addAll_panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT_INDEX 5
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$addAll_panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT*);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$add_panda$parser$GLRParser$ParseError_INDEX 6
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$add_panda$parser$GLRParser$ParseError_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$parser$GLRParser$ParseError*);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$add_panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$add_panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT_Int64_Int64_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$collections$ListView$LTpanda$parser$GLRParser$ParseError$GT*, Int64, Int64);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$remove_panda$parser$GLRParser$ParseError_INDEX 8
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$remove_panda$parser$GLRParser$ParseError_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$parser$GLRParser$ParseError*);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$clear_INDEX 9
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$clear_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$$ARREQ_Int64_panda$parser$GLRParser$ParseError_INDEX 10
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$$ARREQ_Int64_panda$parser$GLRParser$ParseError_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64, panda$parser$GLRParser$ParseError*);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$removeIndex_Int64_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$contains_panda$parser$GLRParser$ParseError_$Rpanda$core$Bit_INDEX 19
typedef Bit(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$contains_panda$parser$GLRParser$ParseError_$Rpanda$core$Bit_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$parser$GLRParser$ParseError*);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$$ARR_Int64_$Rpanda$parser$GLRParser$ParseError_INDEX 25
typedef panda$parser$GLRParser$ParseError*(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$$ARR_Int64_$Rpanda$parser$GLRParser$ParseError_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$sorted_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT_INDEX 39
typedef panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT*(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$sorted_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, void**);
#define panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$sort_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$core$Bit$RP_INDEX 40
typedef void(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$sort_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$core$Bit$RP_TYPE)(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, void**);
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self);
panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* new_panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init();
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_Int64(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64);
panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* new_panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_Int64(Int64);
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_Int64_panda$parser$GLRParser$ParseError(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64, panda$parser$GLRParser$ParseError*);
panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* new_panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_Int64_panda$parser$GLRParser$ParseError(Int64, panda$parser$GLRParser$ParseError*);
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT*);
panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* new_panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$PrimitiveArray$LTpanda$parser$GLRParser$ParseError$GT*);
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT*);
panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* new_panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT*);
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$swap_Int64_Int64(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64, Int64);
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$sort_Int64_Int64_$LPpanda$parser$GLRParser$ParseError$Cpanda$parser$GLRParser$ParseError$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64, Int64, void**);
void panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT$ensureCapacity_Int64(panda$collections$Array$LTpanda$parser$GLRParser$ParseError$GT* self, Int64);
extern Int64 class_panda$collections$Array$DEFAULT_COUNT;
extern Bit class_panda$collections$Array$$classInited;
#endif
#endif
