// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LTpanda$core$Integer$GT_H
#define panda$collections$Iterator$LTpanda$core$Integer$GT_H
extern panda$core$Class panda$collections$Iterator$LTpanda$core$Integer$GT_class;
#ifndef CLASS_panda$collections$Iterator$LTpanda$core$Integer$GT
#define CLASS_panda$collections$Iterator$LTpanda$core$Integer$GT
struct panda$collections$Iterator$LTpanda$core$Integer$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterator$LTpanda$core$Integer$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LTpanda$core$Integer$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LTpanda$core$Integer$GT* self);
#define panda$collections$Iterator$LTpanda$core$Integer$GT$fold_$LPpanda$core$Integer$Cpanda$core$Integer$RP$EQ$GT$LPpanda$core$Integer$RP_$Rpanda$core$Integer_INDEX 5
typedef panda$core$Integer*(panda$collections$Iterator$LTpanda$core$Integer$GT$fold_$LPpanda$core$Integer$Cpanda$core$Integer$RP$EQ$GT$LPpanda$core$Integer$RP_$Rpanda$core$Integer_TYPE)(panda$collections$Iterator$LTpanda$core$Integer$GT* self, void**);
#define panda$collections$Iterator$LTpanda$core$Integer$GT$fold_$LPpanda$core$Integer$Cpanda$core$Integer$RP$EQ$GT$LPpanda$core$Integer$RP_panda$core$Integer_$Rpanda$core$Integer_INDEX 6
typedef panda$core$Integer*(panda$collections$Iterator$LTpanda$core$Integer$GT$fold_$LPpanda$core$Integer$Cpanda$core$Integer$RP$EQ$GT$LPpanda$core$Integer$RP_panda$core$Integer_$Rpanda$core$Integer_TYPE)(panda$collections$Iterator$LTpanda$core$Integer$GT* self, void**, panda$core$Integer*);
#define panda$collections$Iterator$LTpanda$core$Integer$GT$filter_$LPpanda$core$Integer$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$core$Integer$GT_INDEX 7
typedef panda$collections$Iterator$LTpanda$core$Integer$GT*(panda$collections$Iterator$LTpanda$core$Integer$GT$filter_$LPpanda$core$Integer$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$core$Integer$GT_TYPE)(panda$collections$Iterator$LTpanda$core$Integer$GT* self, void**);
#define panda$collections$Iterator$LTpanda$core$Integer$GT$next_$Rpanda$core$Integer_INDEX 8
typedef panda$core$Integer*(panda$collections$Iterator$LTpanda$core$Integer$GT$next_$Rpanda$core$Integer_TYPE)(panda$collections$Iterator$LTpanda$core$Integer$GT* self);
#endif
#endif
