// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListWriter$LTpanda$core$String$Z$GT_H
#define panda$collections$ListWriter$LTpanda$core$String$Z$GT_H
extern panda$core$Class panda$collections$ListWriter$LTpanda$core$String$Z$GT_class;
#ifndef CLASS_panda$collections$ListWriter$LTpanda$core$String$Z$GT
#define CLASS_panda$collections$ListWriter$LTpanda$core$String$Z$GT
struct panda$collections$ListWriter$LTpanda$core$String$Z$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListWriter$LTpanda$core$String$Z$GT$$ARREQ_Int64_panda$core$String$Z_INDEX 10
typedef void(panda$collections$ListWriter$LTpanda$core$String$Z$GT$$ARREQ_Int64_panda$core$String$Z_TYPE)(panda$collections$ListWriter$LTpanda$core$String$Z$GT* self, Int64, panda$core$String*);
#define panda$collections$ListWriter$LTpanda$core$String$Z$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$ListWriter$LTpanda$core$String$Z$GT$removeIndex_Int64_TYPE)(panda$collections$ListWriter$LTpanda$core$String$Z$GT* self, Int64);
#define panda$collections$ListWriter$LTpanda$core$String$Z$GT$insert_Int64_panda$core$String$Z_INDEX 12
typedef void(panda$collections$ListWriter$LTpanda$core$String$Z$GT$insert_Int64_panda$core$String$Z_TYPE)(panda$collections$ListWriter$LTpanda$core$String$Z$GT* self, Int64, panda$core$String*);
#endif
#endif
