// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LTpanda$core$Char$GT_H
#define panda$collections$Iterator$LTpanda$core$Char$GT_H
extern panda$core$Class panda$collections$Iterator$LTpanda$core$Char$GT_class;
#ifndef CLASS_panda$collections$Iterator$LTpanda$core$Char$GT
#define CLASS_panda$collections$Iterator$LTpanda$core$Char$GT
struct panda$collections$Iterator$LTpanda$core$Char$GT {
    panda$core$Class* cl;
};

#define panda$collections$Iterator$LTpanda$core$Char$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LTpanda$core$Char$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LTpanda$core$Char$GT* self);
#define panda$collections$Iterator$LTpanda$core$Char$GT$fold_$LPpanda$core$Char$Cpanda$core$Char$RP$EQ$GT$LPpanda$core$Char$RP_$Rpanda$core$Char_INDEX 5
typedef Char(panda$collections$Iterator$LTpanda$core$Char$GT$fold_$LPpanda$core$Char$Cpanda$core$Char$RP$EQ$GT$LPpanda$core$Char$RP_$Rpanda$core$Char_TYPE)(panda$collections$Iterator$LTpanda$core$Char$GT* self, void**);
#define panda$collections$Iterator$LTpanda$core$Char$GT$fold_$LPpanda$core$Char$Cpanda$core$Char$RP$EQ$GT$LPpanda$core$Char$RP_Char_$Rpanda$core$Char_INDEX 6
typedef Char(panda$collections$Iterator$LTpanda$core$Char$GT$fold_$LPpanda$core$Char$Cpanda$core$Char$RP$EQ$GT$LPpanda$core$Char$RP_Char_$Rpanda$core$Char_TYPE)(panda$collections$Iterator$LTpanda$core$Char$GT* self, void**, Char);
#define panda$collections$Iterator$LTpanda$core$Char$GT$filter_$LPpanda$core$Char$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$core$Char$GT_INDEX 7
typedef panda$collections$Iterator$LTpanda$core$Char$GT*(panda$collections$Iterator$LTpanda$core$Char$GT$filter_$LPpanda$core$Char$RP$EQ$GT$LPpanda$core$Bit$RP_$Rpanda$collections$Iterator$LTpanda$core$Char$GT_TYPE)(panda$collections$Iterator$LTpanda$core$Char$GT* self, void**);
#define panda$collections$Iterator$LTpanda$core$Char$GT$next_$Rpanda$core$Char_INDEX 8
typedef Char(panda$collections$Iterator$LTpanda$core$Char$GT$next_$Rpanda$core$Char_TYPE)(panda$collections$Iterator$LTpanda$core$Char$GT* self);
#endif
#endif
