// This file was automatically generated by the Panda compiler
#ifndef panda$core$System$OperatingEnvironmentInfo_H
#define panda$core$System$OperatingEnvironmentInfo_H
extern panda$core$Class panda$core$System$OperatingEnvironmentInfo_class;
#ifndef CLASS_panda$core$System$OperatingEnvironmentInfo
#define CLASS_panda$core$System$OperatingEnvironmentInfo
struct panda$core$System$OperatingEnvironmentInfo {
    panda$core$Class* cl;
    panda$core$System$Type* type;
    panda$core$System$OperatingSystem* operatingSystem;
};

void panda$core$System$OperatingEnvironmentInfo$init_panda$core$System$Type_panda$core$System$OperatingSystem(panda$core$System$OperatingEnvironmentInfo* self, panda$core$System$Type*, panda$core$System$OperatingSystem*);
panda$core$System$OperatingEnvironmentInfo* new_panda$core$System$OperatingEnvironmentInfo$init_panda$core$System$Type_panda$core$System$OperatingSystem(panda$core$System$Type*, panda$core$System$OperatingSystem*);
#endif
#endif
