// This file was automatically generated by the Panda compiler
#ifndef panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT_H
#define panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT_H
extern panda$core$Class panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT_class;
#ifndef CLASS_panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT
#define CLASS_panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT
struct panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT {
    panda$core$Class* cl;
    panda$collections$HashMap$LTpanda$core$Immutable$Cpanda$core$Object$GT* map;
    Int64 index;
    panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT* entry;
    Int64 changeCount;
};

#define panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT* self);
#define panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$next_$R$LPpanda$core$Immutable$Cpanda$core$Object$RP_INDEX 8
typedef $LPpanda$core$Immutable$Cpanda$core$Object$RP*(panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$next_$R$LPpanda$core$Immutable$Cpanda$core$Object$RP_TYPE)(panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT* self);
#define panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$result_panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT_$R$LPpanda$core$Immutable$Cpanda$core$Object$RP_INDEX 9
typedef $LPpanda$core$Immutable$Cpanda$core$Object$RP*(panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$result_panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT_$R$LPpanda$core$Immutable$Cpanda$core$Object$RP_TYPE)(panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT* self, panda$collections$MutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Object$GT*);
void panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$init_panda$collections$HashMap$LTpanda$core$Immutable$Cpanda$core$Object$GT(panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT* self, panda$collections$HashMap$LTpanda$core$Immutable$Cpanda$core$Object$GT*);
panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT* new_panda$collections$HashMapIterator$LTpanda$core$Immutable$Cpanda$core$Object$C$LPpanda$core$Immutable$Cpanda$core$Object$RP$GT$init_panda$collections$HashMap$LTpanda$core$Immutable$Cpanda$core$Object$GT(panda$collections$HashMap$LTpanda$core$Immutable$Cpanda$core$Object$GT*);
#endif
#endif
