// This file was automatically generated by the Panda compiler
#ifndef panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_H
#define panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_H
extern panda$core$Class panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_class;
#ifndef CLASS_panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT
#define CLASS_panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT
struct panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT {
    panda$core$Class* cl;
    panda$core$Object* key;
    panda$core$Object* value;
    panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT* next;
};

void panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$init_panda$core$Object$Z_panda$core$Object$Z(panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT* self, panda$core$Object*, panda$core$Object*);
panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT* new_panda$collections$MutableMapEntry$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$init_panda$core$Object$Z_panda$core$Object$Z(panda$core$Object*, panda$core$Object*);
#endif
#endif
