// This file was automatically generated by the Panda compiler
#ifndef panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_H
#define panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_H
extern panda$core$Class panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_class;
#ifndef CLASS_panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT
#define CLASS_panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT
struct panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT {
    panda$core$Class* cl;
};

#define panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$addAll_panda$collections$MapView$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_INDEX 4
typedef void(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$addAll_panda$collections$MapView$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT_TYPE)(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT* self, panda$collections$MapView$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT*);
#define panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$remove_panda$core$Object$Z_INDEX 5
typedef void(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$remove_panda$core$Object$Z_TYPE)(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT* self, panda$core$Object*);
#define panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$$ARREQ_panda$core$Object$Z_panda$core$Object$Z_INDEX 6
typedef void(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$$ARREQ_panda$core$Object$Z_panda$core$Object$Z_TYPE)(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT* self, panda$core$Object*, panda$core$Object*);
#define panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$clear_INDEX 7
typedef void(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT$clear_TYPE)(panda$collections$MapWriter$LTpanda$core$Object$Z$Cpanda$core$Object$Z$GT* self);
#endif
#endif
