// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_H
#define panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_H
extern panda$core$Class panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT_class;
#ifndef CLASS_panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT
#define CLASS_panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT
struct panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT {
    panda$core$Class* cl;
    panda$core$Immutable* key;
    panda$core$Immutable* value;
    panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* next;
};

void panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$core$Immutable_panda$core$Immutable_panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$Z(panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* self, panda$core$Immutable*, panda$core$Immutable*, panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT*);
panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT* new_panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$init_panda$core$Immutable_panda$core$Immutable_panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT$Z(panda$core$Immutable*, panda$core$Immutable*, panda$collections$ImmutableMapEntry$LTpanda$core$Immutable$Cpanda$core$Immutable$GT*);
#endif
#endif
