// This file was automatically generated by the Panda compiler
#ifndef panda$io$BufferedInputStream_H
#define panda$io$BufferedInputStream_H
extern panda$core$Class panda$io$BufferedInputStream_class;
#ifndef CLASS_panda$io$BufferedInputStream
#define CLASS_panda$io$BufferedInputStream
struct panda$io$BufferedInputStream {
    panda$core$Class* cl;
    Bit closed;
    panda$io$InputStream* raw;
    Bit closeUnderlyingStream;
    panda$collections$Array$LTpanda$core$UInt8$GT* buffer;
    Int64 bufferSize;
    Int64 pos;
    Int64 limit;
};

#define panda$io$BufferedInputStream$read_$Rpanda$core$UInt8Wrapper$Z_INDEX 9
typedef panda$core$UInt8Wrapper*(panda$io$BufferedInputStream$read_$Rpanda$core$UInt8Wrapper$Z_TYPE)(panda$io$BufferedInputStream* self);
#define panda$io$BufferedInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 10
typedef panda$core$Int64Wrapper*(panda$io$BufferedInputStream$read_panda$collections$ListWriter$LTpanda$core$UInt8$GT_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$io$BufferedInputStream* self, panda$collections$ListWriter$LTpanda$core$UInt8$GT*, Int64);
void panda$io$BufferedInputStream$init_panda$io$InputStream(panda$io$BufferedInputStream* self, panda$io$InputStream*);
panda$io$BufferedInputStream* new_panda$io$BufferedInputStream$init_panda$io$InputStream(panda$io$InputStream*);
void panda$io$BufferedInputStream$init_panda$io$InputStream_Int64(panda$io$BufferedInputStream* self, panda$io$InputStream*, Int64);
panda$io$BufferedInputStream* new_panda$io$BufferedInputStream$init_panda$io$InputStream_Int64(panda$io$InputStream*, Int64);
void panda$io$BufferedInputStream$fillBuffer(panda$io$BufferedInputStream* self);
void panda$io$BufferedInputStream$$classInit_class();
extern Int64 class_panda$io$BufferedInputStream$DEFAULT_BUFFER_SIZE;
extern Bit class_panda$io$BufferedInputStream$$classInited;
#endif
#endif
