// This file was automatically generated by the Panda compiler
#ifndef panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT_H
#define panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT_H
extern panda$core$Class panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT_class;
#ifndef CLASS_panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT
#define CLASS_panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT
struct panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT* base;
    void** filter;
    panda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT* nextValue;
};

#define panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT* self);
#define panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$next_$Rpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT_INDEX 8
typedef panda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT*(panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$next_$Rpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT_TYPE)(panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT* self);
#define panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$getNext_INDEX 9
typedef void(panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$getNext_TYPE)(panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT* self);
void panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$init_panda$collections$Iterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT_$LPpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT* self, panda$collections$Iterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT*, void**);
panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT* new_panda$collections$FilterIterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT$init_panda$collections$Iterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT_$LPpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$collections$ImmutableArray$LTpanda$core$Int64Wrapper$Z$GT$GT*, void**);
#endif
#endif
