// This file was automatically generated by the Panda compiler
#ifndef panda$parser$GLRParser$StateNode_H
#define panda$parser$GLRParser$StateNode_H
extern panda$core$Class panda$parser$GLRParser$StateNode_class;
#ifndef CLASS_panda$parser$GLRParser$StateNode
#define CLASS_panda$parser$GLRParser$StateNode
struct panda$parser$GLRParser$StateNode {
    panda$core$Class* cl;
    Int64 state;
    panda$core$Object* output;
    panda$parser$GLRParser$StateNode* next;
};

#define panda$parser$GLRParser$StateNode$convert_$Rpanda$core$String_INDEX 1
typedef panda$core$String*(panda$parser$GLRParser$StateNode$convert_$Rpanda$core$String_TYPE)(panda$parser$GLRParser$StateNode* self);
void panda$parser$GLRParser$StateNode$init_Int64_panda$core$Object$Z_panda$parser$GLRParser$StateNode$Z(panda$parser$GLRParser$StateNode* self, Int64, panda$core$Object*, panda$parser$GLRParser$StateNode*);
panda$parser$GLRParser$StateNode* new_panda$parser$GLRParser$StateNode$init_Int64_panda$core$Object$Z_panda$parser$GLRParser$StateNode$Z(Int64, panda$core$Object*, panda$parser$GLRParser$StateNode*);
#endif
#endif
