// This file was automatically generated by the Panda compiler
#ifndef panda$core$Environment_H
#define panda$core$Environment_H
extern panda$core$Class panda$core$Environment_class;
#ifndef CLASS_panda$core$Environment
#define CLASS_panda$core$Environment
struct panda$core$Environment {
    panda$core$Class* cl;
};

#define panda$core$Environment$$ARR_panda$core$String_$Rpanda$core$String$Z_INDEX 4
typedef panda$core$String*(panda$core$Environment$$ARR_panda$core$String_$Rpanda$core$String$Z_TYPE)(panda$core$Environment* self, panda$core$String*);
panda$core$String* panda$core$Environment$pandaGetEnv_class_panda$core$String_$Rpanda$core$String$Z(panda$core$String*);
void panda$core$Environment$init(panda$core$Environment* self);
panda$core$Environment* new_panda$core$Environment$init();
#endif
#endif
