// This file was automatically generated by the Panda compiler
#ifndef panda$core$Immutable_H
#define panda$core$Immutable_H
extern panda$core$Class panda$core$Immutable_class;
#ifndef CLASS_panda$core$Immutable
#define CLASS_panda$core$Immutable
struct panda$core$Immutable {
    panda$core$Class* cl;
};

void panda$core$Immutable$init(panda$core$Immutable* self);
panda$core$Immutable* new_panda$core$Immutable$init();
#endif
#endif
