// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListView$LTpanda$core$String$GT_H
#define panda$collections$ListView$LTpanda$core$String$GT_H
extern panda$core$Class panda$collections$ListView$LTpanda$core$String$GT_class;
#ifndef CLASS_panda$collections$ListView$LTpanda$core$String$GT
#define CLASS_panda$collections$ListView$LTpanda$core$String$GT
struct panda$collections$ListView$LTpanda$core$String$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListView$LTpanda$core$String$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$String$GT_INDEX 4
typedef panda$collections$Iterator$LTpanda$core$String$GT*(panda$collections$ListView$LTpanda$core$String$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$String$GT_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self);
#define panda$collections$ListView$LTpanda$core$String$GT$contains_panda$core$String_$Rpanda$core$Bit_INDEX 11
typedef Bit(panda$collections$ListView$LTpanda$core$String$GT$contains_panda$core$String_$Rpanda$core$Bit_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$String*);
#define panda$collections$ListView$LTpanda$core$String$GT$convert_$Rpanda$collections$Array$LTpanda$core$String$GT_INDEX 12
typedef panda$collections$Array$LTpanda$core$String$GT*(panda$collections$ListView$LTpanda$core$String$GT$convert_$Rpanda$collections$Array$LTpanda$core$String$GT_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self);
#define panda$collections$ListView$LTpanda$core$String$GT$lastIndexOf_panda$core$String_$Rpanda$core$Int64Wrapper$Z_INDEX 13
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$String$GT$lastIndexOf_panda$core$String_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$String*);
#define panda$collections$ListView$LTpanda$core$String$GT$lastIndexOf_panda$core$String_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 14
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$String$GT$lastIndexOf_panda$core$String_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$String*, Int64);
#define panda$collections$ListView$LTpanda$core$String$GT$$SLE_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_INDEX 15
typedef panda$collections$ListView$LTpanda$core$String$GT*(panda$collections$ListView$LTpanda$core$String$GT$$SLE_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64);
#define panda$collections$ListView$LTpanda$core$String$GT$$SLE_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_INDEX 16
typedef panda$collections$ListView$LTpanda$core$String$GT*(panda$collections$ListView$LTpanda$core$String$GT$$SLE_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, Int64, Int64, Int64);
#define panda$collections$ListView$LTpanda$core$String$GT$$ARR_Int64_$Rpanda$core$String_INDEX 17
typedef panda$core$String*(panda$collections$ListView$LTpanda$core$String$GT$$ARR_Int64_$Rpanda$core$String_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, Int64);
#define panda$collections$ListView$LTpanda$core$String$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Object$Z$GT_INDEX 18
typedef panda$collections$Iterator$LTpanda$core$Object$Z$GT*(panda$collections$ListView$LTpanda$core$String$GT$get_iterator_$Rpanda$collections$Iterator$LTpanda$core$Object$Z$GT_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self);
#define panda$collections$ListView$LTpanda$core$String$GT$join_$Rpanda$core$String_INDEX 19
typedef panda$core$String*(panda$collections$ListView$LTpanda$core$String$GT$join_$Rpanda$core$String_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self);
#define panda$collections$ListView$LTpanda$core$String$GT$join_panda$core$String_$Rpanda$core$String_INDEX 20
typedef panda$core$String*(panda$collections$ListView$LTpanda$core$String$GT$join_panda$core$String_$Rpanda$core$String_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$String*);
#define panda$collections$ListView$LTpanda$core$String$GT$indexOf_panda$core$String_$Rpanda$core$Int64Wrapper$Z_INDEX 21
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$String$GT$indexOf_panda$core$String_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$String*);
#define panda$collections$ListView$LTpanda$core$String$GT$indexOf_panda$core$String_Int64_$Rpanda$core$Int64Wrapper$Z_INDEX 22
typedef panda$core$Int64Wrapper*(panda$collections$ListView$LTpanda$core$String$GT$indexOf_panda$core$String_Int64_$Rpanda$core$Int64Wrapper$Z_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$String*, Int64);
#define panda$collections$ListView$LTpanda$core$String$GT$$SLI_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_INDEX 23
typedef panda$collections$ListView$LTpanda$core$String$GT*(panda$collections$ListView$LTpanda$core$String$GT$$SLI_panda$core$Int64Wrapper$Z_panda$core$Int64Wrapper$Z_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, panda$core$Int64Wrapper*, panda$core$Int64Wrapper*, Int64);
#define panda$collections$ListView$LTpanda$core$String$GT$$SLI_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_INDEX 24
typedef panda$collections$ListView$LTpanda$core$String$GT*(panda$collections$ListView$LTpanda$core$String$GT$$SLI_Int64_Int64_Int64_$Rpanda$collections$ListView$LTpanda$core$String$GT_TYPE)(panda$collections$ListView$LTpanda$core$String$GT* self, Int64, Int64, Int64);
#endif
#endif
