// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT_H
#define panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT_H
extern panda$core$Class panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT_class;
#ifndef CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT
#define CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT
struct panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT {
    panda$core$Class* cl;
    Int64 $length;
    panda$io$File** contents;
};

#define panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT$length_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT$length_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutablePrimitiveArray$LTpanda$io$File$GT* self);
#endif
#endif
