// This file was automatically generated by the Panda compiler
#ifndef panda$io$Console_H
#define panda$io$Console_H
extern panda$core$Class panda$io$Console_class;
#ifndef CLASS_panda$io$Console
#define CLASS_panda$io$Console
struct panda$io$Console {
    panda$core$Class* cl;
};

void panda$io$Console$init(panda$io$Console* self);
panda$io$Console* new_panda$io$Console$init();
panda$core$CharWrapper* panda$io$Console$read_class_$Rpanda$core$CharWrapper$Z();
panda$core$String* panda$io$Console$readLine_class_$Rpanda$core$String$Z();
void panda$io$Console$write_class_panda$core$String(panda$core$String*);
void panda$io$Console$write_class_panda$core$Object(panda$core$Object*);
void panda$io$Console$write_class_panda$core$String_panda$collections$ListView$LTpanda$core$Object$GT(panda$core$String*, panda$collections$ListView$LTpanda$core$Object$GT*);
void panda$io$Console$writeLine_class_panda$core$String(panda$core$String*);
void panda$io$Console$writeLine_class_panda$core$Object(panda$core$Object*);
void panda$io$Console$writeLine_class_panda$core$String_panda$collections$ListView$LTpanda$core$Object$GT(panda$core$String*, panda$collections$ListView$LTpanda$core$Object$GT*);
void panda$io$Console$writeLine_class();
void* panda$io$Console$stdIn_class_$Rpanda$core$$NativePointer();
void* panda$io$Console$stdOut_class_$Rpanda$core$$NativePointer();
void panda$io$Console$$classInit_class();
panda$io$FileInputStream* panda$io$Console$$initinputStream_class_$Rpanda$io$FileInputStream();
panda$io$FileOutputStream* panda$io$Console$$initoutputStream_class_$Rpanda$io$FileOutputStream();
extern panda$io$FileInputStream* class_panda$io$Console$inputStream;
extern Int64 class_panda$io$Console$inputStream$index;
extern panda$io$FileOutputStream* class_panda$io$Console$outputStream;
extern Int64 class_panda$io$Console$outputStream$index;
extern Bit class_panda$io$Console$$classInited;
#endif
#endif
