// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Iterator$LTpanda$core$Object$GT$closure73_H
#define panda$collections$Iterator$LTpanda$core$Object$GT$closure73_H
extern panda$core$Class panda$collections$Iterator$LTpanda$core$Object$GT$closure73_class;
#ifndef CLASS_panda$collections$Iterator$LTpanda$core$Object$GT$closure73
#define CLASS_panda$collections$Iterator$LTpanda$core$Object$GT$closure73
struct panda$collections$Iterator$LTpanda$core$Object$GT$closure73 {
    panda$core$Class* cl;
    void** $capture72;
};

#define panda$collections$Iterator$LTpanda$core$Object$GT$closure73$closure_panda$core$Object$Z_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Iterator$LTpanda$core$Object$GT$closure73$closure_panda$core$Object$Z_$Rpanda$core$Bit_TYPE)(panda$collections$Iterator$LTpanda$core$Object$GT$closure73* self, panda$core$Object*);
void panda$collections$Iterator$LTpanda$core$Object$GT$closure73$init_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP(panda$collections$Iterator$LTpanda$core$Object$GT$closure73* self, void**);
panda$collections$Iterator$LTpanda$core$Object$GT$closure73* new_panda$collections$Iterator$LTpanda$core$Object$GT$closure73$init_$LPpanda$core$Object$RP$EQ$GT$LPpanda$core$Bit$RP(void**);
#endif
#endif
