// This file was automatically generated by the Panda compiler
#ifndef panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT_H
#define panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT_H
extern panda$core$Class panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT_class;
#ifndef CLASS_panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT
#define CLASS_panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT
struct panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT {
    panda$core$Class* cl;
    panda$collections$Iterator$LTpanda$parser$GLRParser$ParseError$GT* base;
    Int64 index;
};

#define panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT$get_done_$Rpanda$core$Bit_INDEX 4
typedef Bit(panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT$get_done_$Rpanda$core$Bit_TYPE)(panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT* self);
#define panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT$next_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP_INDEX 8
typedef $LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP*(panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT$next_$R$LPpanda$core$Int64$Cpanda$parser$GLRParser$ParseError$RP_TYPE)(panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT* self);
void panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT* self, panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT*);
panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT* new_panda$collections$Enumerator$LTpanda$parser$GLRParser$ParseError$GT$init_panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT(panda$collections$CollectionView$LTpanda$parser$GLRParser$ParseError$GT*);
#endif
#endif
