// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure202_H
#define panda$util$JSONParser$closure202_H
extern panda$core$Class panda$util$JSONParser$closure202_class;
#ifndef CLASS_panda$util$JSONParser$closure202
#define CLASS_panda$util$JSONParser$closure202
struct panda$util$JSONParser$closure202 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure202$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure202$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure202* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure202$init(panda$util$JSONParser$closure202* self);
panda$util$JSONParser$closure202* new_panda$util$JSONParser$closure202$init();
#endif
#endif
