// This file was automatically generated by the Panda compiler
#ifndef panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_H
#define panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_H
extern panda$core$Class panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_class;
#ifndef CLASS_panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT
#define CLASS_panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT
struct panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT {
    panda$core$Class* cl;
};

#define panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$get_count_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$get_count_$Rpanda$core$Int64_TYPE)(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self);
#define panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$addAll_panda$collections$CollectionView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_INDEX 5
typedef void(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$addAll_panda$collections$CollectionView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_TYPE)(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self, panda$collections$CollectionView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT*);
#define panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$add_$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_INDEX 6
typedef void(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$add_$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_TYPE)(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self, $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP*);
#define panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$add_panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_Int64_Int64_INDEX 7
typedef void(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$add_panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT_Int64_Int64_TYPE)(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self, panda$collections$ListView$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT*, Int64, Int64);
#define panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$remove_$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_INDEX 8
typedef void(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$remove_$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP_TYPE)(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self, $LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP*);
#define panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$clear_INDEX 9
typedef void(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT$clear_TYPE)(panda$collections$CollectionWriter$LT$LPpanda$core$Object$Z$Cpanda$core$Object$Z$RP$GT* self);
#endif
#endif
