// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT_H
#define panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT_H
extern panda$core$Class panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT_class;
#ifndef CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT
#define CLASS_panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT
struct panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT {
    panda$core$Class* cl;
    Int64 $length;
    panda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT** contents;
};

#define panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT$length_$Rpanda$core$Int64_INDEX 4
typedef Int64(panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT$length_$Rpanda$core$Int64_TYPE)(panda$collections$ImmutablePrimitiveArray$LTpanda$collections$ImmutableArray$LTpanda$parser$GLRParser$Action$Z$GT$GT* self);
#endif
#endif
