// This file was automatically generated by the Panda compiler
#ifndef panda$collections$ListWriter$LTpanda$core$UInt8$GT_H
#define panda$collections$ListWriter$LTpanda$core$UInt8$GT_H
extern panda$core$Class panda$collections$ListWriter$LTpanda$core$UInt8$GT_class;
#ifndef CLASS_panda$collections$ListWriter$LTpanda$core$UInt8$GT
#define CLASS_panda$collections$ListWriter$LTpanda$core$UInt8$GT
struct panda$collections$ListWriter$LTpanda$core$UInt8$GT {
    panda$core$Class* cl;
};

#define panda$collections$ListWriter$LTpanda$core$UInt8$GT$$ARREQ_Int64_UInt8_INDEX 10
typedef void(panda$collections$ListWriter$LTpanda$core$UInt8$GT$$ARREQ_Int64_UInt8_TYPE)(panda$collections$ListWriter$LTpanda$core$UInt8$GT* self, Int64, UInt8);
#define panda$collections$ListWriter$LTpanda$core$UInt8$GT$removeIndex_Int64_INDEX 11
typedef void(panda$collections$ListWriter$LTpanda$core$UInt8$GT$removeIndex_Int64_TYPE)(panda$collections$ListWriter$LTpanda$core$UInt8$GT* self, Int64);
#define panda$collections$ListWriter$LTpanda$core$UInt8$GT$insert_Int64_UInt8_INDEX 12
typedef void(panda$collections$ListWriter$LTpanda$core$UInt8$GT$insert_Int64_UInt8_TYPE)(panda$collections$ListWriter$LTpanda$core$UInt8$GT* self, Int64, UInt8);
#endif
#endif
