// This file was automatically generated by the Panda compiler
#ifndef panda$parser$GLRParser$Reducer_H
#define panda$parser$GLRParser$Reducer_H
extern panda$core$Class panda$parser$GLRParser$Reducer_class;
#ifndef CLASS_panda$parser$GLRParser$Reducer
#define CLASS_panda$parser$GLRParser$Reducer
struct panda$parser$GLRParser$Reducer {
    panda$core$Class* cl;
};

#define panda$parser$GLRParser$Reducer$reduce_Int64_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$parser$GLRParser$Reducer$reduce_Int64_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$parser$GLRParser$Reducer* self, Int64, panda$parser$GLRParser$State*);
#endif
#endif
