// This file was automatically generated by the Panda compiler
#ifndef panda$core$OverflowError_H
#define panda$core$OverflowError_H
extern panda$core$Class panda$core$OverflowError_class;
#ifndef CLASS_panda$core$OverflowError
#define CLASS_panda$core$OverflowError
struct panda$core$OverflowError {
    panda$core$Class* cl;
    panda$core$String* message;
    panda$collections$ImmutablePrimitiveArray$LTpanda$core$StackTraceEntry$GT* stack;
};

void panda$core$OverflowError$init(panda$core$OverflowError* self);
panda$core$OverflowError* new_panda$core$OverflowError$init();
void panda$core$OverflowError$init_panda$core$String(panda$core$OverflowError* self, panda$core$String*);
panda$core$OverflowError* new_panda$core$OverflowError$init_panda$core$String(panda$core$String*);
#endif
#endif
