// This file was automatically generated by the Panda compiler
#ifndef panda$core$ParameterError_H
#define panda$core$ParameterError_H
extern panda$core$Class panda$core$ParameterError_class;
#ifndef CLASS_panda$core$ParameterError
#define CLASS_panda$core$ParameterError
struct panda$core$ParameterError {
    panda$core$Class* cl;
    panda$core$String* message;
    panda$collections$ImmutablePrimitiveArray$LTpanda$core$StackTraceEntry$GT* stack;
};

void panda$core$ParameterError$init(panda$core$ParameterError* self);
panda$core$ParameterError* new_panda$core$ParameterError$init();
void panda$core$ParameterError$init_panda$core$String(panda$core$ParameterError* self, panda$core$String*);
panda$core$ParameterError* new_panda$core$ParameterError$init_panda$core$String(panda$core$String*);
#endif
#endif
