// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure175_H
#define panda$util$JSONParser$closure175_H
extern panda$core$Class panda$util$JSONParser$closure175_class;
#ifndef CLASS_panda$util$JSONParser$closure175
#define CLASS_panda$util$JSONParser$closure175
struct panda$util$JSONParser$closure175 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure175$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure175$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure175* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure175$init(panda$util$JSONParser$closure175* self);
panda$util$JSONParser$closure175* new_panda$util$JSONParser$closure175$init();
#endif
#endif
