// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure4_H
#define panda$util$JSONParser$closure4_H
extern panda$core$Class panda$util$JSONParser$closure4_class;
#ifndef CLASS_panda$util$JSONParser$closure4
#define CLASS_panda$util$JSONParser$closure4
struct panda$util$JSONParser$closure4 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure4$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure4$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure4* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure4$init(panda$util$JSONParser$closure4* self);
panda$util$JSONParser$closure4* new_panda$util$JSONParser$closure4$init();
#endif
#endif
