// This file was automatically generated by the Panda compiler
#ifndef panda$util$JSONParser$closure21_H
#define panda$util$JSONParser$closure21_H
extern panda$core$Class panda$util$JSONParser$closure21_class;
#ifndef CLASS_panda$util$JSONParser$closure21
#define CLASS_panda$util$JSONParser$closure21
struct panda$util$JSONParser$closure21 {
    panda$core$Class* cl;
};

#define panda$util$JSONParser$closure21$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_INDEX 4
typedef panda$core$Object*(panda$util$JSONParser$closure21$closure_panda$parser$GLRParser$State_$Rpanda$core$Object$Z_TYPE)(panda$util$JSONParser$closure21* self, panda$parser$GLRParser$State*);
void panda$util$JSONParser$closure21$init(panda$util$JSONParser$closure21* self);
panda$util$JSONParser$closure21* new_panda$util$JSONParser$closure21$init();
#endif
#endif
